"""Planches manga du cours LaTeX (9 chapitres). Usage : python3 manga31.py <page>"""
import sys, pathlib
sys.path.insert(0, str(pathlib.Path(__file__).parent))
from manga_gabarit import strip3, apply
F = lambda *a: strip3(*a)
N = dict(rack=False, nuit=False)
STRIPS = [
 ("c1", F("mglx1", "ça compile chez moi", "LaTeX 1",
   dict(term=["TeX installé sur le poste", "  version de 2019", "  paquets ajoutés à la main"], bulle=["Chez moi,", "ça compile."]),
   dict(term=["serveur de génération :", "  ! File `fontspec.sty' not found", "  rapports du lundi absents"], **N, who='mika', expr='shock', sfx="KO"),
   "compiler en conteneur", ["image TeX Live épinglée", "latexmk partout", "même résultat sur tous les postes", "CI qui compile"],
   "Une distribution installée à la main diffère d'un poste à l'autre : l'image TeX Live épinglée compile partout de la même façon.")),
 ("c2", F("mglx2", "le tiret bas qui casse tout", "LaTeX 2",
   dict(term=["Voir le fichier", "  rapport_final_2026.pdf", "  (texte copié tel quel)"], bulle=["C'est du", "texte simple."]),
   dict(term=["! Missing $ inserted.", "  l.42 rapport_", "  compilation arrêtée"], **N, who='kai', expr='shock', sfx="$"),
   "échapper les spéciaux", ["# $ % & ~ _ ^ \\ { }", "\\_ pour le tiret bas", "\\url pour les chemins", "fonction d'échappement unique"],
   "Dix caractères ont un sens pour LaTeX : on les échappe, et pour du texte généré, par une seule fonction appliquée à toutes les valeurs.")),
 ("c3", F("mglx3", "les marges de chacun", "LaTeX 3",
   dict(term=["\\usepackage[margin=1.5cm]{geometry}", "  \\usepackage[margin=3cm]{geometry}", "  (selon le rédacteur)"], bulle=["Chacun a", "ses réglages."]),
   dict(term=["vingt rapports,", "  vingt mises en page", "  la direction s'en plaint"], **N, who='mika', expr='angry', pose='hips', sfx="×20"),
   "une mise en page commune", ["classe d'entreprise", "marges, polices, en-têtes fixés", "documents = contenu seul", "version de la charte"],
   "Des réglages répétés dans chaque document divergent : une classe d'entreprise fixe la mise en page, et les documents ne gardent que leur contenu.")),
 ("c4", F("mglx4", "le tableau qui disparaît", "LaTeX 4",
   dict(term=["\\begin{table}", "  300 lignes d'incidents", "\\end{table}"], bulle=["Tout le", "tableau d'un", "coup."]),
   dict(term=["le tableau déborde", "  en bas de page", "  la moitié est invisible"], **N, who='kai', expr='shock', sfx="coupé"),
   "un tableau qui se coupe", ["longtable ou xltabular", "en-tête répété (\\endhead)", "booktabs pour la lisibilité", "contrôle du nombre de pages"],
   "Un tableau dans un flottant ne se coupe jamais : longtable le répartit sur plusieurs pages et répète l'en-tête.")),
 ("c5", F("mglx5", "minted et le shell-escape", "LaTeX 5",
   dict(term=["\\usepackage{minted}", "  latexmk -shell-escape", "  (pour la coloration)"], bulle=["C'est plus", "joli."]),
   dict(term=["donnée injectée :", "  \\immediate\\write18{curl …}", "  commande exécutée"], sfx="exec"),
   "rien d'exécuté", ["listings au lieu de minted", "-no-shell-escape", "conteneur sans réseau", "données échappées"],
   "L'option -shell-escape laisse le document exécuter des commandes : pour une génération automatique, on s'en passe et on isole la compilation.")),
 ("c6", F("mglx6", "la bibliographie vide", "LaTeX 6",
   dict(term=["\\autocite{anssi-guide}", "  compilation : pdflatex", "  une seule fois"], bulle=["C'est cité,", "c'est bon."]),
   dict(term=["[anssi-guide] en gras", "  bibliographie vide", "  document envoyé au client"], **N, who='mika', expr='shock', sfx="??"),
   "laisser latexmk enchaîner", ["latexmk lance biber", "lire le .blg", "aucun ?? dans le PDF", "contrôle automatique"],
   "Une bibliographie demande plusieurs passes et biber : latexmk les enchaîne, et un contrôle refuse tout PDF contenant des références non résolues.")),
 ("c7", F("mglx7", "le préambule copié vingt fois", "LaTeX 7",
   dict(term=["préambule de 80 lignes", "  copié dans 20 modèles", "  chacun un peu modifié"], bulle=["Je copie", "le dernier."]),
   dict(term=["nouvelle couleur de la charte :", "  20 fichiers à modifier", "  3 oubliés"], **N, who='kai', expr='shock', sfx="×20"),
   "une classe versionnée", ["crisis-rapport.cls", "options (confidentiel)", "macros métier", "CI qui compile les modèles"],
   "Un préambule copié partout se modifie partout : une classe versionnée le contient une fois, et la CI compile tous les modèles à chaque changement.")),
 ("c8", F("mglx8", "le titre qui lit /etc/passwd", "LaTeX 8",
   dict(term=["titre saisi par l'utilisateur :", "  \\input{/etc/passwd}", "  inséré sans échappement"], bulle=["C'est juste", "un titre."]),
   dict(term=["le PDF généré contient", "  le fichier du serveur", "  envoyé à tous"], sfx="fuite"),
   "échapper et isoler", ["échappement de chaque valeur", "openin_any=p", "--network none, lecture seule", "délai et arrêt sur erreur"],
   "Une donnée insérée sans échappement devient une commande LaTeX : on échappe chaque valeur, et la compilation isolée empêche de lire hors du répertoire.")),
 ("c9", F("mglx9", "deux pages au lieu de trente", "LaTeX 9",
   dict(term=["génération de nuit", "  -interaction=nonstopmode", "  sans -halt-on-error"], bulle=["Il ne", "s'arrête", "jamais."]),
   dict(term=["erreur ligne 12 ignorée", "  PDF de 2 pages publié", "  au lieu de 30"], **N, who='mika', expr='shock', sfx="2 / 30"),
   "s'arrêter et contrôler", ["-halt-on-error", "contrôle des pages et du texte", "lecture du .log", "alerte si échec"],
   "Une compilation qui continue malgré les erreurs publie des documents incomplets : on s'arrête à la première erreur, et on contrôle chaque PDF produit.")),
]
if __name__ == '__main__': apply(sys.argv[1], STRIPS)
