"""Planches manga de la page Mission Tech Lead Java MCO/MCS (17 chapitres). Usage : python3 manga32.py <page>"""
import sys, pathlib
sys.path.insert(0, str(pathlib.Path(__file__).parent))
from manga_gabarit import strip3, apply
F = lambda *a: strip3(*a)
N = dict(rack=False, nuit=False)
STRIPS = [
 ("c1", F("mgmi1", "tout faire soi-même", "Mission 1",
   dict(term=["semaine 1 : le Tech Lead", "  corrige lui-même 12 tickets", "  la nuit"], bulle=["Ça ira plus", "vite si je le", "fais."]),
   dict(term=["semaine 3 : CDS en attente", "  vérification matinale oubliée", "  mise en production ratée"], **N, who='mika', expr='shock', sfx="débordé"),
   "garantir, pas tout faire", ["piloter le CDS", "vérifier, relire, arbitrer", "coder les POC et l'urgent", "déléguer le reste"],
   "Le Tech Lead qui fait tout lui-même lâche ce que lui seul peut faire : il garantit le fonctionnement, pilote le CDS et arbitre, et code surtout les POC et les urgences.")),
 ("c2", F("mgmi2", "l'avis donné trop tôt", "Mission 2",
   dict(term=["jour 2 : « c'est simple,", "  on remplace ce module", "  en deux semaines »"], bulle=["J'ai vu pire."]),
   dict(term=["le module appelle 3 services", "  et 6 traitements de nuit", "  deux mois de travail"], **N, who='kai', expr='shock', sfx="× 4"),
   "cartographier d'abord", ["application lancée en conteneur", "inventaire et versions", "flux et ordonnancement", "avis ferme en fin de semaine 1"],
   "Un avis ferme sans connaître l'existant se paie ensuite : on cartographie une semaine, puis on s'engage.")),
 ("c3", F("mgmi3", "standalone.xml modifié à la main", "Mission 3",
   dict(term=["vi standalone.xml", "  max-pool-size : 20 → 50", "  (production, en direct)"], bulle=["Deux minutes,", "c'est réglé."]),
   dict(term=["redéploiement suivant :", "  configuration écrasée", "  le problème revient"], sfx="écrasé"),
   "tout passe par jboss-cli", ["script versionné", "idempotent", "joué en intégration d'abord", "même script en production"],
   "Une modification à la main de la configuration n'est ni tracée ni rejouée : un script jboss-cli versionné, joué en intégration puis en production.")),
 ("c4", F("mgmi4", "le serveur up, les pages figées", "Mission 4",
   dict(term=["9 h 05 : pages qui tournent", "  WildFly : démarré", "  « tout est vert »"], bulle=["Le serveur", "répond, c'est", "le réseau."]),
   dict(term=["pool : 30 actives sur 30", "  connexions non rendues", "  depuis la version d'hier"], sfx="30/30"),
   "des preuves, pas des intuitions", ["statistiques du pool", "trois thread dumps", "sessions Oracle", "cause, puis correctif"],
   "Un serveur démarré n'est pas un service qui répond : statistiques du pool, vidages des fils d'exécution et sessions Oracle montrent où il bloque.")),
 ("c5", F("mgmi5", "la différence invisible", "Mission 5",
   dict(term=["intégration : pool max 50", "  production : pool max 20", "  personne ne le sait"], bulle=["Testé en", "intégration,", "on livre."]),
   dict(term=["production, lundi 9 h :", "  pool saturé", "  alors que tout passait en test"], **N, who='mika', expr='shock', sfx="ISO ?"),
   "comparer avant de livrer", ["export des configurations", "valeurs propres documentées", "diff automatique", "écart bloque la livraison"],
   "Deux environnements différents sans le savoir rendent les tests trompeurs : on compare les configurations avant chaque mise en production.")),
 ("c6", F("mgmi6", "le job vert qui n'a rien fait", "Mission 6",
   dict(term=["job extraction : code 0", "  fichier d'entrée vide", "  aucun contrôle de volume"], bulle=["Il est vert", "dans le plan."]),
   dict(term=["8 h : éditions vides", "  envoyées aux partenaires", "  le job « avait réussi »"], sfx="vide"),
   "un code retour qui dit vrai", ["contrôle de volume", "code retour documenté", "verrou et reprise", "vérification matinale"],
   "Un traitement qui renvoie 0 sans rien produire trompe l'ordonnanceur : il contrôle ses volumes et échoue clairement.")),
 ("c7", F("mgmi7", "la variable vide", "Mission 7",
   dict(term=["rm -rf $DOSSIER/*", "  # DOSSIER non défini", "  # dans le cron de nuit"], bulle=["Il marche", "chez moi."]),
   dict(term=["rm -rf /*", "  serveur de recette", "  à reconstruire"], sfx="rm"),
   "des scripts de production", ["set -Eeuo pipefail", "vérifier le dossier", "mode essai à blanc", "ShellCheck en CI"],
   "Une variable vide dans une commande de suppression efface tout : mode strict, vérification du dossier, essai à blanc, et ShellCheck.")),
 ("c8", F("mgmi8", "la purge de cinq heures", "Mission 8",
   dict(term=["purge de nuit", "  DELETE ligne par ligne", "  sans index sur la clé"], bulle=["Elle a", "toujours", "marché."]),
   dict(term=["5 h 40 : toujours en cours", "  verrous sur incident", "  l'application bloquée"], sfx="5 h"),
   "par lots, avec le bon plan", ["BULK COLLECT et FORALL", "validation par lot", "index sur la clé étrangère", "plan vérifié en intégration"],
   "Une purge ligne à ligne sans index tient des verrous des heures : traitement par lots, index adapté et plan vérifié avant la production.")),
 ("c9", F("mgmi9", "la migration qui compile", "Mission 9",
   dict(term=["Java 11 → 17", "  mvn package : succès", "  « c'est migré »"], bulle=["Ça compile !"]),
   dict(term=["en recette :", "  InaccessibleObjectException", "  dans une bibliothèque"], **N, who='kai', expr='shock', sfx="17"),
   "inventorier, tester, déployer", ["jdeps et jdeprscan", "dépendances à jour", "tests complets", "intégration avant production"],
   "Une migration de Java qui compile n'est pas finie : inventaire des API internes, dépendances à jour et tests complets en intégration.")),
 ("c10", F("mgmi10", "le paramètre class", "Mission 10",
   dict(term=["Struts 1 en production", "  aucun filtre d'entrée", "  « personne ne l'attaque »"], bulle=["Ça tourne", "depuis 2010."]),
   dict(term=["?class.classLoader…=", "  (CVE-2014-0114)", "  alerte du test d'intrusion"], sfx="CVE"),
   "réduire le risque, préparer la sortie", ["filtre des paramètres class", "WAF en amont", "dépendances à jour", "migration écran par écran"],
   "Struts 1 ne sera plus corrigé : on filtre les attaques connues, on met un WAF, et on prépare la sortie écran par écran.")),
 ("c11", F("mgmi11", "le DOCTYPE du partenaire", "Mission 11",
   dict(term=["flux XML d'un partenaire", "  analyseur par défaut", "  entités externes activées"], bulle=["C'est un", "partenaire de", "confiance."]),
   dict(term=["<!ENTITY e SYSTEM", "  \"file:///etc/passwd\">", "  contenu renvoyé dans la réponse"], sfx="XXE"),
   "un analyseur durci", ["disallow-doctype-decl", "entités externes coupées", "validation XSD", "journal des rejets"],
   "Un analyseur XML par défaut peut lire des fichiers du serveur : on interdit les DOCTYPE et les entités externes, et on valide par XSD.")),
 ("c12", F("mgmi12", "la barrière contournée", "Mission 12",
   dict(term=["barrière SonarQube : rouge", "  « c'est urgent,", "  on livre quand même »"], bulle=["Juste cette", "fois."]),
   dict(term=["six mois plus tard :", "  la barrière est ignorée", "  à chaque livraison"], **N, who='mika', expr='angry', pose='hips', sfx="rouge"),
   "une règle, des dérogations tracées", ["barrière sur le nouveau code", "dérogation écrite et datée", "tests exigés rapidement", "suivi dans Jira"],
   "Une barrière qualité contournée une fois l'est ensuite toujours : les dérogations sont rares, écrites, datées et suivies.")),
 ("c13", F("mgmi13", "trois cents alertes", "Mission 13",
   dict(term=["scan de sécurité :", "  300 vulnérabilités", "  un seul fichier Excel"], bulle=["On verra", "après la", "version."]),
   dict(term=["audit trois mois après :", "  les critiques toujours là", "  une exploitée publiquement"], sfx="critique"),
   "trier, planifier, prouver", ["regrouper par composant", "CVSS, EPSS, exposition", "tickets et délais", "preuve de fermeture"],
   "Trois cents alertes non triées n'en font corriger aucune : on regroupe, on priorise selon l'exploitabilité, on planifie et on prouve chaque fermeture.")),
 ("c14", F("mgmi14", "le devis validé sans lecture", "Mission 14",
   dict(term=["devis du CDS : 40 jours", "  validé en 5 minutes", "  « ils connaissent »"], bulle=["Ils sont", "experts."]),
   dict(term=["à la livraison :", "  ni tests, ni documentation", "  « hors du devis »"], **N, who='kai', expr='shock', sfx="hors devis"),
   "lire le devis comme un contrat", ["périmètre et hypothèses", "chiffrage comparé", "oublis : tests, doc, sécurité", "critères d'acceptation"],
   "Un devis non analysé laisse tout ce qui n'y est pas écrit hors du contrat : périmètre, hypothèses, oublis et critères se vérifient avant de valider.")),
 ("c15", F("mgmi15", "les droits donnés dans le couloir", "Mission 15",
   dict(term=["« donne-moi l'accès admin", "  en production,", "  c'est pour débloquer »"], bulle=["Pas le temps", "d'un ticket."]),
   dict(term=["revue des droits, 6 mois après :", "  12 administrateurs", "  dont 5 partis"], **N, who='mika', expr='shock', sfx="12"),
   "un processus tracé", ["demande par ticket", "validation du représentant", "moindre privilège, durée limitée", "revue trimestrielle"],
   "Des droits donnés sans trace s'accumulent : demande, validation, attribution minimale et limitée, puis revue régulière.")),
 ("c16", F("mgmi16", "le script qui attend pour toujours", "Mission 16",
   dict(term=["controle_matin.py", "  requests.get(url)", "  # sans délai"], bulle=["Il tourne", "tous les", "matins."]),
   dict(term=["7 h 45 : API injoignable", "  script bloqué", "  aucun rapport à 8 h"], sfx="∞"),
   "des délais partout", ["timeout sur chaque appel", "délai global par l'ordonnanceur", "journal de l'étape en cours", "tests sans réseau"],
   "Un appel réseau sans délai bloque tout le contrôle : chaque appel a un timeout, et l'ordonnanceur borne la durée du script.")),
 ("c17", F("mgmi17", "réciter la fiche de poste", "Mission 17",
   dict(term=["entretien :", "  « je maîtrise WildFly,", "  Oracle, Jenkins… »"], bulle=["J'ai tout", "sur mon CV."]),
   dict(term=["« racontez un incident", "  de production récent »", "  … réponse vague"], **N, who='kai', expr='shock', sfx="…"),
   "des preuves vécues", ["histoires STAR chiffrées", "TP réalisés comme preuves", "plan des 90 jours", "questions sur leur contexte"],
   "Une liste de technologies ne convainc pas : des situations réelles chiffrées, des preuves pratiques et un plan pour leur contexte, si.")),
]
if __name__ == '__main__': apply(sys.argv[1], STRIPS)
