"""Planches manga du cours Talend (10 chapitres). Usage : python3 manga26.py <page>"""
import sys, pathlib
sys.path.insert(0, str(pathlib.Path(__file__).parent))
from manga_gabarit import strip3, apply
F = lambda *a: strip3(*a)
N = dict(rack=False, nuit=False)
STRIPS = [
 ("c1", F("mgt1", "ça marche dans le Studio", "Talend 1",
   dict(term=["Run dans le Studio : OK", "  chemin C:\\\\temp\\\\entree", "  contexte par défaut"], bulle=["Testé, je", "livre."]),
   dict(term=["JobServer, cette nuit :", "  fichier introuvable", "  Java 17 au lieu de 11"], sfx="KO"),
   "tester comme en production", ["build de l'archive", "exécution en conteneur Java 17", "contextes, pas de chemins en dur", "code de sortie vérifié"],
   "Un job qui marche dans le Studio peut échouer sur le JobServer : on construit l'archive et on la teste dans un conteneur identique à la production, avec ses contextes.")),
 ("c2", F("mgt2", "l'erreur de jointure silencieuse", "Talend 2",
   dict(term=["tMap : jointure interne", "  sur code_zone", "  rejets : non activés"], bulle=["Les lignes", "passent, c'est", "bon."]),
   dict(term=["12 % des incidents", "  absents du rapport", "  personne ne sait pourquoi"], **N, who='mika', expr='shock', sfx="12 %"),
   "rien ne disparaît en silence", ["sortie des rejets de jointure", "raison du rejet enregistrée", "compteur par sortie", "compte rendu du job"],
   "Une jointure interne écarte sans bruit les lignes sans correspondance : on active la sortie des rejets, on la compte, et le compte rendu du job l'affiche.")),
 ("c3", F("mgt3", "le lookup de quarante millions", "Talend 3",
   dict(term=["tMap : lookup « ventes »", "  40 millions de lignes", "  chargement en mémoire"], bulle=["Le JobServer", "a de la", "mémoire."]),
   dict(term=["java.lang.OutOfMemoryError", "  Java heap space", "  la nuit de flux s'arrête"], sfx="OOM"),
   "adapter le lookup", ["stockage sur disque", "ou jointure en base (ELT)", "filtrer le lookup", "mesurer la mémoire"],
   "Un lookup énorme chargé en mémoire fait tomber le job : on le filtre, on le stocke sur disque, ou on fait la jointure dans la base.")),
 ("c4", F("mgt4", "le contexte de production", "Talend 4",
   dict(term=["contexte par défaut :", "  db_hote = pg-prod", "  (pour « tester vite »)"], bulle=["Juste un", "petit test."]),
   dict(term=["test lancé depuis le Studio", "  3 000 lignes de test", "  écrites en production"], sfx="prod"),
   "la production hors du Studio", ["contexte par défaut : dev", "valeurs de production au TAC", "mots de passe dans un coffre", "compte prod inaccessible au poste"],
   "Une valeur de production dans le Studio finit par être utilisée par erreur : le contexte par défaut est le développement, et la production n'existe que sur le TAC ou au chargement.")),
 ("c5", F("mgt5", "l'erreur avalée", "Talend 5",
   dict(term=["sous-job en erreur", "  OnSubjobError : rien", "  code de sortie : 0"], bulle=["Il est vert", "dans le TAC."]),
   dict(term=["rapport du matin vide", "  plan de nuit « succès »", "  cause découverte à midi"], **N, who='kai', expr='shock', sfx="0"),
   "échouer franchement", ["tLogCatcher partout", "table de journal commune", "tDie avec code documenté", "le parent vérifie les enfants"],
   "Un job qui se termine à 0 malgré une erreur trompe tout le monde : tLogCatcher capte, le journal commun enregistre, et tDie termine avec un code que la supervision voit.")),
 ("c6", F("mgt6", "un commit par ligne", "Talend 6",
   dict(term=["tDBOutput : lot = 1", "  validation = 1", "  5 millions de lignes"], bulle=["C'est plus", "sûr ligne par", "ligne."]),
   dict(term=["durée : 7 heures", "  base saturée", "  le flux suivant en retard"], sfx="7 h"),
   "écrire en masse", ["lots de 1 000", "validation tous les 10 000", "bulk : COPY", "ELT si tout est en base"],
   "Valider chaque ligne transforme un chargement de minutes en heures : lots, validation espacée, chargement en masse ou ELT.")),
 ("c7", F("mgt7", "la clé dans tS3Get", "Talend 7",
   dict(term=["tS3Get :", "  access key = AKIA…", "  secret key = …"], bulle=["Sinon il ne", "se connecte", "pas."]),
   dict(term=["job exporté vers un prestataire", "  clé AWS dans l'archive", "  compartiments lisibles"], sfx="clé"),
   "un rôle, pas une clé", ["rôle IAM du JobServer", "droits minimaux par zone", "secret de base dans un coffre", "recherche de clés en CI"],
   "Une clé d'accès dans un composant voyage avec chaque export : le JobServer utilise un rôle IAM minimal et aucun identifiant n'est saisi dans les jobs.")),
 ("c8", F("mgt8", "le changement non testé", "Talend 8",
   dict(term=["tMap modifié :", "  arrondi des montants", "  aucun cas de test"], bulle=["Une petite", "retouche."]),
   dict(term=["le lendemain :", "  totaux faux de 0,5 %", "  sur 90 jours de rapports"], **N, who='mika', expr='angry', pose='hips', sfx="0,5 %"),
   "tester avant de livrer", ["cas de test Talend", "fichier de référence comparé", "exécution en CI", "MR relue"],
   "Une retouche de tMap peut fausser des mois de rapports : chaque flux critique a un cas de test avec sortie de référence, exécuté en CI avant la livraison.")),
 ("c9", F("mgt9", "la nuit sans dépendances", "Talend 9",
   dict(term=["TAC : trois tâches à 01 h 00", "  aucune dépendance", "  « elles sont rapides »"], bulle=["Ça passe", "toujours."]),
   dict(term=["référentiels en retard", "  incidents chargés avant", "  zones manquantes"], sfx="ordre"),
   "un plan avec dépendances", ["plan d'exécution ordonné", "délai de fin attendu", "relance limitée", "alerte à l'astreinte"],
   "Des tâches lancées à la même heure sans dépendances finissent par s'inverser : un plan d'exécution ordonne les flux, avec un délai de fin et une alerte.")),
 ("c10", F("mgt10", "réciter les composants", "Talend 10",
   dict(term=["entretien Data InfraOps :", "  « tMap, tJava, tRunJob,", "  tFileInput… »"], bulle=["Je connais", "tous les", "composants."]),
   dict(term=["« racontez un incident", "  Talend en production »", "  … silence"], **N, who='kai', expr='shock', sfx="…"),
   "raconter un flux redressé", ["le problème chiffré", "le diagnostic par mesures", "les corrections", "le résultat, la leçon"],
   "Un recruteur cherche une expérience, pas un catalogue : un flux réel, le diagnostic, les corrections et le résultat chiffré.")),
]
if __name__ == '__main__': apply(sys.argv[1], STRIPS)
