"""Planches manga du cours Monitoring (13 chapitres). Usage : python3 manga23.py <page>"""
import sys, pathlib
sys.path.insert(0, str(pathlib.Path(__file__).parent))
from manga_gabarit import strip3, apply
F = lambda *a: strip3(*a)
N = dict(rack=False, nuit=False)
STRIPS = [
 ("c1", F("mgo1", "tout est vert, les clients crient", "Monitoring 1",
   dict(term=["Grafana : CPU 30 %", "  mémoire 50 %, disque 40 %", "  tout est vert"], bulle=["Rien à signaler", "aujourd'hui."]),
   dict(term=["support : 140 appels", "  « l'application renvoie", "  une erreur » depuis 1 h"], **N, who='mika', expr='shock', sfx="140"),
   "mesurer ce que vit l'utilisateur", ["RED à chaque point d'entrée", "sonde externe (blackbox)", "USE pour le diagnostic", "SLO sur le parcours"],
   "Des ressources saines ne disent rien d'un service qui renvoie des erreurs : on mesure débit, erreurs et latence à l'entrée, et une sonde externe joue l'utilisateur.")),
 ("c2", F("mgo2", "la moyenne des p95", "Monitoring 2",
   dict(term=["résumé Micrometer par Pod", "p95 : 120, 140, 2 800 ms", "affiché : moyenne des trois"], bulle=["p95 du service :", "1 020 ms."]),
   dict(term=["vrai p95 du service : 2,4 s", "SLO violé depuis 3 jours", "personne ne l'a vu"], **N, who='kai', expr='shock', sfx="faux"),
   "des histogrammes agrégeables", ["histogramme, pas résumé", "tranches alignées sur le SLO", "sum by (le) puis quantile", "jamais de moyenne de p95"],
   "Des quantiles calculés dans chaque Pod ne s'additionnent pas : on expose un histogramme, on additionne les tranches, puis on calcule le quantile du service.")),
 ("c3", F("mgo3", "sum puis rate", "Monitoring 3",
   dict(term=["rate(sum(", "  http_requests_total)[5m])", "# plus court à écrire"], bulle=["Même résultat,", "non ?"]),
   dict(term=["un Pod redémarre", "  le compteur total recule", "  pic à 40 000 req/s"], **N, who='mika', expr='angry', pose='hips', sfx="pic"),
   "rate d'abord, sum ensuite", ["sum(rate(x[5m]))", "rate détecte les remises à zéro", "rate sur un compteur seulement", "tests promtool en CI"],
   "rate sait gérer la remise à zéro d'un compteur seulement s'il voit chaque série : on calcule rate série par série, puis on additionne.")),
 ("c4", F("mgo4", "deux cents pages pour une panne", "Monitoring 4",
   dict(term=["nœud 3 indisponible", "  Alertmanager sans groupement", "  ni inhibition"], bulle=["On sera", "prévenus, au", "moins."]),
   dict(term=["02 h 14 : 184 notifications", "  le téléphone sonne sans fin", "  la vraie cause noyée"], sfx="184"),
   "une panne, une page", ["group_by service et nœud", "inhibition des alertes filles", "causes en ticket", "runbook dans chaque alerte"],
   "Sans regroupement ni inhibition, une panne de nœud réveille pour chaque Pod : Alertmanager regroupe, fait taire les conséquences et n'envoie qu'une page, avec son runbook.")),
 ("c5", F("mgo5", "quatre-vingts panneaux", "Monitoring 5",
   dict(term=["tableau de bord « Global »", "  80 panneaux", "  aucune unité, aucun seuil"], bulle=["Tout y est,", "c'est complet."]),
   dict(term=["incident : 20 minutes", "  à chercher le bon graphique", "  pendant que ça brûle"], **N, who='kai', expr='shock', sfx="20 min"),
   "une question par tableau de bord", ["état et SLO en haut", "RED, puis USE", "douze panneaux au plus", "liens vers journaux et traces"],
   "Un tableau de bord qui montre tout ne répond à rien : un écran par question, l'état en haut, RED puis USE, et des liens vers les journaux et les traces.")),
 ("c6", F("mgo6", "deux ans sur un disque", "Monitoring 6",
   dict(term=["prometheus --storage.tsdb", "  .retention.time=2y", "  disque local de 200 Go"], bulle=["On garde", "l'historique", "ici."]),
   dict(term=["disque plein un dimanche", "  Prometheus s'arrête", "  plus aucune alerte"], sfx="plein"),
   "court en local, long ailleurs", ["15 jours dans Prometheus", "remote_write vers Mimir", "stockage objet, sous-échantillonné", "paire pour la disponibilité"],
   "Prometheus n'est pas fait pour des années sur un disque local : il garde quelques semaines, et remote_write envoie l'historique vers un stockage durable sur objet.")),
 ("c7", F("mgo7", "le service invisible", "Monitoring 7",
   dict(term=["service « export » déployé", "  il y a deux semaines", "  ServiceMonitor : aucun"], bulle=["Il marche,", "pas besoin de", "le regarder."]),
   dict(term=["export en CrashLoop", "  depuis 5 jours", "  aucune métrique, aucune alerte"], sfx="5 j"),
   "collecter par défaut", ["ServiceMonitor dans le modèle", "règles livrées avec l'application", "alerte : déployé mais non collecté", "kube-state-metrics pour l'état"],
   "Un service qui n'est pas collecté n'existe pas pour la supervision : le ServiceMonitor fait partie du modèle de service, et une alerte signale tout déploiement sans cible collectée.")),
 ("c8", F("mgo8", "des journaux en vrac", "Monitoring 8",
   dict(term=["System.out.println(", "  \"erreur incident \" + id);", "# texte libre, sans niveau"], bulle=["Kibana", "cherchera."]),
   dict(term=["grok : 14 motifs fragiles", "  30 % des lignes non analysées", "  pas de filtre par niveau"], **N, who='mika', expr='angry', pose='hips', sfx="30 %"),
   "structurer à la source", ["journaux JSON dès l'application", "niveau, service, traceId", "décodage ndjson à la collecte", "grok pour l'hérité seulement"],
   "Des journaux en texte libre imposent des expressions grok fragiles : l'application écrit du JSON avec niveau, service et traceId, et la collecte n'a plus qu'à le décoder.")),
 ("c9", F("mgo9", "dix mille champs", "Monitoring 9",
   dict(term=["journal : { \"payload\": {…} }", "  JSON libre des clients", "  mapping dynamique"], bulle=["Elasticsearch", "s'adapte tout", "seul."]),
   dict(term=["mapping : 10 000 champs", "  nœud maître saturé", "  cluster en rouge"], sfx="rouge"),
   "un mapping explicite", ["champs utiles déclarés", "dynamic: false pour le reste", "total_fields.limit", "données libres non indexées"],
   "Avec un mapping dynamique, chaque clé nouvelle devient un champ, jusqu'à saturer le cluster : on déclare les champs utiles et on laisse le reste non indexé.")),
 ("c10", F("mgo10", "un flux par requête", "Monitoring 10",
   dict(term=["labels Loki :", "  service, niveau,", "  request_id"], bulle=["Pour filtrer", "plus vite."]),
   dict(term=["3 millions de flux", "  requêtes de 40 secondes", "  facture de stockage × 5"], sfx="×5"),
   "peu de labels, bornés", ["service, niveau, espace de noms", "request_id dans le texte", "filtrer avec | json", "moins de 100 flux par service"],
   "Dans Loki, chaque combinaison de labels crée un flux : un identifiant de requête en label crée des millions de flux ; il reste dans le texte et se filtre à la requête.")),
 ("c11", F("mgo11", "tout garder, tout payer", "Monitoring 11",
   dict(term=["échantillonnage : 100 %", "  toutes les traces gardées", "  30 jours"], bulle=["On ne sait", "jamais laquelle", "servira."]),
   dict(term=["stockage des traces × 3", "  99 % : requêtes normales", "  jamais consultées"], **N, who='kai', expr='shock', sfx="× 3"),
   "garder les traces utiles", ["échantillonnage en queue", "toutes les erreurs", "toutes les lenteurs", "5 % du reste"],
   "Garder chaque trace coûte cher pour rien : l'échantillonnage en queue conserve toutes les erreurs et les lenteurs, et un petit échantillon du trafic normal.")),
 ("c12", F("mgo12", "six heures de retard, zéro alerte", "Monitoring 12",
   dict(term=["consommateur « notifications »", "  up = 1", "  aucune alerte définie"], bulle=["Il est en", "vie, tout va", "bien."]),
   dict(term=["bloqué sur un message", "  retard : 6 heures", "  alertes de crise jamais parties"], sfx="6 h"),
   "surveiller le retard", ["kafka_consumergroup_lag", "seuil lié au besoin métier", "alerte sur la croissance", "sonde de bout en bout"],
   "Un consommateur peut être en vie et bloqué : on surveille son retard, avec un seuil qui dit ce que le métier tolère.")),
 ("c13", F("mgo13", "le surveillant endormi", "Monitoring 13",
   dict(term=["Prometheus : un seul", "  sur un seul nœud", "  personne ne le surveille"], bulle=["S'il tombe,", "on le saura."]),
   dict(term=["01 h : Prometheus tombe", "  03 h : panne de production", "  aucune alerte envoyée"], sfx="silence"),
   "surveiller la supervision", ["Watchdog toujours active", "battement de cœur externe", "paire de Prometheus", "méta-supervision des échecs"],
   "Une supervision tombée ne prévient de rien : une alerte Watchdog permanente, relayée à un service externe, déclenche un appel quand le signal s'arrête.")),
]
if __name__ == '__main__': apply(sys.argv[1], STRIPS)
