"""Planches manga du cours Java PKI et signature électronique (13 chapitres). Usage : python3 manga17.py <page>"""
import sys, pathlib
sys.path.insert(0, str(pathlib.Path(__file__).parent))
from manga_gabarit import strip3, apply
F = lambda *a: strip3(*a)
N = dict(rack=False, nuit=False)
STRIPS = [
 ("c1", F("mgp1", "MD5 pour les mots de passe", "PKI 1",
   dict(term=["hash = md5(motDePasse)", "# sans sel", "# « c'est haché, donc sûr »"], bulle=["Haché, donc", "illisible."]),
   dict(term=["fuite de la table users", "60 % retrouvés en 1 heure", "  (tables arc-en-ciel)"], sfx="60 %"),
   "un hachage fait pour ça", ["Argon2id ou bcrypt", "sel unique, coût réglable", "MD5 et SHA-1 : jamais", "SHA-256 : intégrité, pas mots"],
   "Un hachage rapide sans sel se casse par tables précalculées : les mots de passe se protègent avec Argon2id ou bcrypt, lents et salés par conception.")),
 ("c2", F("mgp2", "la racine en ligne", "PKI 2",
   dict(term=["AC racine sur un serveur", "  connecté au réseau", "  signe tous les certificats"], bulle=["Plus simple", "à opérer."]),
   dict(term=["serveur compromis", "clé racine copiée", "toute la PKI à reconstruire"], sfx="racine"),
   "racine hors ligne", ["racine hors ligne, dans un HSM", "intermédiaires pour signer", "cérémonie de clés tracée", "révocation d'intermédiaire"],
   "Une racine compromise invalide toute la hiérarchie : elle reste hors ligne dans un HSM et ne signe que des autorités intermédiaires, qui signent les certificats.")),
 ("c3", F("mgp3", "la chaîne incomplète", "PKI 3",
   dict(term=["ssl_certificate", "  server.crt;  # seul", "le navigateur marche"], bulle=["Chrome l'accepte,", "c'est bon."]),
   dict(term=["client Java, curl, mobile :", "  unable to get local", "  issuer certificate"], sfx="PKIX"),
   "servir la chaîne", ["fullchain : feuille + intermédiaires", "vérifier : openssl s_client", "  -showcerts", "jamais la racine dans la chaîne"],
   "Un navigateur complète parfois une chaîne manquante, les autres clients non : le serveur envoie la feuille et ses intermédiaires, vérifiés avec openssl s_client.")),
 ("c4", F("mgp4", "changeit, toujours", "PKI 4",
   dict(term=["keystore.p12 dans Git", "server.ssl.key-store-password", "  = changeit"], bulle=["C'est le", "mot de passe", "par défaut."]),
   dict(term=["dépôt cloné par un tiers", "clé privée du serveur", "  extraite en 5 secondes"], sfx="clé"),
   "protéger le magasin", ["keystore hors du dépôt", "mot de passe dans Vault", "PKCS12, droits restreints", "rotation du certificat"],
   "Un keystore versionné avec le mot de passe par défaut équivaut à publier la clé privée : le magasin reste hors du dépôt et son mot de passe vient d'un coffre.")),
 ("c5", F("mgp5", "tout faire confiance", "PKI 5",
   dict(term=["new X509TrustManager() {", "  checkServerTrusted(…) {}", "}  // accepte tout"], bulle=["L'erreur PKIX", "a disparu."]),
   dict(term=["Wi-Fi d'hôtel, proxy piégé", "faux certificat accepté", "identifiants interceptés"], sfx="MITM"),
   "un vrai truststore", ["ajouter l'AC au truststore", "vérifier le nom d'hôte", "mTLS pour les services", "jamais de trustAll"],
   "Un TrustManager qui accepte tout supprime l'authentification du serveur : on ajoute la bonne autorité au truststore et on vérifie le nom d'hôte.")),
 ("c6", F("mgp6", "la signature qui expire", "PKI 6",
   dict(term=["contrat signé PAdES-B", "  sans horodatage", "certificat valable 2 ans"], bulle=["Signé, c'est", "définitif."]),
   dict(term=["dans 3 ans : vérification", "certificat expiré, révoqué ?", "signature invérifiable"], **N, who='mika', expr='shock', sfx="?"),
   "signer pour durer", ["horodatage (TSA) : niveau T", "LT : preuves de validité", "LTA : archivage renouvelé", "choisir B-LTA pour l'archive"],
   "Sans horodatage ni preuves de validation, une signature devient invérifiable à l'expiration du certificat : les niveaux T, LT et LTA la rendent vérifiable dans la durée.")),
 ("c7", F("mgp7", "AES tout court", "PKI 7",
   dict(term=["Cipher.getInstance(\"AES\")", "// mode par défaut ?", "// ECB, sans IV"], bulle=["AES, c'est", "du solide."]),
   dict(term=["blocs identiques →", "  chiffrés identiques", "motifs visibles, pas d'intégrité"], sfx="ECB"),
   "préciser mode et IV", ["AES/GCM/NoPadding", "IV aléatoire de 12 octets", "tag d'authentification vérifié", "jamais réutiliser un IV"],
   "Sans mode explicite, Java choisit ECB, qui laisse voir les motifs et n'authentifie rien : AES-GCM avec un IV aléatoire unique chiffre et protège l'intégrité.")),
 ("c8", F("mgp8", "la clé dans le JAR", "PKI 8",
   dict(term=["src/main/resources/", "  signature.p12", "  mot de passe dans le code"], bulle=["Tout est au", "même endroit."]),
   dict(term=["le JAR est partagé", "clé de signature extraite", "documents signés par un tiers"], sfx="clé"),
   "la clé ne sort jamais", ["HSM via PKCS#11", "ou Vault Transit", "l'application demande une", "  signature, jamais la clé"],
   "Une clé de signature embarquée est copiée avec le binaire : elle vit dans un HSM ou un service de signature, et l'application demande seulement la signature d'un condensat.")),
 ("c9", F("mgp9", "le certificat révoqué accepté", "PKI 9",
   dict(term=["signature.verify(cle)  → OK", "chaîne valide  → OK", "// révocation : pas vérifiée"], bulle=["Signature et", "chaîne : OK."]),
   dict(term=["certificat révoqué hier", "  (clé volée)", "document accepté aujourd'hui"], **N, who='mika', expr='angry', pose='hips', sfx="révoqué"),
   "valider complètement", ["chaîne jusqu'à une ancre", "dates et usages (keyUsage)", "révocation : OCSP ou CRL", "échec si statut inconnu"],
   "Valider une signature, c'est aussi valider le certificat : chaîne, dates, usages et révocation par OCSP ou CRL, avec un échec si le statut est inconnu.")),
 ("c10", F("mgp10", "le mauvais niveau de signature", "PKI 10",
   dict(term=["acte à valeur juridique", "  signé en signature simple", "  (case à cocher)"], bulle=["Signé,", "c'est signé."]),
   dict(term=["contestation au tribunal", "niveau insuffisant", "  pour cet acte"], **N, who='kai', expr='shock', sfx="refusé"),
   "le niveau selon l'enjeu", ["simple : faible enjeu", "avancée : identité liée", "qualifiée : équivaut au manuscrit", "RGS pour l'administration"],
   "eIDAS définit trois niveaux de signature qui n'ont pas la même force : on choisit selon l'enjeu juridique de l'acte, et le RGS fixe les exigences pour l'administration.")),
 ("c11", F("mgp11", "un seul HSM", "PKI 11",
   dict(term=["1 HSM pour toutes les", "  signatures de l'application", "sauvegarde : « plus tard »"], bulle=["Il est certifié,", "il ne tombe", "pas."]),
   dict(term=["HSM en panne un lundi", "aucune signature possible", "clés non sauvegardées"], sfx="panne"),
   "prévoir la continuité", ["HSM en cluster, deux sites", "sauvegarde chiffrée des clés", "procédure de cérémonie écrite", "PRA de signature testé"],
   "Un HSM unique est un point de panne pour toute la signature : cluster sur deux sites, sauvegarde des clés sous contrôle de plusieurs personnes, et un plan de reprise testé.")),
 ("c12", F("mgp12", "PKIX path building failed", "PKI 12",
   dict(term=["javax.net.ssl.SSLHandshake", "  Exception: PKIX path", "  building failed"], bulle=["Je désactive", "la vérification."]),
   dict(term=["vérification désactivée", "  « temporairement »", "toujours là deux ans après"], **N, who='mika', expr='angry', pose='hips', sfx="2 ans"),
   "diagnostiquer, pas contourner", ["openssl s_client -showcerts", "quelle AC manque ?", "keytool -list sur le truststore", "-Djavax.net.debug=ssl:handshake"],
   "PKIX path building failed signifie qu'une autorité manque dans le truststore : on identifie la chaîne avec openssl et keytool, et on ajoute la bonne autorité au lieu de couper la vérification.")),
 ("c13", F("mgp13", "dans dix ans, ça tient ?", "PKI 13",
   dict(term=["entretien : « comment vérifier", "  une signature PAdES", "  dans dix ans ? »"], bulle=["Avec la clé", "publique ?"]),
   dict(term=["certificat expiré depuis 8 ans", "AC disparue, algorithme faible", "réponse incomplète"], **N, who='kai', expr='shock', sfx="…"),
   "la réponse attendue", ["horodatage au moment de signer", "preuves de validation (LT)", "horodatage d'archive (LTA)", "renouvelé avant affaiblissement"],
   "La vérification à long terme repose sur l'horodatage, les preuves de validation embarquées et des horodatages d'archive renouvelés : c'est la réponse attendue en entretien PKI.")),
]
if __name__ == '__main__': apply(sys.argv[1], STRIPS)
