"""Planches manga du cours Perl (10 chapitres). Usage : python3 manga30.py <page>"""
import sys, pathlib
sys.path.insert(0, str(pathlib.Path(__file__).parent))
from manga_gabarit import strip3, apply
F = lambda *a: strip3(*a)
N = dict(rack=False, nuit=False)
STRIPS = [
 ("c1", F("mgpl1", "le script sans strict", "Perl 1",
   dict(term=["#!/usr/bin/perl", "$total = $totla + $n;", "# ni strict, ni warnings"], bulle=["Il tourne", "depuis 2009."]),
   dict(term=["$totla n'existe pas", "  total toujours faux", "  depuis des années"], **N, who='mika', expr='shock', sfx="faux"),
   "strict et warnings d'abord", ["use v5.36 en tête", "variables déclarées avec my", "avertissements corrigés un par un", "tests avant de toucher"],
   "Sans use strict, une faute de frappe crée une nouvelle variable en silence : strict et warnings attrapent l'erreur dès la première exécution.")),
 ("c2", F("mgpl2", "le tableau devenu nombre", "Perl 2",
   dict(term=["my $zones = @zones;", "print \"zones : $zones\";"], bulle=["J'affiche", "les zones."]),
   dict(term=["sortie : zones : 3", "  le rapport attendait", "  N1, N2, S3"], **N, who='kai', expr='shock', sfx="3"),
   "maîtriser le contexte", ["scalaire : la taille", "liste : les éléments", "join(', ', @zones)", "(my $x) = @liste pour le premier"],
   "Un tableau en contexte scalaire vaut sa taille : pour les éléments, on reste en contexte liste ou on les joint explicitement.")),
 ("c3", F("mgpl3", "le masquage trop gourmand", "Perl 3",
   dict(term=["s/password=.*/password=****/", "# masquer les mots de passe"], bulle=["Une ligne,", "c'est réglé."]),
   dict(term=["password=**** ", "  la fin de chaque ligne", "  a disparu des journaux"], sfx=".*"),
   "limiter la correspondance", ["password=\\S+", "ou [^&\\s]+ jusqu'au séparateur", "qr//x commenté", "tests sur de vraies lignes"],
   "Un .* va jusqu'au bout de la ligne : on limite la correspondance à la valeur visée, et on teste l'expression sur des lignes réelles.")),
 ("c4", F("mgpl4", "le nom de fichier qui exécute", "Perl 4",
   dict(term=["system(\"gzip $fichier\");", "# noms lus dans un fichier", "# « a.log; rm -rf ~ »"], bulle=["C'est juste", "un gzip."]),
   dict(term=["le shell interprète le ;", "  rm -rf ~ exécuté", "  dossier personnel vidé"], sfx="rm"),
   "sans shell, avec vérification", ["system('gzip', '--', $f)", "noms validés, liste blanche", "mode taint (-T)", "code de retour vérifié"],
   "Une commande construite par concaténation passe par le shell et s'injecte : la forme liste de system passe les arguments tels quels, sans interprétation.")),
 ("c5", F("mgpl5", "la clé créée en lisant", "Perl 5",
   dict(term=["if ($config{zone}{N9}{actif})", "# juste un test de lecture"], bulle=["Je lis,", "je ne modifie", "rien."]),
   dict(term=["exporte : zone N9 créée", "  vide, dans la configuration", "  (autovivification)"], **N, who='mika', expr='angry', pose='hips', sfx="N9"),
   "tester avant de descendre", ["exists à chaque niveau", "no autovivification si besoin", "Data::Dumper pour vérifier", "tests sur la structure"],
   "Lire en profondeur une structure crée les niveaux intermédiaires manquants : on teste exists à chaque niveau avant de descendre.")),
 ("c6", F("mgpl6", "quatre copies de la même fonction", "Perl 6",
   dict(term=["sub normaliser { … }", "  copiée dans 4 scripts", "  4 versions différentes"], bulle=["Copier-coller,", "c'est rapide."]),
   dict(term=["correctif appliqué à 1 script", "  3 autres toujours faux", "  rapports incohérents"], **N, who='kai', expr='shock', sfx="×4"),
   "un module, testé", ["lib/Crise/Incident.pm", "Exporter, interface claire", "cpanfile et image Docker", "tests du module"],
   "Une fonction copiée dans plusieurs scripts diverge à chaque correction : elle va dans un module testé, importé par tous.")),
 ("c7", F("mgpl7", "le hachage que tout le monde modifie", "Perl 7",
   dict(term=["$equipe->{membres} = [];", "  dans 6 scripts différents", "  « c'est un objet »"], bulle=["C'est plus", "direct."]),
   dict(term=["structure modifiée par un script", "  les 5 autres cassent", "  en production"], sfx="cassé"),
   "des objets avec des règles", ["Moo, attributs typés", "accesseurs, lecture seule", "rôles partagés", "plus d'accès directs"],
   "Un objet dont chacun modifie les champs n'a aucune règle : Moo déclare des attributs typés et des accesseurs, et les accès directs disparaissent.")),
 ("c8", F("mgpl8", "le script qui réussit toujours", "Perl 8",
   dict(term=["eval { traiter() };", "# erreur ignorée", "exit 0;"], bulle=["Comme ça, il", "ne plante", "jamais."]),
   dict(term=["base injoignable depuis 3 nuits", "  code de sortie : 0", "  personne n'est prévenu"], **N, who='mika', expr='shock', sfx="0"),
   "échouer clairement", ["erreur journalisée avec contexte", "code de sortie non nul", "test du cas d'échec", "Perl::Critic en CI"],
   "Un script qui avale ses erreurs réussit en apparence pendant que les données manquent : il journalise, sort avec un code d'échec, et un test le vérifie.")),
 ("c9", F("mgpl9", "l'apostrophe dans la zone", "Perl 9",
   dict(term=["\"… WHERE zone = '$zone'\"", "# zone lue dans le fichier"], bulle=["Les zones", "sont sûres."]),
   dict(term=["zone : « L'Isle »", "  erreur de syntaxe SQL", "  (et injection possible)"], sfx="SQL"),
   "des paramètres, toujours", ["prepare('… zone = ?')", "execute($zone)", "RaiseError", "transaction et rollback"],
   "Une valeur insérée dans le texte SQL casse la requête ou l'injecte : DBI passe les valeurs par des paramètres.")),
 ("c10", F("mgpl10", "tout réécrire en Python", "Perl 10",
   dict(term=["script legacy : 3 000 lignes", "  « on le réécrit en Python »", "  aucun test"], who='sensei', expr='neutral', pose='stand', bulle=["Ce sera", "plus propre."]),
   dict(term=["trois mois plus tard :", "  12 cas particuliers oubliés", "  retour à l'ancien script"], **N, who='kai', expr='shock', sfx="12"),
   "figer, fiabiliser, puis décider", ["tests de caractérisation", "strict, modules, CI", "conteneur", "réécrire sur critères"],
   "Réécrire un script sans en connaître les cas particuliers en oublie toujours : on fige son comportement par des tests, on le fiabilise, et on ne réécrit que sur critères.")),
]
if __name__ == '__main__': apply(sys.argv[1], STRIPS)
