import re, pathlib, html as H

out = pathlib.Path('/mnt/user-data/outputs')
LEVEL = {}
for lvl, fn, chs in [(0,"devops-00-fondations.html",range(1,7)),(1,"devops-01-virtualisation-et-conteneurs.html",range(7,11)),(2,"devops-02-integration-et-livraison-continues.html",range(11,16)),(3,"devops-03-infrastructure-as-code.html",range(16,20)),
                     (4,"devops-04-cloud.html",range(20,25)),(5,"devops-05-kubernetes.html",range(25,32)),(6,"devops-06-observabilite.html",range(32,37)),(7,"devops-07-securite-devsecops.html",range(37,43)),
                     (8,"devops-08-sre-et-architecture.html",range(43,49)),(9,"devops-09-expert-et-leadership.html",range(49,55))]:
    for ch in chs: LEVEL[ch] = fn

def tp_info(ch):
    """titre et étapes de l'énoncé, extraits de la page du niveau"""
    s = (out/LEVEL[ch]).read_text()
    m = re.search(r'<div class="tp"><span class="tag">Travail pratique ' + str(ch) + r' — ([^<]*)</span>(.*?)</div>\n', s, flags=re.S)
    if not m: m = re.search(r'<div class="tp"><span class="tag">Travail pratique ' + str(ch) + r'[^<]*</span>(.*?)</div>\n', s, flags=re.S); title = ''; body = m.group(1)
    else: title, body = m.group(1), m.group(2)
    steps = [re.sub(r'<[^>]+>', '', x).strip() for x in re.findall(r'<li>(.*?)</li>', body, flags=re.S)]
    return title.strip(), steps, m

def slug(t):
    t = t.lower(); t = re.sub(r'[àâä]', 'a', t); t = re.sub(r'[éèêë]', 'e', t); t = re.sub(r'[îï]', 'i', t); t = re.sub(r'[ôö]', 'o', t); t = re.sub(r'[ùûü]', 'u', t); t = t.replace('ç', 'c')
    t = re.sub(r'[^a-z0-9]+', '-', t).strip('-'); return t[:60].rstrip('-')

HEAD = None
def build_page(ch, title, steps, sol, deliverable, further):
    global HEAD
    if HEAD is None:
        h = re.search(r'^.*?</head>', (out/'devops-00-fondations.html').read_text(), flags=re.S).group(0)
        extra = """
.pagenav{display:flex;flex-wrap:wrap;gap:.6rem;margin-bottom:1rem;font-size:.9rem}
.pagenav a{color:#fff;text-decoration:none;background:rgba(255,255,255,.1);border:1px solid rgba(255,255,255,.22);padding:.3rem .75rem;border-radius:6px}
.pagenav a:hover{background:rgba(255,255,255,.2);color:#fff}
.footnav{display:flex;justify-content:space-between;gap:1rem;flex-wrap:wrap;margin-top:2rem;padding-top:1.2rem;border-top:1px solid var(--line)}
.footnav a{text-decoration:none;font-weight:700;background:var(--paper);border:1px solid var(--line);padding:.6rem 1rem;border-radius:var(--radius)}
.out{font-family:"JetBrains Mono",monospace;font-size:.8rem;background:var(--bg);border:1px dashed var(--line-strong);border-radius:8px;padding:.6rem .8rem;white-space:pre-wrap;word-break:break-word;margin:.3rem 0 1rem}
.out::before{content:"résultat attendu";display:block;font-family:"Atkinson Hyperlegible",system-ui,sans-serif;font-size:.72rem;font-weight:700;color:var(--muted);margin-bottom:.3rem;letter-spacing:.04em;text-transform:uppercase}
.enonce{background:var(--bg);border:1px solid var(--line);border-radius:var(--radius);padding:.8rem 1rem 0.4rem 1rem;margin:0 0 1rem}
.enonce ol{margin:0 0 .5rem;padding-left:1.3rem;font-size:.9rem}
body{padding-bottom:2rem}
@media print{.pagenav,.footnav{display:none}}
</style>"""
        HEAD = h.replace('</style>', extra, 1)
    head = re.sub(r'<title>[^<]*</title>', f'<title>Correction du TP {ch} — {H.escape(title)}</title>', HEAD)
    lvl = LEVEL[ch]; nxt = f'{lvl}#c{ch+1}' if ch < 54 else 'index.html'
    b = f'''<body>
<header class="hero"><div class="in">
<div class="pagenav"><a href="../{lvl}#c{ch}">← Retour au chapitre {ch}</a><a href="../index.html">Accueil du parcours</a></div>
<div class="level">Correction type — Travail pratique {ch}</div>
<h1>{H.escape(title)}</h1>
<p class="lead">Une solution complète, étape par étape : ce qu'il faut produire, la commande ou le fichier clé, le résultat qui prouve que ça marche, et les pièges. Ta solution peut différer ; ce qui compte, c'est que chaque preuve soit là.</p>
</div></header>
<div class="single">
<div class="enonce"><strong>Énoncé</strong><ol>{''.join(f'<li>{H.escape(x)}</li>' for x in steps)}</ol></div>
'''
    for k, (st_title, code, expected, notes) in enumerate(sol, 1):
        b += f'<article><div class="chaphead"><span class="chapnum">Étape {k}</span></div><h2>{H.escape(st_title)}</h2>'
        if code: b += f'<pre><code>{H.escape(code)}</code></pre>'
        if expected: b += f'<div class="out">{H.escape(expected)}</div>'
        if notes: b += '<ul>' + ''.join(f'<li>{n}</li>' for n in notes) + '</ul>'
        b += '</article>\n'
    b += f'<article><div class="chaphead"><span class="chapnum">Livrable</span><span class="badge tag-important">Important</span></div><h2>Ce que le relecteur doit trouver</h2><ul>{"".join(f"<li>{d}</li>" for d in deliverable)}</ul></article>\n'
    if further: b += f'<article><div class="chaphead"><span class="chapnum">Pour aller plus loin</span><span class="badge tag-contexte">Bon à savoir</span></div><h2>Questions de relecteur</h2><ul>{"".join(f"<li>{f}</li>" for f in further)}</ul></article>\n'
    b += f'''<div class="footnav"><a href="../{lvl}#c{ch}">← Chapitre {ch}</a><a href="../{nxt}">{'Chapitre ' + str(ch+1) if ch < 54 else 'Accueil'} →</a></div>
</div>
<script>
(function(){{ var root=document.documentElement; try{{ var t=localStorage.getItem('devops-theme'); if(t) root.setAttribute('data-theme',t); }}catch(e){{}}
  document.querySelectorAll('pre').forEach(function(pre){{ var b=document.createElement('button'); b.type='button'; b.className='copy'; b.textContent='Copier';
    b.addEventListener('click',function(){{ var t=pre.querySelector('code').textContent; navigator.clipboard.writeText(t).then(function(){{ b.textContent='Copié !'; setTimeout(function(){{ b.textContent='Copier'; }},1500); }}); }}); pre.appendChild(b); }});
}})();
</script>
</body></html>'''
    return head + '\n' + b

CORR = {}   # ch -> (sol, deliverable, further)
def C(ch, sol, deliverable, further=None): CORR[ch] = (sol, deliverable, further or [])

# ================================================================ Niveau 0
C(3, [
 ("Un réseau Docker et deux services", "docker network create tp3\ndocker run -d --name api --network tp3 -p 3000:3000 -e PORT=3000 node:22-alpine sh -c \"echo 'require(\\\"http\\\").createServer((q,r)=>r.end(\\\"api ok\\\\n\\\")).listen(3000)' > s.js && node s.js\"\ndocker run -d --name web --network tp3 -p 8080:80 nginx:1.27\ndocker network inspect tp3 --format '{{range .Containers}}{{.Name}} {{.IPv4Address}}{{\"\\n\"}}{{end}}'", "api 172.20.0.2/16\nweb 172.20.0.3/16", ["Deux conteneurs sur le même réseau utilisateur se résolvent par nom : le DNS interne de Docker fait le travail, pas /etc/hosts.", "Le réseau <code>bridge</code> par défaut n'offre pas cette résolution par nom : toujours créer un réseau."]),
 ("Résolution, ports, connexion : la chaîne DNS → TCP → HTTP", "docker exec web sh -c 'getent hosts api ; nc -zv api 3000 ; wget -qO- http://api:3000'\ndocker exec web ss -tulpn 2>/dev/null || docker exec web netstat -tlnp", "172.20.0.2  api\napi (172.20.0.2:3000) open\napi ok\ntcp LISTEN 0.0.0.0:80  nginx", ["getent = DNS, nc = TCP, wget = HTTP : trois vérifications, trois couches, dans l'ordre du chapitre.", "Depuis Git Bash, <code>curl localhost:3000</code> et <code>curl localhost:8080</code> passent par les ports publiés ; <code>curl api:3000</code> échoue : le nom n'existe que dans le réseau Docker."]),
 ("Un reverse proxy nginx vers l'API", "cat > nginx.conf <<'EOF'\nevents {}\nhttp { server { listen 80;\n  location /api/ { proxy_pass http://api:3000/; proxy_set_header Host $host; proxy_set_header X-Forwarded-For $remote_addr; }\n  location / { return 200 'front\\n'; } } }\nEOF\ndocker run -d --name proxy --network tp3 -p 8081:80 -v \"$PWD/nginx.conf:/etc/nginx/nginx.conf:ro\" nginx:1.27\ncurl -i localhost:8081/api/", "HTTP/1.1 200 OK\nServer: nginx/1.27.x\napi ok", ["Le proxy joint l'API par son nom de conteneur sur le réseau tp3 ; l'API n'a plus besoin de publier son port : <code>docker rm -f api</code> puis relance sans <code>-p</code>.", "Arrête l'API et rejoue <code>curl -i localhost:8081/api/</code> : <code>502 Bad Gateway</code>. C'est le proxy qui parle ; un 502 signifie « backend injoignable », pas « bug de l'application »."]),
 ("TLS auto-signé et lecture du certificat", "openssl req -x509 -newkey rsa:2048 -nodes -keyout tp3.key -out tp3.crt -days 30 -subj '/CN=localhost' -addext 'subjectAltName=DNS:localhost'\nopenssl x509 -in tp3.crt -noout -subject -issuer -dates -ext subjectAltName\ncurl -k https://localhost:8443/ ; curl https://localhost:8443/", "subject=CN = localhost\nissuer=CN = localhost   (auto-signé : émetteur = sujet)\nnotAfter=Oct 22 …\nDNS:localhost\ncurl: (60) SSL certificate problem: self-signed certificate", ["Ajoute au nginx.conf un second <code>server { listen 443 ssl; ssl_certificate /etc/nginx/tp3.crt; ssl_certificate_key /etc/nginx/tp3.key; … }</code>, monte les deux fichiers, publie <code>-p 8443:443</code>.", "L'erreur 60 de curl sans <code>-k</code> est la bonne : le certificat n'est signé par aucune autorité connue. Avec <code>--cacert tp3.crt</code> ça passe : tu viens de faire confiance à cette autorité précise, pas à tout le monde."]),
 ("Les commandes de diagnostic réseau, dans le conteneur", "docker run --rm -it --network tp3 nicolaka/netshoot sh -c 'dig +short api ; ping -c 2 api ; traceroute -n api ; tcpdump -c 3 -n port 3000 &  sleep 1 ; curl -s api:3000'", "172.20.0.2\n2 packets transmitted, 2 received\n1  172.20.0.2\n… IP 172.20.0.5.4xxxx > 172.20.0.2.3000: Flags [S]", ["netshoot embarque tout l'outillage réseau ; l'image nginx n'a même pas <code>ping</code>.", "tcpdump montre le SYN de la poignée de main TCP : c'est la preuve concrète de l'étape « TCP » de la chaîne."]),
], ["Un dépôt <code>tp3/</code> avec <code>nginx.conf</code>, les certificats de test (30 jours, jamais réutilisés ailleurs), et un <code>tp3.md</code> qui montre les trois vérifications (getent, nc, wget) et la sortie d'<code>openssl x509</code>.", "L'explication du 502 en une phrase, et pourquoi l'API ne publie plus de port derrière le proxy.", "Le curl HTTPS avec <code>--cacert</code> qui passe, et sans qui échoue avec le code 60."],
 ["Pourquoi <code>proxy_set_header X-Forwarded-For</code> ? Sans lui, l'API voit l'adresse du proxy pour tous les clients : les logs et la limitation de débit sont faux.", "Que se passe-t-il si deux réseaux Docker ont le même nom de conteneur ? Rien : les noms sont uniques par démon ; mais un même nom de service dans deux piles Compose se résout dans chaque réseau séparément."])

C(4, [
 ("Squelette du script de sauvegarde", "#!/usr/bin/env bash\nset -euo pipefail\nIFS=$'\\n\\t'\nusage(){ echo \"usage: $0 -s SOURCE -d DEST [-k JOURS]\" >&2; exit 2; }\nKEEP=7\nwhile getopts \"s:d:k:h\" o; do case $o in s) SRC=$OPTARG;; d) DST=$OPTARG;; k) KEEP=$OPTARG;; *) usage;; esac; done\n[[ -n \"${SRC:-}\" && -n \"${DST:-}\" ]] || usage\n[[ -d \"$SRC\" ]] || { echo \"source absente : $SRC\" >&2; exit 1; }\nmkdir -p \"$DST\"\nlog(){ printf '%s %s\\n' \"$(date -Is)\" \"$*\"; }\nTMP=$(mktemp -d); trap 'rm -rf \"$TMP\"' EXIT\nARCH=\"$DST/backup-$(date +%F-%H%M).tar.gz\"\ntar czf \"$TMP/a.tgz\" -C \"$SRC\" . && mv \"$TMP/a.tgz\" \"$ARCH\"\nlog \"archive $ARCH ($(du -h \"$ARCH\" | cut -f1))\"\nfind \"$DST\" -name 'backup-*.tar.gz' -mtime +\"$KEEP\" -print -delete | while read -r f; do log \"supprimé $f\"; done", "2026-09-22T10:20:11+00:00 archive /backups/backup-2026-09-22-1020.tar.gz (1.2M)", ["<code>set -euo pipefail</code> en première ligne utile : c'est la leçon de la planche manga du chapitre.", "L'archive est écrite dans un temporaire puis déplacée : jamais une archive à moitié écrite avec un nom définitif.", "<code>trap … EXIT</code> nettoie même en cas d'erreur ; <code>mktemp -d</code> évite les collisions."]),
 ("Exécution en conteneur, avec un échec provoqué", "docker run --rm -v \"$PWD:/w\" -w /w -v tp4data:/data -v tp4backups:/backups ubuntu:24.04 bash -c 'mkdir -p /data && echo hello > /data/f.txt && bash backup.sh -s /data -d /backups -k 7 && ls -la /backups'\ndocker run --rm -v \"$PWD:/w\" -w /w ubuntu:24.04 bash backup.sh -s /nexistepas -d /backups ; echo \"code de retour : $?\"", "-rw-r--r-- 1 root root 1234 … backup-2026-09-22-1020.tar.gz\nsource absente : /nexistepas\ncode de retour : 1", ["Un script sérieux se teste d'abord sur son échec : mauvais chemin, argument manquant, disque plein. Ici, sortie 1 avec un message sur stderr.", "Sans <code>set -e</code>, l'échec du <code>tar</code> laisserait le script continuer et supprimer d'anciennes sauvegardes quand même."]),
 ("ShellCheck et tests Bats", "docker run --rm -v \"$PWD:/mnt\" koalaman/shellcheck backup.sh\ncat > test/backup.bats <<'EOF'\n@test \"refuse une source absente\" { run bash backup.sh -s /nope -d /tmp/b ; [ \"$status\" -eq 1 ] ; [[ \"$output\" == *\"source absente\"* ]] ; }\n@test \"crée une archive\" { mkdir -p /tmp/s ; echo x > /tmp/s/f ; run bash backup.sh -s /tmp/s -d /tmp/b ; [ \"$status\" -eq 0 ] ; ls /tmp/b/backup-*.tar.gz ; }\nEOF\ndocker run --rm -v \"$PWD:/code\" bats/bats test/", "✓ refuse une source absente\n✓ crée une archive\n2 tests, 0 failures", ["ShellCheck attrape les variables non citées et les <code>$?</code> mal utilisés avant qu'ils ne coûtent en production.", "Deux tests suffisent : un cas nominal, un cas d'erreur ; chaque bug corrigé plus tard ajoute son test."]),
 ("La version Python du même outil", "# backup.py : argparse, logging, subprocess, pathlib\nimport argparse, logging, subprocess, tarfile, tempfile, shutil, time\nfrom pathlib import Path\np = argparse.ArgumentParser(); p.add_argument('-s', required=True, type=Path); p.add_argument('-d', required=True, type=Path); p.add_argument('-k', type=int, default=7)\na = p.parse_args(); logging.basicConfig(level=logging.INFO, format='%(asctime)s %(levelname)s %(message)s')\nif not a.s.is_dir(): raise SystemExit(f'source absente : {a.s}')\na.d.mkdir(parents=True, exist_ok=True)\nwith tempfile.TemporaryDirectory() as tmp:\n    tmp_arch = Path(tmp) / 'a.tgz'\n    with tarfile.open(tmp_arch, 'w:gz') as t: t.add(a.s, arcname='.')\n    final = a.d / f\"backup-{time.strftime('%F-%H%M')}.tar.gz\"; shutil.move(tmp_arch, final); logging.info('archive %s', final)\nfor f in a.d.glob('backup-*.tar.gz'):\n    if time.time() - f.stat().st_mtime > a.k * 86400: f.unlink(); logging.info('supprimé %s', f)\n\n# docker run --rm -v \"$PWD:/w\" -w /w python:3.12-slim python backup.py -s /w/src -d /w/out", "2026-09-22 10:31:02 INFO archive out/backup-2026-09-22-1031.tar.gz", ["Même logique, même structure ; Python gagne dès qu'il y a une vraie structure de données, un appel HTTP ou des tests plus riches (pytest, monkeypatch).", "<code>raise SystemExit('message')</code> écrit sur stderr et sort avec le code 1 : l'équivalent de l'erreur Bash."]),
], ["<code>backup.sh</code> avec en-tête, options, usage, temporaire, trap, rotation ; ShellCheck vert ; deux tests Bats verts ; <code>backup.py</code> équivalent.", "Un <code>tp4.md</code> qui montre l'exécution nominale et l'échec provoqué avec son code de retour.", "Aucune commande exécutée sur le poste : tout passe par <code>docker run</code> avec le répertoire monté."],
 ["Que se passerait-il sans <code>IFS=$'\\n\\t'</code> sur un répertoire dont un fichier contient un espace ?", "Pourquoi <code>find … -mtime +7</code> compte en jours entiers ? (7 signifie strictement plus de 7 × 24 h.)"])

C(5, [
 ("Dépôt, commits conventionnels, branche", "git init tp5 && cd tp5 && git switch -c main\nprintf 'root = true\\n[*]\\nend_of_line = lf\\n' > .editorconfig ; printf '* text=auto eol=lf\\n' > .gitattributes ; printf '.env\\n*.key\\n' > .gitignore\ngit add -A && git commit -m 'chore: initialisation du dépôt'\ngit switch -c feature/api-health\necho 'ok' > health.txt && git add health.txt && git commit -m 'feat(api): endpoint /health'\ngit log --oneline --graph --all", "* 3e1f2a7 (HEAD -> feature/api-health) feat(api): endpoint /health\n* a1b2c3d (main) chore: initialisation du dépôt", ["<code>.gitattributes</code> avec <code>eol=lf</code> dès le premier commit : sinon les scripts commités sous Windows cassent dans les conteneurs (<code>\\r</code> en fin de ligne).", "Conventional Commits : <code>type(portée): description</code> ; c'est ce que semantic-release et commitlint liront au niveau 2."]),
 ("Conflit provoqué et résolu", "git switch main && echo 'v1' > version.txt && git add . && git commit -m 'chore: version 1'\ngit switch feature/api-health && echo 'v2' > version.txt && git add . && git commit -m 'chore: version 2'\ngit rebase main", "CONFLICT (add/add): Merge conflict in version.txt\nerror: could not apply 4f5e6d7… chore: version 2", ["Ouvre <code>version.txt</code> : les marqueurs <code>&lt;&lt;&lt;&lt;&lt;&lt;&lt;</code>, <code>=======</code>, <code>&gt;&gt;&gt;&gt;&gt;&gt;&gt;</code>. Garde <code>v2</code>, puis <code>git add version.txt && git rebase --continue</code>. Le graphe est maintenant linéaire.", "<code>git rebase --abort</code> à tout moment ramène à l'état d'avant : rien n'est perdu."]),
 ("Un merge propre, un revert, un reset annulé par reflog", "git switch main && git merge --no-ff feature/api-health -m 'merge: feature/api-health'\ngit revert --no-edit HEAD~1          # annule le commit de version sans réécrire\ngit reset --hard HEAD~2 && git log --oneline | head -1   # « oups »\ngit reflog | head -4\ngit reset --hard 'HEAD@{1}'", "a1b2c3d chore: initialisation du dépôt          (après le reset : tout semble perdu)\n9c8d7e6 HEAD@{0}: reset: moving to HEAD~2\n1b2c3d4 HEAD@{1}: revert: Revert \"chore: version 1\"\nHEAD is now at 1b2c3d4 Revert \"chore: version 1\"", ["<code>--no-ff</code> garde la trace de la branche dans le graphe ; <code>revert</code> crée un commit inverse : c'est ce qu'on fait sur main, jamais <code>reset</code> sur une branche poussée.", "Le reflog est la démonstration du chapitre : <code>reset --hard</code> déplace la branche, les commits existent encore pendant 90 jours."]),
 ("Signature des commits et secret commité", "git config user.signingkey ~/.ssh/id_ed25519.pub ; git config gpg.format ssh ; git config commit.gpgsign true\ngit commit --allow-empty -m 'chore: commit signé' && git log --show-signature -1 | head -3\necho 'AKIAIOSFODNN7EXAMPLE' > creds.txt && git add creds.txt && git commit -m 'oops'\ndocker run --rm -v \"$PWD:/repo\" zricethezav/gitleaks detect -s /repo --no-banner", "Good \"git\" signature for gael@… with ED25519 key\n○ leaks found: 1   Finding: AKIAIOSFODNN7EXAMPLE  RuleID: aws-access-key  File: creds.txt", ["gitleaks trouve la clé dans l'historique même après <code>git rm</code> : la seule réponse à une clé commitée est de la <strong>révoquer</strong>, puis de nettoyer (<code>git filter-repo --path creds.txt --invert-paths</code>) et de forcer le push, en prévenant l'équipe.", "Installe gitleaks en hook pre-commit (pre-commit framework) : le secret n'entre jamais dans l'historique."]),
 ("Pousser vers GitHub et protéger main", "git remote add origin git@github.com:TABETG/tp5.git && git push -u origin main && git push -u origin feature/api-health\n# Settings → Branches → Add rule : main : require pull request, 1 approval, require status checks, no force push", "branch protection rule : main (PR required, force push blocked)", ["Une branche protégée rend le workflow du chapitre obligatoire ; c'est ce que ton dépôt DevOpsCourses fait déjà avec develop et master.", "Ouvre une pull request depuis feature/api-health et fusionne-la par squash : un commit propre sur main."]),
], ["Un dépôt avec <code>.gitattributes</code>, <code>.editorconfig</code>, <code>.gitignore</code>, des commits conventionnels, un conflit résolu par rebase, un merge --no-ff, un revert, une récupération par reflog documentée dans <code>tp5.md</code>.", "Une capture de la règle de protection de main et une PR fusionnée.", "Le rapport gitleaks et la phrase « un secret commité est révoqué »."],
 ["Pourquoi <code>rebase</code> sur sa branche locale et jamais sur une branche partagée ?", "Quelle différence entre <code>git pull</code> et <code>git pull --rebase</code>, et lequel choisir pour une branche de fonctionnalité ?"])

C(6, [
 ("PostgreSQL en conteneur, schéma et données", "docker run -d --name pg -e POSTGRES_PASSWORD=tp6 -e POSTGRES_DB=shop -v tp6pg:/var/lib/postgresql/data -p 5432:5432 postgres:16\ndocker exec -i pg psql -U postgres -d shop <<'EOF'\nCREATE TABLE customers(id serial PRIMARY KEY, email text UNIQUE NOT NULL, created_at timestamptz DEFAULT now());\nCREATE TABLE orders(id serial PRIMARY KEY, customer_id int REFERENCES customers(id), amount numeric(10,2) NOT NULL, status text NOT NULL, created_at timestamptz DEFAULT now());\nINSERT INTO customers(email) SELECT 'user'||g||'@ex.com' FROM generate_series(1,10000) g;\nINSERT INTO orders(customer_id,amount,status) SELECT (random()*9999+1)::int, (random()*500)::numeric(10,2), (ARRAY['paid','pending','refunded'])[1+(random()*2)::int] FROM generate_series(1,500000);\nEOF\ndocker exec pg psql -U postgres -d shop -c '\\dt' -c 'SELECT count(*) FROM orders'", " public | customers | table | postgres\n public | orders    | table | postgres\n count\n 500000", ["Un volume nommé pour les données : <code>docker rm pg</code> puis relance avec le même volume, tout est là.", "<code>generate_series</code> crée un jeu réaliste en secondes : c'est ce qui rend l'étape suivante parlante."]),
 ("Requêtes, jointure, agrégation, et le plan", "docker exec pg psql -U postgres -d shop -c \"EXPLAIN ANALYZE SELECT c.email, sum(o.amount) FROM orders o JOIN customers c ON c.id=o.customer_id WHERE o.status='paid' GROUP BY c.email ORDER BY 2 DESC LIMIT 5;\"", "Seq Scan on orders o  (cost=0.00..10347.00 rows=166667 …)  Filter: (status = 'paid')  Rows Removed by Filter: 333xxx\nExecution Time: 210.5 ms", ["Le Seq Scan sur 500 000 lignes avec un filtre qui en rejette deux tiers : c'est le cas d'école.", "Note le temps d'exécution avant l'index : c'est ta mesure « avant »."]),
 ("L'index qui change tout, et sa preuve", "docker exec pg psql -U postgres -d shop -c 'CREATE INDEX CONCURRENTLY idx_orders_status_customer ON orders(status, customer_id);' -c 'ANALYZE orders;'\ndocker exec pg psql -U postgres -d shop -c \"EXPLAIN ANALYZE SELECT … (même requête)\"", "Index Scan using idx_orders_status_customer on orders o  (Index Cond: (status = 'paid'))\nExecution Time: 62.3 ms", ["<code>CONCURRENTLY</code> ne verrouille pas la table : c'est la seule façon d'indexer en production.", "L'ordre des colonnes compte : le filtre d'égalité (status) en premier, la jointure ensuite. Un index sur <code>customer_id</code> seul n'aurait pas aidé ce filtre."]),
 ("Transaction : atomicité démontrée", "docker exec -i pg psql -U postgres -d shop <<'EOF'\nBEGIN;\nUPDATE orders SET amount = amount - 50 WHERE id = 1;\nUPDATE orders SET amount = amount + 50 WHERE id = 99999999;   -- 0 ligne : erreur métier\nSELECT 'vérif', count(*) FROM orders WHERE id = 99999999;\nROLLBACK;\nSELECT amount FROM orders WHERE id = 1;\nEOF", "UPDATE 1\nUPDATE 0\n vérif | 0\nROLLBACK\n amount : inchangé", ["Sans transaction, le premier UPDATE serait resté : 50 € disparus. Avec, ROLLBACK remet tout.", "Dans l'application : une méthode <code>@Transactional</code> par cas d'usage, et une vérification du nombre de lignes affectées (UPDATE 0 est une erreur métier, pas un succès)."]),
 ("Sauvegarde, destruction, restauration", "docker exec pg pg_dump -U postgres -Fc shop > shop.dump && ls -la shop.dump\ndocker exec pg psql -U postgres -c 'DROP DATABASE shop;' -c 'CREATE DATABASE shop;'\ndocker exec -i pg pg_restore -U postgres -d shop < shop.dump\ndocker exec pg psql -U postgres -d shop -c 'SELECT count(*) FROM orders'", "-rw-r--r-- … 9.8M shop.dump\n count\n 500000", ["Une sauvegarde non restaurée n'existe pas : cette étape est la seule qui prouve quelque chose.", "<code>-Fc</code> (format compressé) permet de restaurer une table seule ; pour la production, sauvegarde physique et PITR (chapitre 47)."]),
 ("Redis et un cache simple", "docker run -d --name redis -p 6379:6379 redis:7\ndocker exec redis redis-cli SET top5 '[...]' EX 60 ; docker exec redis redis-cli TTL top5 ; docker exec redis redis-cli GET top5", "OK\n(integer) 58\n\"[...]\"", ["Le cache a une durée de vie : sans <code>EX</code>, une valeur périmée survit à jamais. Le TTL est la première décision d'un cache, avant la clé.", "En Spring : <code>@Cacheable</code> avec un TTL Redis ; l'invalidation à l'écriture reste la partie difficile."]),
], ["Un <code>tp6.sql</code> (schéma, données, index) et <code>tp6.md</code> avec les deux plans EXPLAIN ANALYZE (avant 210 ms, après 62 ms, valeurs indicatives) et la transaction annulée.", "Le fichier de sauvegarde et la preuve de restauration (count identique).", "Une phrase sur le TTL du cache."],
 ["Pourquoi <code>ANALYZE</code> après la création de l'index ? Sans statistiques à jour, le planificateur peut ignorer l'index.", "Que devient l'index si <code>status</code> n'a que trois valeurs distinctes ? Sélectivité faible : c'est la colonne <code>customer_id</code> en second qui le rend utile pour la jointure."])

# ================================================================ Niveau 1
C(7, [
 ("Le poste : Docker Desktop et WSL 2 vus de près", "docker version --format '{{.Server.Os}}/{{.Server.Arch}} {{.Server.Version}}'\nwsl -l -v\ndocker run --rm alpine uname -a\ndocker run --rm -v \"$PWD:/w\" alpine sh -c 'time (for i in $(seq 200); do cat /w/README.md > /dev/null; done)'", "linux/amd64 27.x\n  docker-desktop  Running  2\nLinux … 5.15.x-microsoft-standard-WSL2 …\nreal 0m1.9s   (montage Windows lent)", ["Le démon tourne dans une VM Linux WSL 2 ; <code>uname</code> dans un conteneur montre le noyau de cette VM, pas Windows.", "Le montage d'un répertoire Windows (<code>/c/…</code>) traverse une frontière de systèmes de fichiers : lent. Le même test avec le répertoire copié dans un volume nommé prend quelques centièmes de seconde. C'est la raison des volumes nommés pour node_modules et target."]),
 ("Une VM en conteneur : le labo sans hyperviseur", "docker run -d --name vmlab --privileged -p 2222:22 -v tp7:/var/lib/libvirt/images qemux/qemu-docker  # ou : docker run --rm -it ubuntu:24.04 bash pour le shell seul\n# comparer : temps de démarrage, empreinte\ndocker stats --no-stream ubuntu-lab", "conteneur : démarre en 0,3 s, 4 Mo de mémoire au repos\nVM : 30 à 60 s, 512 Mo minimum", ["Le TP demande la comparaison, pas une VM en production : un conteneur Ubuntu et les chiffres de <code>docker stats</code> suffisent pour la démonstration.", "Sans hyperviseur sur le poste (interdit), la comparaison des ordres de grandeur se fait avec les valeurs de référence du chapitre 7.1."]),
 ("Modules Terraform Proxmox et Nutanix, validés sans hyperviseur", "mkdir -p tp7/{proxmox,nutanix}\ncat > tp7/proxmox/main.tf <<'EOF'\nterraform { required_providers { proxmox = { source = \"bpg/proxmox\", version = \"~> 0.70\" } } }\nprovider \"proxmox\" { endpoint = var.endpoint, api_token = var.api_token }\nvariable \"endpoint\" { type = string } ; variable \"api_token\" { type = string, sensitive = true } ; variable \"ssh_pub\" { type = string }\nresource \"proxmox_virtual_environment_vm\" \"web\" {\n  name = \"crisisshield-web\" ; node_name = \"pve1\"\n  clone { vm_id = 9000 } ; cpu { cores = 2 } ; memory { dedicated = 2048 }\n  initialization { ip_config { ipv4 { address = \"10.0.1.11/24\", gateway = \"10.0.1.1\" } } user_account { username = \"deploy\", keys = [var.ssh_pub] } }\n}\nEOF\ndocker run --rm -v \"$PWD/tp7/proxmox:/w\" -w /w hashicorp/terraform:1.9 sh -c 'terraform init -backend=false && terraform validate'", "Terraform has been successfully initialized!\nSuccess! The configuration is valid.", ["<code>init -backend=false</code> télécharge le provider et valide sans state ni accès à un hyperviseur : c'est ce que fait la CI en revue.", "Même exercice avec le provider <code>nutanix/nutanix</code> (ressource <code>nutanix_virtual_machine</code>, catégories, sous-réseau) : les deux modules créent la même VM."]),
 ("Inventaire dynamique Ansible et commandes du premier jour", "cat > tp7/inventory.proxmox.yml <<'EOF'\nplugin: community.general.proxmox\nurl: https://pve.lab:8006\nuser: ci@pve\ntoken_id: terraform\ntoken_secret: \"{{ lookup('env', 'PVE_TOKEN') }}\"\nwant_facts: true\nkeyed_groups: [{ key: proxmox_tags_parsed, separator: \"\" }]\nEOF\ndocker run --rm -v \"$PWD/tp7:/w\" -w /w willhallonline/ansible:2.17-alpine ansible-inventory -i inventory.proxmox.yml --list 2>&1 | head -3", "(sans hyperviseur : erreur de connexion attendue ; le plugin est reconnu, le fichier est valide)", ["<code>docs/tp7-commandes.md</code> : <code>pvecm status</code>, <code>qm list</code>, <code>qm config 100</code>, <code>pct list</code>, <code>vzdump 101 --storage pbs</code>, <code>ha-manager status</code> ; <code>acli vm.list</code>, <code>ncli cluster info</code>, <code>ncc health_checks run_all</code>. Pour chacune, une ligne : quand je la tape et ce que je regarde.", "Si tu as un Developer Sandbox Nutanix ou un Proxmox de labo, exécute réellement ; sinon, la validation Terraform et l'inventaire valide sont la preuve attendue."]),
 ("Plan du homelab", "# docs/homelab.md — matériel ou VM cloud imbriquée, plan d'adressage (MGMT 10.0.10.0/24, SERVERS 10.0.20.0/24, IOT 10.0.30.0/24),\n# nœud admin (IdP, OpenBao, step-ca), distribution (Talos), les 4 phases avec leur porte de sortie, journal de bord.", "", ["Une page, pas plus ; la porte de sortie de chaque phase est la partie qui compte.", "La variante virtuelle (Proxmox dans une VM cloud à virtualisation imbriquée) respecte la règle « rien sur le poste »."]),
], ["<code>tp7.md</code> avec les chiffres VM contre conteneur mesurés (démarrage, mémoire) et l'explication de la lenteur des montages Windows.", "Deux modules Terraform (Proxmox, Nutanix) qui passent <code>terraform validate</code> en conteneur, un inventaire dynamique valide, la fiche des commandes du premier jour.", "<code>docs/homelab.md</code> en une page."],
 ["Pourquoi <code>--privileged</code> est-il nécessaire pour faire tourner une VM dans un conteneur, et pourquoi est-ce inacceptable pour une application ?", "Quelle est la différence entre le quorum corosync de Proxmox et le quorum etcd de Kubernetes ? (Même problème, même réponse : une majorité de votes.)"])

C(8, [
 ("Un Dockerfile multi-étapes pour l'API Spring Boot", "cat > Dockerfile <<'EOF'\nFROM eclipse-temurin:21-jdk-alpine AS build\nWORKDIR /src\nCOPY mvnw pom.xml ./\nCOPY .mvn .mvn\nRUN ./mvnw -q dependency:go-offline\nCOPY src src\nRUN ./mvnw -q package -DskipTests && java -Djarmode=layertools -jar target/*.jar extract --destination /layers\n\nFROM eclipse-temurin:21-jre-alpine\nRUN addgroup -S app && adduser -S -G app app\nWORKDIR /app\nCOPY --from=build /layers/dependencies/ ./\nCOPY --from=build /layers/spring-boot-loader/ ./\nCOPY --from=build /layers/snapshot-dependencies/ ./\nCOPY --from=build /layers/application/ ./\nUSER app\nEXPOSE 8080\nHEALTHCHECK --interval=15s --timeout=3s --start-period=30s CMD wget -qO- http://localhost:8080/actuator/health || exit 1\nENTRYPOINT [\"java\", \"-XX:MaxRAMPercentage=75\", \"org.springframework.boot.loader.launch.JarLauncher\"]\nEOF\nprintf 'target\\n.git\\n*.md\\n' > .dockerignore\ndocker build -t crisisshield-api:1.0.0 . && docker images crisisshield-api", "crisisshield-api  1.0.0  …  198MB   (contre ~450 Mo avec le JDK et le jar entier)", ["Les dépendances (couche stable) sont copiées avant le code (couche volatile) : rebuild d'un changement de code en secondes.", "USER non root, HEALTHCHECK, ENTRYPOINT en forme exec, <code>MaxRAMPercentage</code> pour respecter la limite mémoire du conteneur : les quatre points que le chapitre exige."]),
 ("Lecture des couches et du cache", "docker history crisisshield-api:1.0.0 --format '{{.Size}}\\t{{.CreatedBy}}' | head -8\ntouch src/main/java/Dummy.java && docker build -t crisisshield-api:1.0.1 . 2>&1 | grep -E 'CACHED|RUN'", "…  COPY /layers/dependencies/ ./     (CACHED)\n…  COPY /layers/application/ ./      (reconstruite)\n#8 CACHED  RUN ./mvnw dependency:go-offline", ["Seule la couche application est reconstruite quand le code change ; si <code>dependency:go-offline</code> se relance, c'est que <code>pom.xml</code> a bougé, ou que COPY src est placé trop tôt.", "dive (<code>docker run --rm -it -v /var/run/docker.sock:/var/run/docker.sock wagoodman/dive crisisshield-api:1.0.0</code>) montre l'efficacité par couche."]),
 ("Exécution durcie, arrêt propre, codes de sortie", "docker run -d --name api -p 8080:8080 --read-only --tmpfs /tmp --cap-drop ALL --security-opt no-new-privileges --memory 512m --pids-limit 200 -e SPRING_PROFILES_ACTIVE=docker crisisshield-api:1.0.0\ndocker inspect api --format '{{.State.Health.Status}}' ; sleep 30 ; docker inspect api --format '{{.State.Health.Status}}'\ntime docker stop api ; docker inspect api --format '{{.State.ExitCode}}'\ndocker run -d --name oom --memory 64m crisisshield-api:1.0.0 ; sleep 15 ; docker inspect oom --format '{{.State.ExitCode}} {{.State.OOMKilled}}'", "starting … healthy\nreal 0m2.1s   (arrêt propre en 2 s)\n143\n137 true", ["143 = 128 + 15 : SIGTERM reçu et traité par la JVM, grâce à la forme exec. 137 = 128 + 9 : OOMKilled, la limite de 64 Mo est trop basse pour une JVM.", "<code>--read-only</code> casse ? L'application écrit dans /tmp : d'où le <code>--tmpfs /tmp</code>. Chaque échec de durcissement est une information sur ce que l'application fait réellement."]),
 ("Déboguer : logs, exec, netshoot, events", "docker logs --tail 20 api\ndocker exec -it api sh -c 'id ; ls -la /app | head -3 ; wget -qO- localhost:8080/actuator/health'\ndocker run --rm -it --network container:api nicolaka/netshoot ss -tulpn\ndocker events --since 5m --filter container=api", "uid=100(app) gid=101(app)\n{\"status\":\"UP\"}\ntcp LISTEN 0.0.0.0:8080 (java)\n… container health_status: healthy", ["L'image jre-alpine n'a pas <code>curl</code> ni <code>ss</code> : netshoot dans le namespace réseau du conteneur (<code>--network container:api</code>) donne tout l'outillage sans modifier l'image.", "<code>docker events</code> montre les transitions de santé et les redémarrages : utile quand un conteneur « meurt sans raison »."]),
 ("Scan et hadolint", "docker run --rm -i hadolint/hadolint < Dockerfile\ndocker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy image --severity HIGH,CRITICAL --ignore-unfixed --exit-code 1 crisisshield-api:1.0.0 ; echo \"code $?\"", "(hadolint : 0 avertissement, ou DL3018 si apk sans version épinglée)\nTotal: 0 (HIGH: 0, CRITICAL: 0)\ncode 0", ["Si Trivy trouve des High dans la base : passer à un tag de base plus récent, jamais « ignorer ».", "Ce <code>--exit-code 1</code> devient le job de scan du pipeline au niveau 2."]),
], ["Le <code>Dockerfile</code> multi-étapes avec couches Spring Boot, <code>.dockerignore</code>, l'image sous 200 Mo.", "<code>tp8.md</code> : la sortie de <code>docker history</code>, la preuve du cache, les codes 143 et 137 expliqués, la commande de lancement durcie, le rapport Trivy et hadolint.", "Aucun Maven sur le poste : le build se fait dans l'étape <code>build</code> de l'image."],
 ["Pourquoi <code>MaxRAMPercentage=75</code> et pas <code>-Xmx</code> fixe ? Parce que la limite du conteneur peut changer (Kubernetes) et la JVM lit les cgroups.", "Que se passe-t-il si HEALTHCHECK utilise <code>curl</code> sur une image sans curl ? Le conteneur est <em>unhealthy</em> pour toujours : le healthcheck teste aussi l'image."])

C(9, [
 ("compose.yaml de CrisisShield : trois services, deux réseaux, volumes, secrets", "cat > compose.yaml <<'EOF'\nservices:\n  db:\n    image: postgres:16\n    environment: { POSTGRES_DB: crisis, POSTGRES_USER: crisis, POSTGRES_PASSWORD_FILE: /run/secrets/db_password }\n    secrets: [db_password]\n    volumes: [pgdata:/var/lib/postgresql/data]\n    networks: [backend]\n    healthcheck: { test: [\"CMD-SHELL\", \"pg_isready -U crisis -d crisis\"], interval: 5s, timeout: 3s, retries: 10 }\n  api:\n    build: ./api\n    environment: { SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/crisis, SPRING_DATASOURCE_USERNAME: crisis, SPRING_DATASOURCE_PASSWORD_FILE: /run/secrets/db_password }\n    secrets: [db_password]\n    depends_on: { db: { condition: service_healthy } }\n    networks: [backend, frontend]\n    healthcheck: { test: [\"CMD\", \"wget\", \"-qO-\", \"http://localhost:8080/actuator/health\"], interval: 10s, start_period: 40s, retries: 5 }\n    read_only: true\n    tmpfs: [/tmp]\n    cap_drop: [ALL]\n    security_opt: [no-new-privileges:true]\n  web:\n    build: ./web\n    depends_on: { api: { condition: service_healthy } }\n    networks: [frontend]\n    ports: [\"443:443\"]\nnetworks: { frontend: {}, backend: {} }\nvolumes: { pgdata: {} }\nsecrets: { db_password: { file: ./secrets/db_password.txt } }\nEOF\nmkdir -p secrets && openssl rand -base64 24 > secrets/db_password.txt && echo 'secrets/' >> .gitignore\ndocker compose config --quiet && docker compose up -d --build && docker compose ps", "NAME   STATUS\ndb     running (healthy)\napi    running (healthy)\nweb    running   0.0.0.0:443->443/tcp", ["Un seul port publié (443, le front) ; api joint db par son nom sur backend ; web ne voit pas db.", "Le mot de passe est un fichier secret monté, jamais une variable d'environnement visible dans <code>docker inspect</code>.", "Spring lit <code>SPRING_DATASOURCE_PASSWORD_FILE</code> via une petite classe de configuration (ou <code>spring.config.import=optional:file:/run/secrets/…</code>) : le code accompagne le TP."]),
 ("Ordre de démarrage et réseau, prouvés", "docker compose logs --timestamps api | head -3\ndocker compose exec web sh -c 'wget -qO- --timeout=2 http://db:5432 2>&1 | tail -1'\ndocker compose exec api sh -c 'wget -qO- http://db:5432 2>&1 | tail -1'", "api démarre après « db healthy » (horodatage)\nweb : wget: bad address 'db'     (frontend ne voit pas backend)\napi : … (connexion refusée par le protocole, mais le nom se résout : même réseau)", ["<code>bad address</code> depuis web est le résultat attendu : c'est la preuve de la segmentation.", "<code>docker compose config</code> affiche le fichier résolu : utile pour vérifier les surcharges et les variables."]),
 ("Panne simulée, retries, redémarrage", "docker compose kill db ; sleep 5 ; docker compose logs --tail 3 api ; docker compose start db ; sleep 15 ; curl -sk https://localhost/api/health", "api : HikariPool - Connection is not available … (retry)\n{\"status\":\"UP\"}   (reconnexion sans redémarrage de l'API)", ["depends_on n'agit qu'au démarrage : la reconnexion en cours de vie vient du pool applicatif (Hikari retente). C'est la limite à connaître.", "Ajoute <code>restart: unless-stopped</code> sur db et api pour les redémarrages du démon."]),
 ("Surcharge de développement et profils", "cat > compose.override.yaml <<'EOF'\nservices:\n  api: { ports: [\"8080:8080\"], environment: { SPRING_PROFILES_ACTIVE: dev } }\n  db: { ports: [\"5432:5432\"] }\n  adminer: { image: adminer, ports: [\"8081:8080\"], networks: [backend], profiles: [tools] }\nEOF\ndocker compose --profile tools up -d && docker compose ps --services", "db api web adminer   (adminer seulement avec le profil tools)", ["<code>compose.override.yaml</code> est lu automatiquement : ports de debug et outils en développement, absents en production (<code>-f compose.yaml -f compose.prod.yaml</code>).", "Le profil évite d'avoir adminer en production par accident."]),
 ("Sauvegarde du volume et nettoyage", "docker compose exec db pg_dump -U crisis -Fc crisis > crisis.dump\ndocker run --rm -v crisisshield_pgdata:/data -v \"$PWD:/b\" alpine tar czf /b/pgdata.tgz -C /data .\ndocker compose down ; docker volume ls | grep pgdata ; docker compose up -d && docker compose exec db psql -U crisis -c '\\dt'", "pgdata.tgz créé\ncrisisshield_pgdata   (le volume survit à down)\n… tables présentes", ["<code>down</code> sans <code>-v</code> garde les volumes ; <code>down -v</code> les détruit : c'est la commande à ne jamais taper par réflexe.", "Le nom du volume est préfixé par le nom du projet (dossier) : <code>docker volume ls</code> le montre."]),
], ["<code>compose.yaml</code>, <code>compose.override.yaml</code>, secrets en fichiers ignorés par Git, healthchecks, deux réseaux, durcissement.", "<code>tp9.md</code> : preuve de l'ordre de démarrage, preuve de la segmentation (<code>bad address</code>), comportement pendant la panne de db, sauvegarde du volume.", "Le cours joint (technos, fichiers, comment l'expliquer en entretien) comme pour chaque livraison CrisisShield."],
 ["Pourquoi <code>condition: service_healthy</code> et pas juste <code>depends_on: [db]</code> ?", "Que se passe-t-il si deux projets Compose utilisent le même nom de réseau <code>backend</code> ? Chacun a le sien, préfixé par le projet : pas de collision."])

C(10, [
 ("Un registre local et le cycle tag, push, digest", "docker run -d --name registry -p 5000:5000 -v tp10reg:/var/lib/registry registry:2\ndocker tag crisisshield-api:1.0.0 localhost:5000/crisisshield/api:1.0.0\ndocker push localhost:5000/crisisshield/api:1.0.0 | tail -1\ncurl -s localhost:5000/v2/crisisshield/api/tags/list\ndocker inspect --format '{{index .RepoDigests 0}}' localhost:5000/crisisshield/api:1.0.0", "1.0.0: digest: sha256:3f9c… size: 1789\n{\"name\":\"crisisshield/api\",\"tags\":[\"1.0.0\"]}\nlocalhost:5000/crisisshield/api@sha256:3f9c…", ["Le digest apparaît au push : c'est l'identité de l'image. Le tag n'est qu'un alias.", "Docker Desktop autorise <code>localhost:5000</code> en HTTP ; tout autre registre non TLS doit être déclaré insecure, ce qu'on ne fait jamais en production."]),
 ("Prouver que le tag est mutable et le digest ne l'est pas", "docker build -t localhost:5000/crisisshield/api:1.0.0 --build-arg X=2 . && docker push localhost:5000/crisisshield/api:1.0.0 | tail -1\ndocker pull localhost:5000/crisisshield/api@sha256:3f9c…   # l'ancien digest existe toujours", "1.0.0: digest: sha256:a77e…   (le même tag pointe maintenant ailleurs)\nsha256:3f9c… : Pull complete", ["Deux images différentes ont porté le tag 1.0.0 : un déploiement par tag ne sait pas laquelle il exécute. C'est l'argument du déploiement par digest.", "Un registre d'entreprise (Harbor) peut rendre les tags immuables : à activer sur les dépôts de production."]),
 ("SBOM, scan et signature", "docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v \"$PWD:/out\" anchore/syft localhost:5000/crisisshield/api:1.0.0 -o cyclonedx-json=/out/sbom.json && jq '.components | length' sbom.json\ndocker run --rm -v \"$PWD:/w\" anchore/grype sbom:/w/sbom.json --fail-on high ; echo \"code $?\"\ndocker run --rm -v \"$PWD:/w\" -w /w -e COSIGN_PASSWORD= gcr.io/projectsigstore/cosign generate-key-pair\ndocker run --rm --network host -v \"$PWD:/w\" -w /w -e COSIGN_PASSWORD= gcr.io/projectsigstore/cosign sign --key cosign.key --yes localhost:5000/crisisshield/api@sha256:a77e…\ndocker run --rm --network host -v \"$PWD:/w\" -w /w gcr.io/projectsigstore/cosign verify --key cosign.pub localhost:5000/crisisshield/api@sha256:a77e… | head -2", "214\ncode 0 (ou 1 avec la liste des High : mettre à jour la base)\nPushing signature to: localhost:5000/crisisshield/api\nVerification for localhost:5000/crisisshield/api@sha256:a77e… -- The following checks were performed …", ["Le SBOM d'abord, le scan sur le SBOM ensuite : quand une CVE sortira, tu rescanneras le fichier, pas l'image.", "Signature par clé ici (pas d'OIDC en local) ; keyless en CI au niveau 7. On signe un digest, jamais un tag."]),
 ("Politique de nommage et nettoyage", "# nommage : registre/équipe/service:semver et registre/équipe/service:<sha court> ; jamais latest en production\ndocker image ls --format '{{.Repository}}:{{.Tag}} {{.Size}}' | grep crisisshield\ndocker image prune -f ; docker system df", "localhost:5000/crisisshield/api:1.0.0 198MB\nlocalhost:5000/crisisshield/api:a1b2c3d 198MB\nTotal reclaimed space: …", ["Un tag par SHA de commit pour la traçabilité, un tag semver pour les humains, le digest pour les déploiements : trois noms, une image.", "Sur un registre, une politique de rétention (garder 10 tags, supprimer les images non taguées) évite le disque plein ; Harbor et ECR la font en interface."]),
], ["<code>tp10.md</code> : le digest au push, la preuve de la mutabilité du tag (deux digests pour 1.0.0), le SBOM (nombre de composants), le rapport grype, la signature vérifiée.", "Une politique de nommage écrite en cinq lignes, appliquée aux tags de CrisisShield.", "<code>cosign.key</code> hors de Git (<code>.gitignore</code>) ; <code>cosign.pub</code> commité."],
 ["Pourquoi signer le digest et non le tag ? Parce que le tag peut être réattribué à une autre image, la signature suivrait un contenu qu'on n'a pas vérifié.", "À quoi sert un proxy pull-through (Harbor, Nexus) devant Docker Hub ? Cache, limites de débit, et contrôle de ce qui entre."])

# ================================================================ Niveau 2
C(11, [
 ("Le pipeline minimal en conteneur, sans serveur de CI", "cat > ci.sh <<'EOF'\n#!/usr/bin/env bash\nset -euo pipefail\nlog(){ printf '\\n== %s ==\\n' \"$*\"; }\nlog build ; docker run --rm -v \"$PWD:/w\" -w /w -v tp11-m2:/root/.m2 eclipse-temurin:21-jdk ./mvnw -q -DskipTests package\nlog test  ; docker run --rm -v \"$PWD:/w\" -w /w -v tp11-m2:/root/.m2 eclipse-temurin:21-jdk ./mvnw -q test\nlog lint  ; docker run --rm -v \"$PWD:/mnt\" koalaman/shellcheck ci.sh\nlog image ; docker build -q -t crisisshield-api:$(git rev-parse --short HEAD) .\nlog scan  ; docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy image --severity CRITICAL --exit-code 1 --ignore-unfixed crisisshield-api:$(git rev-parse --short HEAD)\nlog ok\nEOF\nchmod +x ci.sh && time ./ci.sh", "== build == … == test == Tests run: 42, Failures: 0 … == image == sha256:… == scan == Total: 0 … == ok\nreal 2m10s (première fois), 40 s ensuite (cache .m2 dans un volume)", ["Un pipeline est une suite de commandes qui s'arrête au premier échec : <code>set -e</code> le fait déjà. Le serveur de CI n'ajoute que le déclenchement, l'isolation et les rapports.", "Le volume nommé pour <code>.m2</code> est le cache : sans lui, chaque exécution retélécharge les dépendances."]),
 ("Échouer vite : provoquer un test rouge", "sed -i 's/assertEquals(200/assertEquals(201/' src/test/java/…/HealthControllerTest.java ; ./ci.sh ; echo \"code $?\"", "== test == Tests run: 42, Failures: 1 … BUILD FAILURE\ncode 1   (l'image n'est pas construite)", ["L'ordre compte : tester avant de construire l'image évite de produire un artefact invalide.", "Remets le test, puis un commit : le pipeline vert est la définition de « prêt à intégrer »."]),
 ("Mesurer : durée par étape et feedback", "for s in build test image scan; do /usr/bin/time -f \"$s %es\" bash -c \"…\" ; done 2>&1 | grep -E '^(build|test|image|scan)'", "build 38s\ntest 41s\nimage 12s\nscan 9s", ["Le total dépasse dix minutes ? Paralléliser test et lint, réduire les tests lents, mettre le cache en place : c'est la matière du chapitre 12.", "Ces chiffres vont dans <code>value-stream.md</code> (TP 1) : le délai commit → artefact vient de commencer à baisser."]),
], ["<code>ci.sh</code> qui construit, teste, lint, construit l'image et la scanne, tout en conteneurs, avec un cache de dépendances.", "<code>tp11.md</code> : durée par étape, un échec provoqué et le code de retour, et ce que le serveur de CI apportera en plus.", "Le fichier <code>value-stream.md</code> mis à jour."],
 ["Pourquoi ne pas mettre le socket Docker dans un job de CI partagé ? Parce que quiconque écrit un job contrôle l'hôte : niveau 2 chapitre 12 et niveau 7 chapitre 40.", "Que vaut un pipeline qui passe sur le poste mais pas en CI ? Rien : la CI est la seule définition de « ça marche »."])

C(12, [
 ("Un GitLab et un runner en conteneurs", "cat > compose.gitlab.yaml <<'EOF'\nservices:\n  gitlab: { image: gitlab/gitlab-ce:17.4.0-ce.0, hostname: gitlab.local, ports: [\"8929:8929\",\"2224:22\"], environment: { GITLAB_OMNIBUS_CONFIG: \"external_url 'http://gitlab.local:8929'; gitlab_rails['gitlab_shell_ssh_port']=2224\" }, volumes: [gl-config:/etc/gitlab, gl-data:/var/opt/gitlab], shm_size: 256m }\n  runner: { image: gitlab/gitlab-runner:v17.4.0, volumes: [gl-runner:/etc/gitlab-runner, /var/run/docker.sock:/var/run/docker.sock] }\nvolumes: { gl-config: {}, gl-data: {}, gl-runner: {} }\nEOF\ndocker compose -f compose.gitlab.yaml up -d && sleep 240 && docker compose -f compose.gitlab.yaml exec gitlab grep Password /etc/gitlab/initial_root_password\ndocker compose -f compose.gitlab.yaml exec runner gitlab-runner register --non-interactive --url http://gitlab:8929 --token glrt-… --executor docker --docker-image alpine:3.20 --docker-network-mode tp12_default", "Password: …\nRunner registered successfully.", ["Le runner utilise l'exécuteur docker : chaque job tourne dans un conteneur jetable. Le socket monté ici est un compromis de labo, interdit en production (Kaniko, chapitre 40).", "<code>--docker-network-mode</code> pour que les jobs joignent GitLab par son nom."]),
 ("Le .gitlab-ci.yml de CrisisShield", "cat > .gitlab-ci.yml <<'EOF'\nstages: [build, test, package, deploy]\nvariables: { MAVEN_OPTS: \"-Dmaven.repo.local=.m2/repository\", DOCKER_TLS_CERTDIR: \"\" }\ndefault: { cache: { key: { files: [pom.xml] }, paths: [.m2/repository], policy: pull } }\nworkflow: { rules: [{ if: $CI_PIPELINE_SOURCE == \"merge_request_event\" }, { if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH }] }\nbuild:\n  stage: build\n  image: eclipse-temurin:21-jdk\n  script: [./mvnw -q -DskipTests package]\n  cache: { key: { files: [pom.xml] }, paths: [.m2/repository], policy: pull-push }\n  artifacts: { paths: [target/*.jar], expire_in: 1 day }\ntest:\n  stage: test\n  image: eclipse-temurin:21-jdk\n  needs: [build]\n  script: [./mvnw -q test]\n  artifacts: { reports: { junit: target/surefire-reports/TEST-*.xml }, when: always }\nlint:\n  stage: test\n  image: koalaman/shellcheck-alpine\n  needs: []\n  script: [shellcheck scripts/*.sh]\npackage:\n  stage: package\n  image: gcr.io/kaniko-project/executor:v1.23.0-debug\n  needs: [test, lint]\n  rules: [{ if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH }]\n  script: [/kaniko/executor --context $CI_PROJECT_DIR --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA]\ndeploy_staging:\n  stage: deploy\n  image: alpine:3.20\n  needs: [package]\n  environment: { name: staging, url: https://staging.crisisshield.example }\n  rules: [{ if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH }]\n  script: [\"echo deploy $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA\"]\n  resource_group: staging\nEOF\ngit add . && git commit -m 'ci: pipeline GitLab' && git push", "Pipeline #1 : build ✓ → test ✓ lint ✓ (parallèle) → package ✓ → deploy_staging ✓", ["<code>needs</code> crée le DAG : lint n'attend pas build ; test attend build seulement.", "<code>rules</code> : MR et branche par défaut uniquement ; package et deploy seulement sur main. <code>resource_group</code> empêche deux déploiements simultanés."]),
 ("Rapports dans la MR, artefacts, cache", "# ouvrir une MR avec un test cassé : l'onglet Tests de la MR montre l'échec ; corriger ; la MR passe au vert\n# vérifier le cache : deuxième pipeline, job build : « Restoring cache » et durée divisée par trois", "Restoring cache … pom.xml-… Successfully extracted cache\nbuild : 1 min 50 → 35 s", ["L'artefact (jar) passe de build à test ; le cache (.m2) accélère, mais un cache manquant ne doit jamais faire échouer.", "<code>when: always</code> sur le rapport JUnit : sinon un test rouge ne produit pas de rapport, et la MR n'affiche rien."]),
 ("Le même pipeline en GitHub Actions, et un job Jenkins", "cat > .github/workflows/ci.yml <<'EOF'\nname: ci\non: { pull_request: {}, push: { branches: [main] } }\npermissions: { contents: read, packages: write, id-token: write }\njobs:\n  build-test:\n    runs-on: ubuntu-24.04\n    steps:\n      - uses: actions/checkout@v4\n      - uses: actions/setup-java@v4\n        with: { distribution: temurin, java-version: '21', cache: maven }\n      - run: ./mvnw -q verify\n      - uses: actions/upload-artifact@v4\n        with: { name: jar, path: target/*.jar }\n  image:\n    needs: build-test\n    if: github.ref == 'refs/heads/main'\n    runs-on: ubuntu-24.04\n    steps:\n      - uses: actions/checkout@v4\n      - uses: docker/login-action@v3\n        with: { registry: ghcr.io, username: ${{ github.actor }}, password: ${{ secrets.GITHUB_TOKEN }} }\n      - uses: docker/build-push-action@v6\n        with: { push: true, tags: \"ghcr.io/${{ github.repository }}:${{ github.sha }}\" }\nEOF\n# Jenkinsfile : pipeline { agent { docker { image 'eclipse-temurin:21-jdk' } } stages { stage('build') { steps { sh './mvnw -q verify' } } } }", "GitHub : build-test ✓ image ✓ (main seulement)", ["Même structure, trois vocabulaires : stages/jobs/needs (GitLab), jobs/steps/needs (Actions), stages/steps (Jenkins). Le chapitre attend que tu saches lire les trois.", "<code>permissions</code> minimales et actions épinglées par tag (par SHA au niveau 7) : les deux réflexes de sécurité sur Actions."]),
], ["Un GitLab et un runner en Compose, le <code>.gitlab-ci.yml</code> avec DAG, rules, cache, artefacts, rapport JUnit, environnement et resource_group ; un workflow GitHub Actions équivalent ; un Jenkinsfile minimal.", "<code>tp12.md</code> : capture de la MR avec le rapport de tests, durée avec et sans cache, et le tableau de correspondance des trois vocabulaires.", "Le socket Docker documenté comme compromis de labo, avec la référence à Kaniko."],
 ["Pourquoi <code>policy: pull</code> par défaut et <code>pull-push</code> seulement sur build ? Pour que les jobs de test n'écrasent pas le cache en parallèle.", "Que se passe-t-il si deux MR déploient en staging en même temps sans <code>resource_group</code> ?"])

C(13, [
 ("Testcontainers à la place de H2, et un test d'intégration réel", "// src/test/java/…/IncidentRepositoryIT.java\n@SpringBootTest @Testcontainers\nclass IncidentRepositoryIT {\n  @Container static PostgreSQLContainer<?> pg = new PostgreSQLContainer<>(\"postgres:16\");\n  @DynamicPropertySource static void props(DynamicPropertyRegistry r){ r.add(\"spring.datasource.url\", pg::getJdbcUrl); r.add(\"spring.datasource.username\", pg::getUsername); r.add(\"spring.datasource.password\", pg::getPassword); }\n  @Autowired IncidentRepository repo;\n  @Test void enregistreEtRelit(){ var i = repo.save(new Incident(null, \"Fuite\", \"nord\", Priority.P1)); assertThat(repo.findById(i.id())).isPresent(); }\n}\n// exécution en CI : le job test monte /var/run/docker.sock (labo) ou utilise un service dind ; en local : docker run … eclipse-temurin ./mvnw verify avec le socket monté", "Tests run: 44, Failures: 0   (IncidentRepositoryIT : PostgreSQL 16 réel démarré en 3 s)", ["H2 ne se comporte pas comme PostgreSQL (types, verrous, SQL) : un test vert sur H2 peut être un bug en production.", "Le conteneur est démarré une fois par classe (<code>static</code>) : le coût est de quelques secondes."]),
 ("Couverture avec JaCoCo, seuil sur le nouveau code", "<!-- pom.xml -->\n<plugin><groupId>org.jacoco</groupId><artifactId>jacoco-maven-plugin</artifactId><version>0.8.12</version>\n  <executions><execution><goals><goal>prepare-agent</goal></goals></execution>\n  <execution><id>report</id><phase>verify</phase><goals><goal>report</goal></goals></execution></executions></plugin>\n# CI : rapport jacoco.xml publié ; seuil de 80 % sur les lignes nouvelles via SonarQube (quality gate « new code »)", "Couverture globale 71 %, nouveau code 84 %", ["La barrière porte sur le nouveau code : c'est la seule façon d'améliorer sans bloquer tout le monde.", "Une couverture élevée sans assertions ne vaut rien : d'où l'étape suivante."]),
 ("Mutation testing avec PIT", "docker run --rm -v \"$PWD:/w\" -w /w -v tp13-m2:/root/.m2 eclipse-temurin:21-jdk ./mvnw -q org.pitest:pitest-maven:mutationCoverage -DtargetClasses='fr.crisisshield.domain.*' -DtargetTests='fr.crisisshield.domain.*Test'\ngrep -o 'Mutation Score.*' target/pit-reports/*/index.html | head -1", "Line Coverage 92 %  Mutation Score 61 %   (31 mutants survivants dans EscalationPolicy)", ["Un mutant survivant = une ligne couverte mais non vérifiée : PIT a changé un <code>&gt;</code> en <code>&gt;=</code> et aucun test n'a échoué. Ajoute le test aux limites.", "On vise le domaine métier, pas les contrôleurs : c'est là que les bugs coûtent."]),
 ("SonarQube et la quality gate", "docker run -d --name sonar -p 9000:9000 sonarqube:community\n# créer un projet, un token ; dans le pipeline :\ndocker run --rm -v \"$PWD:/w\" -w /w -v tp13-m2:/root/.m2 --network host eclipse-temurin:21-jdk ./mvnw -q verify sonar:sonar -Dsonar.host.url=http://localhost:9000 -Dsonar.token=$SONAR_TOKEN -Dsonar.qualitygate.wait=true", "ANALYSIS SUCCESSFUL … QUALITY GATE STATUS: PASSED (ou FAILED : le job échoue et la MR est bloquée)", ["<code>sonar.qualitygate.wait=true</code> fait attendre le verdict : sans lui, l'analyse passe même si la barrière échoue.", "Règles de la barrière : couverture nouveau code ≥ 80 %, 0 bug, 0 vulnérabilité, dette nouvelle ≤ 30 min, duplication ≤ 3 %."]),
 ("Test de contrat avec le front (Pact) et test de charge k6", "# consumer (React) : pact test → target/pacts/web-api.json ; provider (Spring) : @Provider(\"api\") @PactBroker verify\n# k6 : docker run --rm -i -v \"$PWD:/w\" --network host grafana/k6 run /w/load.js --vus 20 --duration 1m\n# load.js : http.get('http://localhost:8080/api/incidents') ; check(res, {'200': r => r.status === 200}) ; thresholds: { http_req_duration: ['p(95)<300'] }", "✓ 200 … http_req_duration p(95)=142ms   (seuil 300 ms tenu)", ["Le contrat protège le front d'un changement d'API non annoncé ; le seuil k6 protège la production d'une régression de performance : les deux en CI, bloquants.", "Le seuil se choisit avec une marge sur la mesure actuelle, puis se resserre."]),
], ["Tests d'intégration sur PostgreSQL réel (Testcontainers), JaCoCo, PIT avec un mutant tué documenté, SonarQube avec barrière bloquante, un contrat Pact, un scénario k6 avec seuil.", "<code>tp13.md</code> : la pyramide de CrisisShield (nombre de tests par niveau, durées), le score de mutation avant et après, la capture de la quality gate.", "Pipeline mis à jour : test → couverture → analyse → gate, la MR bloquée si FAILED."],
 ["Pourquoi PIT sur le domaine et pas sur toute la base de code ? Coût d'exécution, et c'est là que la logique est.", "Un test de charge dans le pipeline de MR ou un pipeline nocturne ? Un scénario court en MR (2 minutes), le complet la nuit."])

C(14, [
 ("Lockfiles, versions épinglées, reproductibilité", "grep -c '<version>' pom.xml ; ./mvnw -q dependency:tree | head -5    # via docker run … eclipse-temurin\nnpm ci --ignore-scripts && git diff --exit-code package-lock.json && echo 'lock intact'\n# Maven : versions dans dependencyManagement + BOM Spring Boot ; jamais de LATEST ni de plage", "lock intact\n[INFO] fr.crisisshield:api:jar:1.0.0\n[INFO] +- org.springframework.boot:spring-boot-starter-web:jar:3.3.4", ["<code>npm ci</code> (jamais <code>npm install</code> en CI) installe exactement le lockfile et échoue s'il diverge.", "Pour Maven, le BOM Spring Boot épingle les versions transitives ; <code>dependency:tree</code> montre d'où vient chaque version."]),
 ("Un proxy Nexus devant les dépôts publics", "docker run -d --name nexus -p 8081:8081 -v tp14nexus:/nexus-data sonatype/nexus3\n# créer maven-proxy (central), npm-proxy (registry.npmjs.org), docker-proxy (hub) ; un groupe maven-public\ncat > .mvn/settings.xml <<'EOF'\n<settings><mirrors><mirror><id>nexus</id><mirrorOf>*</mirrorOf><url>http://nexus:8081/repository/maven-public/</url></mirror></mirrors></settings>\nEOF\necho 'registry=http://nexus:8081/repository/npm-proxy/' > .npmrc\n# build avec -s .mvn/settings.xml : Nexus se remplit ; couper le réseau externe : le build passe encore", "Nexus : maven-proxy 312 composants mis en cache ; build hors ligne OK", ["Le proxy rend le build indépendant d'Internet et permet une liste d'autorisation (blocage d'un paquet malveillant pour toute l'entreprise).", "Le groupe (<code>maven-public</code>) agrège proxy et dépôt interne : une seule URL pour les développeurs."]),
 ("Renovate en conteneur, une MR par mise à jour", "cat > renovate.json <<'EOF'\n{ \"$schema\": \"https://docs.renovatebot.com/renovate-schema.json\", \"extends\": [\"config:recommended\"],\n  \"packageRules\": [ { \"matchUpdateTypes\": [\"patch\"], \"automerge\": true, \"matchManagers\": [\"maven\",\"npm\"] },\n                    { \"matchUpdateTypes\": [\"major\"], \"labels\": [\"major\"], \"schedule\": [\"before 6am on monday\"] } ],\n  \"vulnerabilityAlerts\": { \"labels\": [\"security\"], \"automerge\": true },\n  \"lockFileMaintenance\": { \"enabled\": true, \"schedule\": [\"before 6am on monday\"] } }\nEOF\ndocker run --rm -e RENOVATE_PLATFORM=gitlab -e RENOVATE_ENDPOINT=http://gitlab:8929/api/v4 -e RENOVATE_TOKEN=$GL_TOKEN --network tp12_default renovate/renovate:38 crisisshield/api", "INFO: Repository started … 6 branches créées : chore(deps): update dependency org.postgresql:postgresql to v42.7.4 …", ["Les correctifs se fusionnent seuls si le pipeline est vert ; les majeures attendent une revue le lundi : la charge de revue reste supportable.", "<code>vulnerabilityAlerts</code> fusionne en priorité ce qui corrige une CVE."]),
 ("Analyse de composition : dépendances et image", "docker run --rm -v \"$PWD:/w\" aquasec/trivy fs --scanners vuln,misconfig,secret --severity HIGH,CRITICAL --exit-code 1 /w\n./mvnw -q org.cyclonedx:cyclonedx-maven-plugin:makeAggregateBom && jq '.components | length' target/bom.json", "Total: 2 (HIGH: 2)  jackson-databind 2.15.2 → fix 2.17.1   (Renovate a déjà ouvert la MR)\n188", ["<code>trivy fs</code> lit le lockfile et le pom : pas besoin de construire l'image pour connaître les CVE des dépendances.", "Le BOM CycloneDX produit par Maven est le SBOM « source » ; celui de l'image (syft) ajoute l'OS. Les deux vont dans Dependency-Track (niveau 7)."]),
 ("Versions et changelog automatiques", "cat > .releaserc.json <<'EOF'\n{ \"branches\": [\"main\"], \"plugins\": [\"@semantic-release/commit-analyzer\", \"@semantic-release/release-notes-generator\", \"@semantic-release/changelog\", \"@semantic-release/git\", \"@semantic-release/gitlab\"] }\nEOF\n# job release sur main : docker run --rm -v \"$PWD:/w\" -w /w -e GITLAB_TOKEN node:22 npx semantic-release\n# commitlint en hook : echo 'foo' | npx commitlint → échec ; 'feat(api): x' → OK", "Published release 1.1.0 (feat → mineure ; fix → correctif ; BREAKING CHANGE → majeure)\nCHANGELOG.md mis à jour, tag v1.1.0 créé", ["Le numéro de version est déduit des commits conventionnels : plus de débat sur « c'est une 1.1 ou une 2.0 ».", "commitlint en hook et en CI garantit le format ; sans lui, semantic-release ne publie rien."]),
], ["Lockfiles vérifiés en CI, Nexus proxy avec settings et npmrc, renovate.json avec auto-merge des correctifs, trivy fs et BOM CycloneDX dans le pipeline, semantic-release et commitlint.", "<code>tp14.md</code> : preuve du build hors ligne via Nexus, capture des MR Renovate, une CVE corrigée par fusion automatique, le premier tag semantic-release.", "Politique de dépendances en dix lignes (qui approuve les majeures, délai de correction par gravité)."],
 ["Quelle différence entre un lockfile et un BOM ? Le premier fige les versions, le second les inventorie.", "Pourquoi ne pas auto-fusionner les majeures ? Changements d'API : elles cassent le code, un humain lit le changelog."])

C(15, [
 ("Un déploiement bleu/vert avec Compose et nginx", "# deux services api-blue, api-green ; nginx upstream sur un fichier de config rechargeable\ncat > nginx/upstream.conf <<'EOF'\nupstream api { server api-blue:8080; }\nEOF\ndocker compose up -d --scale api-green=1 api-green   # nouvelle version à côté\ncurl -sf localhost:8080/health -H 'Host: green.local' || docker compose exec proxy wget -qO- http://api-green:8080/actuator/health\nsed -i 's/api-blue/api-green/' nginx/upstream.conf && docker compose exec proxy nginx -s reload\nfor i in $(seq 20); do curl -s localhost/api/version; done | sort | uniq -c", "     20 1.1.0   (bascule instantanée, aucune requête perdue)", ["La bascule est un rechargement de configuration, réversible en une seconde : remettre api-blue et recharger.", "Le vert est vérifié avant de recevoir du trafic : c'est la différence avec un simple redémarrage."]),
 ("Canary pondéré", "cat > nginx/upstream.conf <<'EOF'\nupstream api { server api-blue:8080 weight=9; server api-green:8080 weight=1; }\nEOF\ndocker compose exec proxy nginx -s reload\nfor i in $(seq 100); do curl -s localhost/api/version; done | sort | uniq -c", "     91 1.0.0\n      9 1.1.0", ["10 % du trafic sur la nouvelle version ; on regarde le taux d'erreur et la latence du canary avant d'augmenter à 50 puis 100.", "Sans métriques comparées (chapitre 35), un canary est un déploiement lent, pas un déploiement sûr."]),
 ("Feature flag : déployer sans activer", "// Spring : @Value(\"${features.export-csv:false}\") boolean exportCsv ; ou un client OpenFeature/Flipt\n// endpoint /api/incidents/export renvoie 404 si le flag est faux\ndocker compose exec api sh -c 'wget -qO- localhost:8080/api/incidents/export' ; echo\n# activer sans redéployer : variable d'environnement rechargée (Spring Cloud Config) ou Flipt : flipt flag enable export-csv\ndocker compose exec api sh -c 'wget -qO- localhost:8080/api/incidents/export | head -c 80'", "404\nid,titre,zone,priorite … (activé pour tous, ou pour un groupe d'utilisateurs)", ["Le code est en production depuis des jours quand la fonctionnalité s'allume : le déploiement n'est plus l'événement.", "Un flag est une dette : date de suppression dans le ticket, sinon le code se remplit de branches mortes."]),
 ("Rollback en une commande, et migration compatible", "# rollback : image précédente par digest\ndocker compose exec proxy sh -c \"sed -i 's/api-green/api-blue/' /etc/nginx/upstream.conf && nginx -s reload\"\n# ou avec Compose : docker compose up -d api --no-deps (image: api@sha256:ancien)\n# migration : Flyway V12__add_zone_code.sql (ADD COLUMN NULL) déployée avant le code qui l'utilise ; le code v1.0.0 tourne encore avec le schéma v12", "retour à 1.0.0 en 1 s ; le schéma v12 reste, compatible avec 1.0.0", ["Un rollback n'est possible que si le schéma est compatible N-1 : expand avant contract (chapitre 47).", "Testé en staging à chaque déploiement, pas découvert le jour où il faut."]),
 ("Runbook de déploiement", "# docs/runbooks/deploiement.md : préconditions (pipeline vert, budget d'erreur, fenêtre), étapes (canary 10 %, 15 min, seuils, 50 %, 100 %), critères d'arrêt (5xx > 1 %, p95 > 300 ms), commande de rollback, qui prévenir, post-déploiement (smoke test, annotation Grafana)", "", ["Un runbook est ce qu'un collègue exécute à 3 h sans toi : commandes exactes, seuils chiffrés, une seule décision par étape.", "Il devient le pipeline d'Argo Rollouts au niveau 5 : les seuils sont les mêmes."]),
], ["La configuration Compose et nginx du bleu/vert et du canary pondéré, le flag dans le code de CrisisShield, la migration Flyway compatible, le runbook.", "<code>tp15.md</code> : les comptages <code>uniq -c</code> qui prouvent la répartition, le rollback chronométré, l'activation du flag sans redéploiement.", "Le cours joint sur les stratégies et comment les expliquer en entretien (avantages, coût, quand)."],
 ["Bleu/vert double les ressources pendant la bascule ; canary non. Quand accepter le premier ?", "Comment tester un rollback sans casser la production ? En staging, à chaque déploiement, automatiquement."])

# ================================================================ Niveau 3
C(16, [
 ("LocalStack et un backend S3 pour le state", "docker run -d --name localstack -p 4566:4566 -e SERVICES=s3,ec2,iam,dynamodb localstack/localstack:3\nalias awsl='docker run --rm --network host -e AWS_ACCESS_KEY_ID=test -e AWS_SECRET_ACCESS_KEY=test -e AWS_DEFAULT_REGION=eu-west-3 amazon/aws-cli --endpoint-url http://localhost:4566'\nawsl s3 mb s3://tfstate && awsl s3api put-bucket-versioning --bucket tfstate --versioning-configuration Status=Enabled\nawsl dynamodb create-table --table-name tflock --attribute-definitions AttributeName=LockID,AttributeType=S --key-schema AttributeName=LockID,KeyType=HASH --billing-mode PAY_PER_REQUEST", "make_bucket: tfstate\n\"TableStatus\": \"ACTIVE\"", ["Versioning sur le bucket : chaque apply garde l'ancien state, restaurable. Table de verrou : deux apply simultanés sont impossibles.", "Le même schéma sur un vrai compte AWS au niveau 4 ; ici LocalStack, gratuit et jetable."]),
 ("Structure : modules et environnements", "mkdir -p modules/network envs/dev envs/prod\ncat > modules/network/main.tf <<'EOF'\nvariable \"name\" { type = string } ; variable \"cidr\" { type = string, validation { condition = can(cidrhost(var.cidr, 0)), error_message = \"CIDR invalide.\" } } ; variable \"azs\" { type = list(string) }\nresource \"aws_vpc\" \"this\" { cidr_block = var.cidr, tags = { Name = var.name } }\nresource \"aws_subnet\" \"private\" { for_each = toset(var.azs), vpc_id = aws_vpc.this.id, cidr_block = cidrsubnet(var.cidr, 8, index(var.azs, each.key)), availability_zone = each.key, tags = { Name = \"${var.name}-${each.key}\" } }\noutput \"vpc_id\" { value = aws_vpc.this.id } ; output \"subnet_ids\" { value = { for k, s in aws_subnet.private : k => s.id } }\nEOF\ncat > envs/dev/main.tf <<'EOF'\nterraform { required_version = \"~> 1.9\" ; required_providers { aws = { source = \"hashicorp/aws\", version = \"~> 5.60\" } }\n  backend \"s3\" { bucket = \"tfstate\", key = \"dev/network.tfstate\", region = \"eu-west-3\", dynamodb_table = \"tflock\", endpoints = { s3 = \"http://localhost:4566\", dynamodb = \"http://localhost:4566\" }, skip_credentials_validation = true, skip_metadata_api_check = true, skip_requesting_account_id = true, use_path_style = true } }\nprovider \"aws\" { region = \"eu-west-3\", access_key = \"test\", secret_key = \"test\", skip_credentials_validation = true, skip_requesting_account_id = true, endpoints { ec2 = \"http://localhost:4566\", s3 = \"http://localhost:4566\", iam = \"http://localhost:4566\" } }\nmodule \"network\" { source = \"../../modules/network\", name = \"crisis-dev\", cidr = \"10.10.0.0/16\", azs = [\"eu-west-3a\", \"eu-west-3b\"] }\noutput \"subnets\" { value = module.network.subnet_ids }\nEOF\nalias tf='docker run --rm -v \"$PWD:/w\" -w /w --network host hashicorp/terraform:1.9'\ncd envs/dev && tf init && tf fmt -check -recursive ../.. && tf validate && tf plan -out=tfplan && tf apply tfplan", "Plan: 3 to add, 0 to change, 0 to destroy.\nApply complete! Resources: 3 added.\nsubnets = { \"eu-west-3a\" = \"subnet-…\", \"eu-west-3b\" = \"subnet-…\" }", ["<code>for_each</code> sur un set d'AZ : ajouter une zone n'invalide pas les autres (avec <code>count</code>, l'index bougerait).", "Un state par environnement (<code>key</code>), un module partagé : la structure demandée par le chapitre."]),
 ("Dérive, import, moved, verrou", "awsl ec2 create-tags --resources $(tf output -raw vpc_id 2>/dev/null || awsl ec2 describe-vpcs --query 'Vpcs[0].VpcId' --output text) --tags Key=Owner,Value=console\ntf plan | grep -A3 'tags'\n# import d'un bucket créé à la main\nawsl s3 mb s3://crisis-dev-logs ; printf 'import { to = aws_s3_bucket.logs, id = \"crisis-dev-logs\" }\\nresource \"aws_s3_bucket\" \"logs\" { bucket = \"crisis-dev-logs\" }\\n' >> main.tf && tf plan\n# moved : renommer module.network en module.net sans recréer\nprintf 'moved { from = module.network, to = module.net }\\n' >> main.tf && sed -i 's/module \"network\"/module \"net\"/' main.tf && tf plan | tail -3\n# verrou : lancer deux plan en parallèle\n(tf plan >/dev/null &) ; sleep 1 ; tf plan 2>&1 | head -3", "~ tags = { \"Owner\" = \"console\" → null }   (Terraform veut retirer le tag posé à la main : dérive détectée)\nPlan: 1 to import, 0 to add\nPlan: 0 to add, 0 to change, 0 to destroy. (moved : aucune recréation)\nError: Error acquiring the state lock", ["La dérive apparaît au plan ; on la corrige par le code (ajouter le tag) ou on la laisse se corriger par l'apply. <code>ignore_changes</code> seulement pour ce qu'un autre système gère.", "Le verrou fait exactement ce qu'on attend ; <code>force-unlock</code> seulement après avoir vérifié qu'aucun apply ne tourne."]),
 ("Sécurité et coût dans la CI", "docker run --rm -v \"$PWD:/w\" aquasec/trivy config --exit-code 1 --severity HIGH,CRITICAL /w\ndocker run --rm -v \"$PWD:/w\" -w /w bridgecrew/checkov -d . --quiet\ndocker run --rm -v \"$PWD:/w\" -w /w infracost/infracost breakdown --path envs/prod   # nécessite une clé gratuite\n# pipeline : fmt-check → validate → trivy config → plan (artefact + commentaire de MR via tfcmt) → apply manuel sur main avec resource_group", "trivy : 0 HIGH (ou : « S3 bucket sans chiffrement » → corriger avec aws_s3_bucket_server_side_encryption_configuration)\ninfracost : monthly cost $42.10", ["Le plan est un artefact revu dans la MR ; l'apply est un job manuel sur main, jamais depuis un poste.", "Les findings de trivy config sont des vraies erreurs de configuration, pas du bruit : chiffrement, journalisation, accès public."]),
 ("Tests Terraform avec mocks, et un vrai contre LocalStack", "cat > tests/network.tftest.hcl <<'EOF'\nmock_provider \"aws\" {}\nrun \"deux_subnets\" { command = plan\n  variables { name = \"t\", cidr = \"10.0.0.0/16\", azs = [\"a\", \"b\"] }\n  assert { condition = length(aws_subnet.private) == 2, error_message = \"deux subnets attendus\" } }\nrun \"cidr_invalide\" { command = plan\n  variables { name = \"t\", cidr = \"pas-un-cidr\", azs = [\"a\"] }\n  expect_failures = [var.cidr] }\nEOF\ncd modules/network && tf test", "tests/network.tftest.hcl… pass\n  run \"deux_subnets\"… pass\n  run \"cidr_invalide\"… pass\nSuccess! 2 passed, 0 failed.", ["<code>mock_provider</code> teste la logique du module sans rien créer, en secondes ; un test réel contre LocalStack en CI complète.", "<code>expect_failures</code> vérifie que la validation refuse bien une entrée invalide."]),
], ["Le dépôt avec <code>modules/</code>, <code>envs/dev</code> et <code>envs/prod</code>, backend S3 versionné avec verrou DynamoDB (LocalStack), variables validées, <code>for_each</code>, outputs.", "<code>tp16.md</code> : le plan de dérive, l'import, le <code>moved</code> sans recréation, l'erreur de verrou, les rapports trivy config et checkov, le coût infracost, les tests <code>terraform test</code>.", "Le pipeline avec plan en MR et apply manuel."],
 ["Pourquoi un state par environnement et pas un workspace Terraform ? Isolation de l'accès et du rayon d'impact : un workspace partage le backend et ses droits.", "Que se passe-t-il si le bucket du state perd son versioning et qu'un apply corrompt le state ?"])

C(17, [
 ("Trois hôtes cibles en conteneurs, et l'inventaire", "for h in web1 web2 db1; do docker run -d --name $h --network tp17 -p 0:22 rastasheep/ubuntu-sshd:18.04 >/dev/null; done   # image de labo avec sshd (root:root) ; ou une image Ubuntu + openssh-server + ta clé\ncat > inventory/lab.ini <<'EOF'\n[web]\nweb1 ansible_host=web1\nweb2 ansible_host=web2\n[db]\ndb1 ansible_host=db1\n[all:vars]\nansible_user=root\nansible_ssh_private_key_file=/w/keys/lab\nansible_python_interpreter=/usr/bin/python3\nEOF\nalias ans='docker run --rm -it -v \"$PWD:/w\" -w /w --network tp17 -e ANSIBLE_HOST_KEY_CHECKING=False willhallonline/ansible:2.17-alpine'\nans ansible all -i inventory/lab.ini -m ping", "web1 | SUCCESS => { \"ping\": \"pong\" }\nweb2 | SUCCESS … db1 | SUCCESS", ["Les hôtes n'ont ni agent ni Ansible : SSH et Python suffisent. Si Python manque : <code>ansible.builtin.raw: apt-get install -y python3</code> en premier.", "<code>host_key_checking</code> désactivé en labo seulement ; en production, <code>ssh-keyscan</code> alimente <code>known_hosts</code>."]),
 ("Rôles : commun, nginx, docker ; playbook site.yml", "ans ansible-galaxy init roles/common && ans ansible-galaxy init roles/nginx\ncat > roles/nginx/tasks/main.yml <<'EOF'\n- name: Paquet nginx\n  ansible.builtin.apt: { name: nginx, state: present, update_cache: true }\n- name: Configuration du site\n  ansible.builtin.template: { src: site.conf.j2, dest: /etc/nginx/sites-available/default, validate: 'nginx -t -c /etc/nginx/nginx.conf', backup: true }\n  notify: reload nginx\n- name: Service actif\n  ansible.builtin.service: { name: nginx, state: started, enabled: true }\nEOF\ncat > roles/nginx/handlers/main.yml <<'EOF'\n- name: reload nginx\n  ansible.builtin.service: { name: nginx, state: reloaded }\nEOF\ncat > roles/nginx/defaults/main.yml <<'EOF'\nnginx_upstream: \"api:8080\"\nEOF\ncat > site.yml <<'EOF'\n- hosts: all\n  become: true\n  roles: [common]\n- hosts: web\n  become: true\n  roles: [nginx]\nEOF\nans ansible-playbook -i inventory/lab.ini site.yml && ans ansible-playbook -i inventory/lab.ini site.yml | grep 'changed=' ", "PLAY RECAP : web1 ok=6 changed=3 … (1er passage)\nweb1 ok=6 changed=0 … (2e passage : idempotent)", ["<code>changed=0</code> au second passage est la preuve d'idempotence demandée par le chapitre.", "<code>validate:</code> sur le template : une configuration invalide n'est jamais écrite ; <code>backup: true</code> garde l'ancienne."]),
 ("Variables, précédence, Vault", "cat > group_vars/web.yml <<'EOF'\nnginx_upstream: \"api:9090\"\nEOF\nans ansible-inventory -i inventory/lab.ini --host web1 --yaml\nans ansible-vault encrypt_string --vault-id dev@prompt 'S3cr3t' --name db_password >> group_vars/db.yml\nans ansible-playbook -i inventory/lab.ini site.yml --vault-id dev@prompt -e nginx_upstream=api:7070 --check --diff | grep -A3 upstream", "nginx_upstream: api:9090  (group_vars gagne sur defaults)\n… -e gagne sur tout : le diff montre api:7070", ["<code>ansible-inventory --host</code> tranche toute question de précédence.", "Une valeur chiffrée inline reste diffable dans Git ; un fichier entier chiffré ne l'est pas."]),
 ("Déploiement avec serial, block/rescue, delegate", "cat > deploy.yml <<'EOF'\n- hosts: web\n  serial: \"50%\"\n  max_fail_percentage: 0\n  any_errors_fatal: true\n  become: true\n  tasks:\n    - name: Retirer du load balancer\n      ansible.builtin.file: { path: \"/w/lb/{{ inventory_hostname }}.up\", state: absent }\n      delegate_to: localhost\n    - block:\n        - name: Déployer la version\n          ansible.builtin.copy: { content: \"{{ app_version }}\", dest: /var/www/html/version.txt }\n        - name: Readiness\n          ansible.builtin.uri: { url: \"http://localhost/version.txt\", return_content: true }\n          register: r\n          until: app_version in r.content\n          retries: 10\n          delay: 1\n      rescue:\n        - ansible.builtin.copy: { content: \"rollback\", dest: /var/www/html/version.txt }\n        - ansible.builtin.fail: { msg: \"déploiement annulé sur {{ inventory_hostname }}\" }\n      always:\n        - name: Remettre dans le load balancer\n          ansible.builtin.file: { path: \"/w/lb/{{ inventory_hostname }}.up\", state: touch }\n          delegate_to: localhost\nEOF\nans ansible-playbook -i inventory/lab.ini deploy.yml -e app_version=1.2.0\nans ansible-playbook -i inventory/lab.ini deploy.yml -e app_version=1.3.0 -e '{\"ansible_become\": false}' ; echo \"code $?\"   # échec provoqué sur un hôte", "web1 puis web2, un à la fois, readiness OK\nweb1 : FAILED → rescue : rollback, always : remis dans le LB ; le play s'arrête (any_errors_fatal)", ["<code>serial</code> limite le rayon d'impact ; <code>rescue</code> ramène l'hôte dans un état sain ; <code>always</code> garantit qu'il revient dans le load balancer même en échec.", "Le « load balancer » est simulé par des fichiers sur le contrôleur : le mécanisme est le même avec une API."]),
 ("Performance, lint, Molecule", "printf '[defaults]\\nforks = 50\\ngathering = smart\\nfact_caching = jsonfile\\nfact_caching_connection = /tmp/facts\\nstdout_callback = yaml\\n[ssh_connection]\\npipelining = True\\n' > ansible.cfg\ntime ans ansible-playbook -i inventory/lab.ini site.yml >/dev/null\ndocker run --rm -v \"$PWD:/w\" -w /w pipelinecomponents/ansible-lint ansible-lint --profile production\n# Molecule : molecule init scenario -r nginx -d docker ; molecule test (dans un conteneur avec le socket)", "real 0m9s (contre 0m21s sans pipelining ni cache de facts)\nPassed: 0 failure(s), 0 warning(s) on 14 files.", ["Les cinq réglages d'<code>ansible.cfg</code> divisent le temps par deux sur trois hôtes ; sur cent, par dix.", "ansible-lint profil production : noms complets des modules, tâches nommées, pas de shell quand un module existe."]),
], ["Le dépôt Ansible : inventaire, rôles common et nginx avec defaults, handlers, template validé ; <code>site.yml</code> idempotent (changed=0 prouvé) ; <code>deploy.yml</code> avec serial, block/rescue/always, delegate_to, until ; valeurs Vault ; <code>ansible.cfg</code> ; lint vert.", "<code>tp17.md</code> : les deux PLAY RECAP, la sortie d'<code>ansible-inventory --host</code>, l'échec provoqué avec rollback, les temps avant/après réglages.", "Un paragraphe : ce qu'Ansible fait encore dans un monde Kubernetes (hôtes, opérations, bootstrap), et ce qu'il ne fait plus."],
 ["Pourquoi <code>notify</code> plutôt que redémarrer nginx à chaque passage ? Zéro coupure quand rien n'a changé.", "Quelle différence entre <code>serial: 1</code> et <code>throttle: 1</code> ? Le premier découpe le play par hôtes, le second limite une tâche."])

C(18, [
 ("Packer : une image dorée construite et testée en conteneur", "cat > golden.pkr.hcl <<'EOF'\npacker { required_plugins { docker = { source = \"github.com/hashicorp/docker\", version = \"~> 1\" } } }\nsource \"docker\" \"ubuntu\" { image = \"ubuntu:24.04\" ; commit = true ; changes = [\"USER app\", \"ENTRYPOINT [\\\"/bin/bash\\\"]\"] }\nbuild {\n  sources = [\"source.docker.ubuntu\"]\n  provisioner \"shell\" { inline = [\"apt-get update\", \"apt-get install -y --no-install-recommends python3 ca-certificates\", \"useradd -m app\"] }\n  provisioner \"ansible\" { playbook_file = \"harden.yml\", user = \"root\" }\n  provisioner \"shell\" { inline = [\"apt-get clean\", \"rm -rf /var/lib/apt/lists/*\"] }\n  post-processor \"docker-tag\" { repository = \"crisis/golden-ubuntu\" ; tags = [\"24.04-$(date +%F)\"] }\n}\nEOF\ndocker run --rm -v \"$PWD:/w\" -w /w -v /var/run/docker.sock:/var/run/docker.sock hashicorp/packer:1.11 init . && docker run … packer:1.11 validate . && docker run … packer:1.11 build .", "==> docker.ubuntu: Provisioning with Ansible… PLAY RECAP … changed=12\nBuild 'docker.ubuntu' finished. Imported Docker image: crisis/golden-ubuntu:24.04-2026-09-22", ["Le builder Docker joue le rôle de l'AMI ou du template Proxmox : même Packer, même rôle Ansible de durcissement, même pipeline ; on change de builder pour AWS (<code>amazon-ebs</code>) ou Proxmox (<code>proxmox-iso</code>).", "L'image est datée : la rotation mensuelle est un nouveau build, jamais un patch en place."]),
 ("Le rôle de durcissement et ses tests", "cat > harden.yml <<'EOF'\n- hosts: all\n  tasks:\n    - ansible.builtin.lineinfile: { path: /etc/ssh/sshd_config, regexp: '^#?PermitRootLogin', line: 'PermitRootLogin no', create: true }\n    - ansible.builtin.lineinfile: { path: /etc/ssh/sshd_config, regexp: '^#?PasswordAuthentication', line: 'PasswordAuthentication no' }\n    - ansible.builtin.copy: { dest: /etc/sysctl.d/99-harden.conf, content: \"net.ipv4.conf.all.rp_filter=1\\nkernel.randomize_va_space=2\\n\" }\n    - ansible.builtin.apt: { name: unattended-upgrades, state: present }\nEOF\ncat > goss.yaml <<'EOF'\nfile: { /etc/ssh/sshd_config: { exists: true, contains: [\"PermitRootLogin no\", \"PasswordAuthentication no\"] } }\nuser: { app: { exists: true } }\npackage: { unattended-upgrades: { installed: true } }\nEOF\ndocker run --rm -v \"$PWD/goss.yaml:/goss.yaml\" --entrypoint sh crisis/golden-ubuntu:24.04-2026-09-22 -c 'curl -fsSL https://goss.rocks/install | sh >/dev/null && goss validate'   # ou l'image aelsabbahy/goss\ndocker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy image --severity HIGH,CRITICAL crisis/golden-ubuntu:24.04-2026-09-22 | tail -2", "Count: 4, Failed: 0, Skipped: 0\nTotal: 0 (HIGH: 0, CRITICAL: 0)", ["Goss vérifie l'état final de l'image (fichiers, utilisateurs, paquets) : c'est le test d'une image de machine.", "Trivy sur l'image dorée : une CVE ici est une CVE sur toutes les machines qui en dériveront."]),
 ("Cloud-init : la personnalisation au premier démarrage", "cat > user-data.yaml <<'EOF'\n#cloud-config\nhostname: crisis-web1\nusers: [{ name: deploy, groups: [sudo], shell: /bin/bash, sudo: 'ALL=(ALL) NOPASSWD:ALL', ssh_authorized_keys: [\"ssh-ed25519 AAAA…\"] }]\npackage_update: true\nwrite_files: [{ path: /etc/crisis/env, content: \"ENV=prod\\n\" }]\nruncmd: [\"systemctl enable --now docker\"]\nEOF\ndocker run --rm -v \"$PWD:/w\" -w /w python:3.12-slim sh -c 'pip -q install cloud-init-schema 2>/dev/null || pip -q install pyyaml ; python -c \"import yaml; yaml.safe_load(open(\\\"user-data.yaml\\\")); print(\\\"YAML valide\\\")\"'", "YAML valide   (validation complète : cloud-init schema --config-file user-data.yaml sur une VM)", ["L'image dorée contient ce qui est commun ; cloud-init apporte ce qui est spécifique à l'instance (nom, clés, rôle) : l'un ne remplace pas l'autre.", "Le <code>user_data</code> Terraform (chapitre 21) et l'<code>initialization</code> Proxmox (chapitre 7.4) sont ce même fichier."]),
 ("Talos : une machine sans SSH, décrite par un fichier", "docker run --rm ghcr.io/siderolabs/talosctl:v1.8.0 gen config crisis https://10.0.1.10:6443 --output-dir /tmp/t 2>&1 | tail -1   # dans un volume monté pour récupérer les fichiers\ndocker run --rm -v \"$PWD/talos:/t\" ghcr.io/siderolabs/talosctl:v1.8.0 validate --config /t/controlplane.yaml --mode cloud\n# machine config : machine.install.disk, machine.network.hostname, cluster.network.cni ; patch avec talosctl machineconfig patch", "generating PKI and tokens … created /tmp/t/controlplane.yaml, worker.yaml, talosconfig\ncontrolplane.yaml is valid for cloud mode", ["Tout ce qu'Ansible faisait sur une VM classique n'existe plus : pas de shell, pas de paquets ; la configuration est un fichier appliqué par API, et un nœud se remplace.", "C'est la distribution retenue pour le cluster du homelab (7.5) et le TP 25 peut l'utiliser à la place de kind si tu as des VM."]),
], ["<code>golden.pkr.hcl</code>, le playbook de durcissement, <code>goss.yaml</code> avec 0 échec, le rapport Trivy, un <code>user-data.yaml</code> cloud-init valide, la configuration Talos générée et validée.", "<code>tp18.md</code> : la sortie du build Packer, la date de l'image, la politique de rotation (mensuelle et à chaque CVE critique), la différence image dorée / cloud-init en trois lignes.", "Le pipeline : build mensuel planifié → tests Goss → scan → publication (tag daté) → Terraform pointe sur la dernière image validée."],
 ["Pourquoi ne pas tout mettre dans l'image dorée (clés SSH, secrets) ? Une image est partagée et immuable ; ce qui est propre à une instance ou secret vient au démarrage.", "Comment retire-t-on une image dorée compromise ? On la dépublie, on reconstruit, on remplace les instances : jamais on ne patche les machines en place."])

C(19, [
 ("Un dépôt de configuration et un déploiement par pull", "mkdir -p gitops/{apps/api,envs/dev,envs/prod}\ncat > gitops/apps/api/compose.yaml <<'EOF'\nservices: { api: { image: \"localhost:5000/crisisshield/api@sha256:a77e…\", ports: [\"8080:8080\"] } }\nEOF\ncd gitops && git init && git add . && git commit -m 'feat: api en dev'\n# l'agent de pull, le plus simple possible : une boucle qui applique ce que Git dit\ncat > agent.sh <<'EOF'\n#!/usr/bin/env bash\nset -euo pipefail\nwhile true; do git -C /repo pull -q ; docker compose -f /repo/apps/api/compose.yaml up -d --remove-orphans ; sleep 30 ; done\nEOF\ndocker run -d --name gitops-agent -v \"$PWD:/repo\" -v /var/run/docker.sock:/var/run/docker.sock -v \"$PWD/agent.sh:/agent.sh\" docker:27-cli sh /agent.sh", "l'agent applique l'état de Git toutes les 30 s ; modifier compose.yaml + commit → nouvelle version déployée sans push ni accès entrant", ["C'est le modèle pull en miniature : personne ne pousse vers l'environnement ; l'environnement lit Git. ArgoCD fait exactement cela avec Kubernetes au chapitre 29.", "Le digest dans le fichier est la clé : la promotion est un changement de digest commité."]),
 ("Dérive corrigée, et retour arrière par revert", "docker compose -f apps/api/compose.yaml exec api sh -c 'echo cassé' ; docker rm -f gitops-api-1 ; sleep 35 ; docker ps --filter name=api --format '{{.Names}} {{.Status}}'\ngit log --oneline | head -2 ; git revert --no-edit HEAD ; sleep 35 ; docker inspect gitops-api-1 --format '{{.Config.Image}}'", "gitops-api-1 Up 20 seconds   (le conteneur supprimé à la main revient : la dérive est corrigée)\nlocalhost:5000/crisisshield/api@sha256:3f9c…   (le revert a ramené l'ancien digest)", ["La réconciliation remet ce que Git décrit, y compris après une suppression manuelle : c'est ce qui rend l'environnement reconstructible.", "Le rollback est un commit comme un autre : traçable, revu, réversible."]),
 ("Promotion entre environnements et politique", "cat > envs/prod/kustomization.yaml <<'EOF'\nresources: [../../apps/api]\nimages: [{ name: crisisshield/api, digest: sha256:a77e… }]\nEOF\n# promotion : une MR qui change le digest de prod vers celui validé en dev ; règle : main protégée, 1 approbation, pipeline (kubeconform, trivy config, kyverno test) vert\ndocker run --rm -v \"$PWD:/w\" ghcr.io/yannh/kubeconform:latest-alpine -summary /w/envs/prod || true", "Summary: 3 resources found, 3 valid   (à partir du chapitre 26, ce sont des manifests Kubernetes)", ["Dev et prod pointent sur le même dossier d'application et diffèrent par le digest : promouvoir = copier un digest, pas reconstruire.", "Le pipeline du dépôt de config valide des manifests, pas du code : schéma, sécurité, politiques."]),
 ("Comparer push et pull, par écrit", "# docs/adr/0003-gitops-pull.md : contexte (accès entrant depuis la CI vers la prod, secrets de déploiement dans la CI), décision (pull par agent), conséquences (dérive corrigée, audit = git log, rollback = revert ; coût : un agent à exploiter, promotion par MR)", "", ["L'ADR est le livrable attendu : une décision datée avec ses conséquences, que le chapitre 51 rendra systématique.", "Le point clé pour l'entretien : en pull, la production n'a aucun identifiant de la CI et la CI n'a aucun accès à la production."]),
], ["Le dépôt de configuration avec <code>apps/</code> et <code>envs/</code>, l'agent de pull en conteneur, la preuve de réconciliation après suppression manuelle, le revert qui ramène l'ancien digest.", "<code>tp19.md</code> : chronologie des trois expériences (déploiement, dérive corrigée, rollback) avec les commandes et les digests.", "L'ADR push contre pull."],
 ["Pourquoi le digest et pas <code>latest</code> dans le dépôt de configuration ? Parce que l'agent ne détecterait aucun changement, et personne ne saurait ce qui tourne.", "Que doit-on faire pour qu'ArgoCD remplace cet agent au niveau 5 ? Rien dans la structure : seulement le format des fichiers (manifests) et l'outil."])

# ================================================================ génération des pages
def write_all(chs):
    n = 0
    for ch in chs:
        if ch not in CORR: continue
        title, steps, _ = tp_info(ch)
        sol, deliv, further = CORR[ch]
        html_page = build_page(ch, title or f'Travail pratique {ch}', steps, sol, deliv, further)
        name = f'tp{ch:02d}-{slug(title)}.html'
        pathlib.Path('/home/claude/corr').mkdir(exist_ok=True)
        pathlib.Path('/home/claude/corr', name).write_text(html_page)
        # lien dans la page du niveau (relatif : zip et GitHub Pages)
        p = out/LEVEL[ch]; s = p.read_text()
        if f'corrections/{name}' not in s:
            m = re.search(r'(<div class="tp"><span class="tag">Travail pratique ' + str(ch) + r'[^<]*</span>.*?)(</div>\n)', s, flags=re.S)
            s = s[:m.end(1)] + f'\n<p><strong>Correction type :</strong> <a href="corrections/{name}">solution complète, étape par étape</a>.</p>' + s[m.end(1):]
            p.write_text(s)
        n += 1
    return n
if __name__ == '__main__':
    print('pages :', write_all(range(3, 20)))
