"""Cours Data Platform / AWS / Talend / Airflow / InfraOps. Usage : python3 data_pages.py <dossier>"""
import sys, runpy, pathlib
g = runpy.run_path(pathlib.Path(__file__).with_name('front_gen.py'), run_name='front'); ch, page = g['ch'], g['page']

DATA = [
ch("Architecture d'une Data Platform et rôles", 'j',
 ["Une Data Platform collecte, stocke, transforme, sert et gouverne les données de l'entreprise ; l'équipe InfraOps/Data Platform en fournit les briques (calcul, bases, stockage, orchestration, monitoring) en libre-service aux équipes Data.", "Rôles : Data Engineer (pipelines), Data Scientist (modèles), Data Analyst (requêtes et tableaux de bord), DBA (bases), SRE/DevOps (fiabilité, automatisation), Data Platform Engineer (la plateforme elle-même), Tech Lead Talend (standards, revues, industrialisation).", "Tout passe par trois flux : ingestion (Talend, API, fichiers) → stockage (S3, PostgreSQL/Aurora, DynamoDB, Redshift) → service (Druid, Elasticsearch, BI), orchestré par Airflow et supervisé de bout en bout."],
 ["Expliquer la plateforme et qui l'utilise pour quoi", "Dessiner l'architecture de référence de la mission", "Situer chaque technologie dans un flux de données"],
 [("Architecture de référence", "", """Data Engineers / Scientists / Analysts (international : plusieurs pays, plusieurs équipes)
        │ portail self-service (demande : base, bucket, serveur, accès) → API → Terraform → AWS (validation, tags, monitoring)
        ▼
┌──────────────────────────────────────── AWS (multi-comptes, IAM, KMS, Secrets Manager, CloudTrail) ───────────────────────────────────────┐
│ INGESTION                 STOCKAGE / BASES                         SERVICE                          ORCHESTRATION       EXPLOITATION     │
│ Talend TIS (Job Server)   S3 (data lake : raw/curated/serving)     Redshift (entrepôt, BI)          Airflow (DAGs)      Prometheus/Grafana│
│  ← ERP, magasins, API     RDS / Aurora PostgreSQL (référentiels)   Druid (séries temporelles,       Talend TAC (tâches) CloudWatch        │
│  fichiers, Kafka          DynamoDB (clé-valeur, forte volumétrie)   temps réel, tableaux de bord)   CI/CD GitLab       alerting, on-call  │
│                           EC2 (Talend Job Server, Druid, ES)        Elasticsearch (recherche, logs)  Kubernetes (EKS)   MCO, support N3   │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
Flux typique : magasins → Talend (extraction nocturne) → S3 raw → Airflow (DAG) → Talend/SQL (transformation) → Redshift / PostgreSQL → Druid (agrégats) → Grafana/BI ; Elasticsearch indexe produits et logs ; DynamoDB sert le stock temps réel"""),
  ("Qui fait quoi", "Le Data Engineer écrit des jobs Talend et des DAGs et demande des ressources ; le Data Scientist lit S3/Redshift et déploie des modèles ; l'Analyst interroge Redshift/Druid ; le DBA règle PostgreSQL/Aurora et Redshift ; le Data Platform Engineer/SRE (la mission) fournit EC2/RDS/S3/Druid/ES par Terraform, exploite TAC et Job Server, supervise, fait le support N3 et l'automatisation ; le Tech Lead Talend fixe les standards, audite, revoit le code, industrialise (CI/CD).", None)],
 [("Pourquoi une plateforme plutôt que chaque équipe qui gère ses ressources ?", "Sécurité et coût (IAM, KMS, tags, budgets uniformes), fiabilité (sauvegardes, monitoring par défaut), vitesse (self-service en minutes), et savoir centralisé pour le support N3."),
  ("Question d'entretien : qu'est-ce que le support N3 ?", "Le dernier niveau : N1 accueille, N2 applique les procédures, N3 diagnostique la cause profonde, corrige (code, configuration, infrastructure) et fait évoluer les runbooks et l'automatisation pour que ça ne se reproduise pas.")],
 ("Cartographie de la plateforme", ["Redessiner l'architecture en la spécialisant (retail international : magasins, e-commerce, logistique).", "Tableau technologie → rôle → qui l'utilise → risque principal → métrique à surveiller.", "Fiche « premier jour de mission » : les 10 questions à poser à l'équipe."],
  "Les dix questions attendues : inventaire des comptes AWS et des environnements, où sont les secrets, comment un job arrive en prod, qui est d'astreinte, quels sont les SLA, où sont les runbooks, quelle est la dernière restauration testée, quels sont les incidents récurrents, quelle est la dette Talend connue, comment sont demandées les ressources.")),

ch("AWS pour la data : VPC, IAM, KMS, Secrets Manager, CloudWatch, CloudTrail", 'j',
 ["Régions et zones, VPC en trois niveaux (public, application, données), tables de routage, IGW/NAT, security groups stateful par référence, NACL stateless, endpoints S3/DynamoDB.", "IAM : rôles pour tout (EC2 instance profile, rôle de tâche, rôle de job), politiques minimales, jamais de clé statique ; KMS chiffre S3, EBS, RDS, Redshift, secrets ; Secrets Manager avec rotation.", "CloudWatch (métriques, logs, alarmes) et CloudTrail (qui a fait quoi) sont activés avant la première ressource."],
 ["Expliquer chaque brique avec son risque et sa question d'entretien", "Configurer un compte data sûr par Terraform", "Lire CloudTrail et CloudWatch pour un diagnostic"],
 [("Grille concept → risque → question", "", """| Brique          | Rôle                                  | Risque classique                              | Question d'entretien                                   |
| VPC/subnet      | isolation, trois niveaux              | base en sous-réseau public                    | pourquoi un sous-réseau « données » sans route sortante ? |
| Route table/IGW/NAT | sortie Internet contrôlée         | NAT unique (SPOF), coût NAT sur les gros flux | endpoint S3 : pourquoi ? (gratuit, pas de NAT)         |
| Security group  | pare-feu stateful par ressource       | 0.0.0.0/0 sur 5432                            | SG vs NACL ?                                          |
| IAM rôle/policy | identité et permissions               | clé d'accès dans un job Talend                | comment un job EC2 accède à S3 sans clé ? (instance profile) |
| KMS             | chiffrement par clés gérées           | clé partagée par tout, pas de politique       | chiffrement d'enveloppe ?                              |
| Secrets Manager | secrets avec rotation                 | mot de passe RDS dans un context Talend        | comment un job lit-il un secret ? (SDK, rôle, cache)   |
| CloudWatch      | métriques, logs, alarmes              | pas de rétention, pas d'alarme                | alarme sur quoi pour RDS ? (CPU, connexions, FreeStorage, ReplicaLag) |
| CloudTrail      | audit des appels API                  | désactivable, non centralisé                  | comment savoir qui a supprimé un bucket ?              |
awsc cloudtrail lookup-events --lookup-attributes AttributeKey=EventName,AttributeValue=DeleteBucket --profile data
awsc logs start-query --log-group-name /aws/rds/instance/prod/postgresql --query-string 'fields @timestamp,@message | filter @message like /deadlock/' --start-time … --end-time …""")],
 [("Un job Talend sur EC2 doit écrire dans S3 : où mettre les identifiants ?", "Nulle part : l'instance a un profil IAM (rôle) avec une politique limitée au bucket ; le SDK (tS3Connection en mode « inherit credentials from AWS role ») les obtient automatiquement et ils tournent seuls."),
  ("Question d'entretien : comment isoler les données de deux pays dans un même compte ?", "Buckets et préfixes séparés avec politiques par rôle et tags, clés KMS distinctes, bases distinctes ou schémas avec rôles PostgreSQL, et au besoin des comptes AWS distincts sous une organisation.")],
 ("Socle AWS data en Terraform", ["VPC trois niveaux, endpoints S3/DynamoDB, SG par référence ; rôles IAM pour Job Server, Airflow, Druid ; clé KMS par domaine ; Secrets Manager pour PostgreSQL avec rotation.", "CloudTrail multi-région vers un bucket verrouillé ; CloudWatch alarmes de base ; budget.", "Test : depuis l'EC2, <code>aws s3 ls</code> fonctionne par rôle ; depuis le poste, accès refusé sans SSO."],
  "Preuve : <code>aws sts get-caller-identity</code> sur l'EC2 renvoie <code>assumed-role/jobserver</code> ; CloudTrail montre l'appel ; une tentative de lecture d'un autre bucket → <code>AccessDenied</code> ; la rotation du secret change le mot de passe RDS sans intervention et le job relit la nouvelle version.")),

ch("EC2 et Linux niveau expert : déploiement propre et diagnostic", 'c',
 ["Une EC2 propre : AMI durcie (Packer), instance profile, EBS gp3 chiffré, user-data idempotent, SSM (pas de SSH ouvert), CloudWatch agent, tags, dans un ASG même à un seul membre (auto-réparation).", "Une machine lente est saturée sur une ressource : CPU (load, steal), mémoire (swap, OOM), disque (iowait, %util, latence), réseau (retransmissions, débit) ; la méthode USE puis les outils standards trouvent laquelle.", "Patching par remplacement d'image ; hardening CIS ; snapshots planifiés ; alarmes sur StatusCheckFailed, CPU, disque, mémoire (agent)."],
 ["Déployer une EC2 de production en Terraform", "Diagnostiquer une EC2 lente avec les outils Linux, en séquence", "Patcher, durcir et sauvegarder sans SSH"],
 [("EC2 en Terraform", "", """resource "aws_launch_template" "jobserver" { image_id = data.aws_ami.golden.id; instance_type = "m6g.xlarge"; iam_instance_profile { name = aws_iam_instance_profile.jobserver.name }
  metadata_options { http_tokens = "required" }   # IMDSv2 obligatoire
  block_device_mappings { device_name = "/dev/xvda"; ebs { volume_size = 100; volume_type = "gp3"; iops = 3000; throughput = 250; encrypted = true; kms_key_id = aws_kms_key.ebs.arn } }
  user_data = base64encode(templatefile("user-data.sh", { env = var.env }))   # idempotent : installe l'agent CloudWatch, monte le volume data, enregistre au TAC
  vpc_security_group_ids = [aws_security_group.jobserver.id]; tag_specifications { resource_type = "instance"; tags = local.tags } }
resource "aws_autoscaling_group" "jobserver" { min_size = 1; max_size = 1; desired_capacity = 1; vpc_zone_identifier = module.network.private_subnets; launch_template { id = aws_launch_template.jobserver.id; version = "$Latest" }; health_check_type = "EC2"; instance_refresh { strategy = "Rolling" } }"""),
  ("Diagnostic d'une machine lente", "", """uptime                      # load > nombre de vCPU ? (load = runnable + iowait)
top -o %CPU / htop          # quel processus ; %st élevé = steal (voisin bruyant, instance burstable T sans crédits)
vmstat 1 5                  # r (runnable), b (bloqués IO), si/so (swap = manque de mémoire), wa (iowait), st
free -m                     # available faible ? swap utilisé ? dmesg -T | grep -i 'killed process' (OOM killer)
iostat -xz 1 5              # %util ~100, await élevé, avgqu-sz : disque saturé → gp3 IOPS/throughput, ou requête qui scanne
df -h ; du -xsh /var/* | sort -h | tail   # disque plein : logs, tmp Talend, WAL
ss -s ; ss -tnp state established | wc -l ; sar -n DEV 1 3   # connexions, retransmissions, débit
ps -eo pid,ppid,stat,%cpu,%mem,rss,etime,cmd --sort=-%mem | head   # processus zombie (Z), gros RSS (JVM Talend)
journalctl -u talend-jobserver --since '1 hour ago' ; systemctl status ; dmesg -T | tail   # erreurs système, disque, réseau
# JVM : jcmd <pid> GC.heap_info ; jstat -gcutil <pid> 1000 5 (GC continu = heap trop petit)"""),
  ("Patch, hardening, sauvegarde", "Packer construit une AMI mensuelle (CIS : pas de root SSH, auditd, fail2ban inutile sans SSH, pare-feu, SSM agent) ; instance refresh de l'ASG remplace la machine ; SSM Patch Manager pour l'urgence ; Data Lifecycle Manager pour les snapshots EBS quotidiens (rétention 7/30 j) ; test de restauration trimestriel ; alarmes CloudWatch : StatusCheckFailed_System (recover automatique), CPUUtilization, mem_used_percent et disk_used_percent (agent), CPUCreditBalance sur T.", None)],
 [("Load average à 12 sur 4 vCPU mais CPU à 30 % : que se passe-t-il ?", "Les processus attendent l'IO (état D) : le load compte les bloqués. <code>vmstat</code> montre b et wa élevés, <code>iostat</code> un disque à 100 %. Cause fréquente : job Talend qui écrit un gros fichier temporaire sur un gp2 épuisé."),
  ("Question d'entretien : pourquoi un ASG de taille 1 ?", "Pour l'auto-réparation (health check → remplacement), l'instance refresh (patch sans intervention) et la cohérence de configuration : la machine est jetable, le state est ailleurs (EBS séparé, S3, base).")],
 ("EC2 Job Server et salle de diagnostic", ["Launch template + ASG(1) + AMI Packer + user-data qui installe l'agent et le Job Server ; SSM Session Manager ; alarmes.", "Provoquer quatre saturations (stress-ng CPU, dd sur le disque, allocation mémoire jusqu'au swap, boucle réseau) et les diagnostiquer avec la séquence de commandes.", "Instance refresh avec une nouvelle AMI ; snapshot et restauration du volume data."],
  "Chaque saturation a sa signature : CPU → load ≈ vCPU et %us ; disque → wa et %util ; mémoire → si/so puis OOM dans dmesg ; réseau → retransmissions dans <code>ss -ti</code>. Le refresh remplace l'instance en 6 min sans perdre le volume data (attaché par user-data) ; la restauration du snapshot est chronométrée (12 min) et notée dans le runbook.")),

ch("PostgreSQL de débutant à expert", 'c',
 ["Architecture : un processus par connexion (postmaster → backends), shared_buffers (cache), WAL (journal d'écriture : durabilité et réplication), checkpointer, autovacuum, background writer ; MVCC : chaque transaction voit un instantané, les anciennes versions restent jusqu'au vacuum.", "Index : B-tree (égalité, plage, tri), hash (égalité seule), GIN (tableaux, JSONB, full-text), GiST (géométrie, plages), BRIN (grosses tables ordonnées) ; un index sert quand il est sélectif et utilisé par le plan.", "Diagnostic : pg_stat_activity (qui attend quoi), pg_locks, pg_stat_statements (top requêtes), EXPLAIN ANALYZE (plan réel), pg_stat_user_tables (lignes mortes)."],
 ["Expliquer MVCC, WAL, vacuum, verrous et niveaux d'isolation", "Lire un EXPLAIN ANALYZE et corriger une requête lente", "Diagnostiquer un blocage, un deadlock, une saturation"],
 [("Architecture et réglages", "", """shared_buffers = 25 % RAM ; effective_cache_size = 75 % RAM ; work_mem par opération de tri (attention : × connexions × opérations) ; maintenance_work_mem pour vacuum/index
max_connections : petit (100–300) + pooler (PgBouncer) ; wal_level = replica/logical ; checkpoint_completion_target 0.9 ; max_wal_size selon le débit d'écriture
MVCC : UPDATE = nouvelle version de ligne + ancienne marquée ; VACUUM récupère ; VACUUM FULL réécrit (verrou exclusif) ; autovacuum par table (scale_factor 0.2 par défaut → 0.02 sur les tables chaudes)
Isolation : READ COMMITTED (défaut : chaque instruction voit les commits précédents) ; REPEATABLE READ (instantané par transaction ; erreur de sérialisation possible) ; SERIALIZABLE (comme si en série ; retries à prévoir)
Verrous : lecture ne bloque pas écriture (MVCC) ; écriture bloque écriture sur la même ligne ; DDL prend AccessExclusive (file d'attente : lock_timeout !) ; deadlock = détecté après deadlock_timeout (1 s), une transaction annulée"""),
  ("Requêtes lentes", "", """CREATE EXTENSION pg_stat_statements; SELECT calls, round(total_exec_time) AS ms, round(mean_exec_time,1) AS mean, rows, left(query,80) FROM pg_stat_statements ORDER BY total_exec_time DESC LIMIT 10;
EXPLAIN (ANALYZE, BUFFERS) SELECT * FROM ventes WHERE magasin_id = 42 AND date >= now() - interval '7 days';
-- Seq Scan on ventes (actual rows=8200 loops=1) Buffers: shared read=180000   → index manquant : CREATE INDEX CONCURRENTLY ON ventes (magasin_id, date DESC);
-- Index Scan … rows=8200 estimated=3 : statistiques fausses → ANALYZE ventes ; ALTER TABLE … ALTER COLUMN magasin_id SET STATISTICS 1000
-- Nested Loop avec 1 M de boucles : jointure mal estimée → index sur la clé de jointure, ou work_mem pour un Hash Join
-- Sort Method: external merge Disk: 250MB → work_mem trop petit pour cette requête (SET LOCAL work_mem)
SELECT pid, now()-xact_start AS age, state, wait_event_type, wait_event, left(query,60) FROM pg_stat_activity WHERE state <> 'idle' ORDER BY age DESC;   -- qui bloque / attend
SELECT blocked.pid, blocking.pid AS blocked_by, left(blocked.query,50) FROM pg_stat_activity blocked JOIN pg_stat_activity blocking ON blocking.pid = ANY(pg_blocking_pids(blocked.pid));
SELECT relname, n_live_tup, n_dead_tup, last_autovacuum FROM pg_stat_user_tables ORDER BY n_dead_tup DESC LIMIT 5;   -- bloat
SELECT pg_size_pretty(pg_wal_lsn_diff(pg_current_wal_lsn(), replay_lsn)) AS lag FROM pg_stat_replication;   -- réplication""")],
 [("Un UPDATE de masse est lent et la table grossit : pourquoi ?", "MVCC : chaque ligne modifiée devient une nouvelle version ; les anciennes attendent le vacuum. Faire par lots, laisser autovacuum passer (ou VACUUM manuel), éviter VACUUM FULL en production (verrou)."),
  ("Question d'entretien : différence entre REPEATABLE READ et SERIALIZABLE ?", "RR garantit un instantané stable mais permet des anomalies d'écriture (write skew) ; SERIALIZABLE les détecte et annule une transaction (à réessayer). Le défaut READ COMMITTED suffit à la plupart des traitements.")],
 ("Laboratoire PostgreSQL", ["PostgreSQL 16 en Docker avec 5 M de lignes de ventes ; pg_stat_statements ; cinq requêtes lentes à corriger par EXPLAIN (index, statistiques, work_mem, jointure, partition).", "Provoquer un blocage (transaction ouverte + DDL) et un deadlock ; les lire dans pg_stat_activity/pg_locks ; corriger avec lock_timeout.", "Réplication streaming vers un second conteneur, mesure du lag, bascule manuelle (pg_ctl promote)."],
  "Chaque correction est mesurée : 2 400 ms → 12 ms avec l'index composite ; le deadlock apparaît dans les logs avec les deux requêtes ; le DDL bloqué derrière la transaction longue bloque aussi les SELECT (file d'attente), ce qui justifie <code>lock_timeout = '2s'</code> dans les migrations ; le lag de réplication passe à 0 après un checkpoint.")),

ch("RDS et Aurora PostgreSQL : exploiter en production", 'c',
 ["RDS : PostgreSQL géré (patch, sauvegardes, Multi-AZ synchrone, réplicas asynchrones, Performance Insights) ; on garde schéma, requêtes, paramètres (Parameter Groups) ; pas d'accès OS ni de superuser.", "Aurora : stockage réparti sur 3 AZ (6 copies), writer + readers partageant le stockage, bascule en ~30 s, endpoints (cluster/writer, reader, custom), réplicas presque sans lag, Serverless v2 pour les charges variables.", "Diagnostic : Performance Insights (attentes par requête), Enhanced Monitoring (OS), CloudWatch (CPU, connexions, FreeableMemory, ReadIOPS, ReplicaLag, AuroraReplicaLag), logs PostgreSQL exportés."],
 ["Choisir EC2 PostgreSQL, RDS ou Aurora et le justifier", "Configurer Parameter Groups, sauvegardes, Multi-AZ, réplicas, Performance Insights", "Diagnostiquer et résoudre les incidents RDS/Aurora courants"],
 [("Comparaison et configuration", "", """| Critère            | PostgreSQL sur EC2               | RDS PostgreSQL                        | Aurora PostgreSQL                                |
| exploitation       | tout à faire (patch, backup, HA)  | gérée                                 | gérée                                            |
| HA                 | à construire (Patroni)           | Multi-AZ synchrone, bascule ~60 s     | stockage 6 copies, bascule ~30 s, readers promus |
| lecture            | réplicas à gérer                 | read replicas (lag asynchrone)        | jusqu'à 15 readers, lag ms, endpoint reader      |
| performance        | selon le tuning                  | proche de PG                          | 2–3× en écriture intensive (stockage distribué)  |
| coût               | instance + travail humain        | +30–50 % vs EC2                       | +20 % vs RDS + IO (ou I/O-Optimized)             |
| extensions/superuser | tout                           | liste supportée, rds_superuser        | idem                                             |
resource "aws_db_parameter_group" "pg16" { family = "postgres16"; parameter { name = "shared_preload_libraries"; value = "pg_stat_statements,auto_explain"; apply_method = "pending-reboot" }; parameter { name = "log_min_duration_statement"; value = "500" }; parameter { name = "auto_explain.log_min_duration"; value = "1000" } }
resource "aws_rds_cluster" "aurora" { engine = "aurora-postgresql"; engine_version = "16.4"; storage_encrypted = true; backup_retention_period = 14; deletion_protection = true; enabled_cloudwatch_logs_exports = ["postgresql"]; serverlessv2_scaling_configuration { min_capacity = 2; max_capacity = 16 } }
resource "aws_rds_cluster_instance" "w" { count = 2; cluster_identifier = aws_rds_cluster.aurora.id; instance_class = "db.serverless"; performance_insights_enabled = true; monitoring_interval = 60 }"""),
  ("Incidents et troubleshooting", "", """| Symptôme                              | Investigation                                              | Cause probable / résolution                                          |
| CPU 100 %, requêtes lentes            | Performance Insights top SQL, attente CPU                  | requête sans index, plan changé (ANALYZE), statistique ; index / réécriture |
| connexions max atteintes              | DatabaseConnections, pg_stat_activity                      | pool mal dimensionné, connexions idle in transaction ; PgBouncer/RDS Proxy, idle_in_transaction_session_timeout |
| FreeStorageSpace en baisse            | taille des tables, WAL, logs                               | bloat, réplica en retard qui retient le WAL, logs verbeux ; vacuum, storage autoscaling |
| ReplicaLag croissant                  | AuroraReplicaLag, charge du writer                         | transactions longues, readers sous-dimensionnés ; endpoint reader, taille |
| bascule Multi-AZ/Aurora               | events RDS, DNS TTL                                        | l'application garde l'ancienne IP : TTL DNS court, pool qui valide les connexions, retries |
| IO élevé / coût Aurora IO             | VolumeReadIOPs, BufferCacheHitRatio < 99 %                 | cache trop petit pour le working set : instance plus grosse ou I/O-Optimized |
| Serverless v2 qui ne descend pas      | ACUUtilization, connexions                                 | connexions persistantes et jobs continus empêchent le scale-down     |
awsc rds describe-events --source-identifier prod --duration 1440 ; awsc rds failover-db-cluster --db-cluster-identifier prod   # test de bascule""")],
 [("Après une bascule Aurora, l'application ne se reconnecte pas : pourquoi ?", "Le pool a gardé des connexions vers l'ancien writer (désormais reader : erreurs « read-only transaction ») ou le cache DNS. Remède : endpoint cluster, TTL bas, validation des connexions dans le pool, retries, ou RDS Proxy qui absorbe la bascule."),
  ("Question d'entretien : Multi-AZ RDS contre réplica de lecture ?", "Multi-AZ = disponibilité (réplique synchrone invisible, bascule automatique) ; réplica = performance de lecture (asynchrone, lisible, promotion manuelle). Aurora fusionne les deux via son stockage partagé.")],
 ("RDS et Aurora en pratique", ["RDS PostgreSQL Multi-AZ et cluster Aurora Serverless v2 en Terraform, Parameter Groups, logs exportés, Performance Insights.", "Bascule forcée des deux, chronométrée avec une boucle d'écriture ; comparaison du comportement du pool Hikari avec et sans validation.", "Restauration PITR dans un cluster de test et vérification d'une ligne témoin ; destruction des ressources (coût mesuré)."],
  "Mesures attendues : RDS Multi-AZ 55–70 s d'indisponibilité, Aurora 20–35 s ; sans validation du pool, 2 minutes d'erreurs « cannot execute INSERT in a read-only transaction » après la bascule Aurora ; PITR restaurée à la seconde demandée ; coût du labo ≈ 2 € pour 3 h.")),

ch("DynamoDB, S3 et Redshift : les briques de stockage AWS", 'c',
 ["DynamoDB : table = partitions déterminées par la clé de partition ; le débit (RCU/WCU) se répartit par partition, donc une mauvaise clé (peu de valeurs, valeur chaude) provoque du throttling quelle que soit la capacité ; GSI (autre clé, éventuellement cohérent) et LSI (même partition, autre tri, à la création) ; TTL, Streams, on-demand ou provisionné.", "S3 : buckets privés, chiffrés (KMS), versionnés, cycle de vie vers Intelligent-Tiering/Glacier, politiques par rôle, jamais d'ACL, réplication et Object Lock pour les sauvegardes ; préfixes pour le débit et pour la structure du data lake (raw/curated/serving).", "Redshift : entrepôt colonnaire MPP (leader + nœuds de calcul, tranches) ; distribution (KEY/EVEN/ALL/AUTO) et clés de tri décident des performances ; compression automatique ; Spectrum interroge S3 ; WLM/queues pour partager les ressources."],
 ["Modéliser une table DynamoDB par accès et éviter la partition chaude", "Sécuriser S3 et organiser un data lake", "Concevoir les tables Redshift et comparer Redshift, PostgreSQL et Athena"],
 [("DynamoDB", "", """Table stock : PK = sku#magasin (haute cardinalité, accès uniforme) ; SK = date (tri) ; GSI1 : PK = magasin, SK = date (tous les stocks d'un magasin) ; attributs projetés = ceux lus par la requête
mauvaise clé : PK = pays (5 valeurs) → toutes les écritures de la France sur une partition → ProvisionedThroughputExceededException même à 10 000 WCU
awsc dynamodb query --table-name stock --key-condition-expression 'pk = :p AND sk BETWEEN :a AND :b' --expression-attribute-values '{":p":{"S":"SKU42#FR-001"},":a":{"S":"2026-09-01"},":b":{"S":"2026-09-30"}}'
métriques : ConsumedRead/WriteCapacityUnits vs Provisioned, ThrottledRequests, SuccessfulRequestLatency ; CloudWatch Contributor Insights pour trouver la clé chaude
coûts : on-demand pour l'imprévisible (×5 plus cher à débit constant), provisionné + autoscaling pour le régulier ; TTL gratuit pour purger ; Streams → Lambda pour propager vers Elasticsearch"""),
  ("S3 et data lake", "", """s3://dl-raw-eu/  source=erp/year=2026/month=09/day=22/ventes.parquet   → immuable, rétention 2 ans, Intelligent-Tiering
s3://dl-curated-eu/ domaine=ventes/…                                     → nettoyé, schéma stable, Parquet partitionné
s3://dl-serving-eu/                                                       → agrégats pour Redshift Spectrum / Druid
erreurs classiques : bucket public (Block Public Access désactivé), ACL au lieu de politiques, pas de chiffrement, pas de versioning sur le raw, listing par un rôle trop large, clés d'accès dans Talend, pas de cycle de vie (coût), petits fichiers par milliers (performances Spectrum/Athena)
politique : { "Effect": "Deny", "Principal": "*", "Action": "s3:*", "Resource": "arn:aws:s3:::dl-raw-eu/*", "Condition": { "Bool": { "aws:SecureTransport": "false" } } }   # + accès par rôle uniquement, condition sur aws:PrincipalOrgID"""),
  ("Redshift", "", """CREATE TABLE ventes (id BIGINT, magasin_id INT, sku VARCHAR(32), date DATE, montant DECIMAL(12,2)) DISTKEY(magasin_id) SORTKEY(date);   -- DISTKEY sur la clé de jointure la plus fréquente, SORTKEY sur le filtre temporel ; petites dimensions en DISTSTYLE ALL
COPY ventes FROM 's3://dl-curated-eu/domaine=ventes/' IAM_ROLE 'arn:…' FORMAT AS PARQUET;   -- jamais d'INSERT ligne à ligne
SELECT query, elapsed, left(querytxt,60) FROM svl_qlog ORDER BY elapsed DESC LIMIT 10 ; SELECT * FROM svv_table_info WHERE skew_rows > 2 OR unsorted > 20;   -- déséquilibre, tri
VACUUM ventes ; ANALYZE ventes ; -- WLM : file « etl » 40 %, « bi » 60 %, concurrency scaling pour les pics
| Besoin                       | Redshift                     | PostgreSQL                   | Athena                        |
| analytique sur des To        | oui (MPP, colonnaire)        | non (au-delà de ~1 To)       | oui, sans serveur, par requête|
| transactions OLTP            | non                          | oui                          | non                           |
| coût                         | cluster à l'heure / serverless | instance                   | 5 $/To scanné                  |
| données dans S3              | Spectrum                     | non                          | natif                          |""")],
 [("Une table DynamoDB de commandes avec PK = date du jour : problème ?", "Toutes les commandes du jour tombent sur une partition : throttling garanti aux heures de pointe. Clé = identifiant de commande ou client#date, avec un GSI par date si on doit lister par jour (et le savoir chaud : sharding de la clé, date#suffixe)."),
  ("Question d'entretien : pourquoi Parquet plutôt que CSV dans le lake ?", "Colonnaire, compressé, typé, avec statistiques : Redshift Spectrum et Athena ne lisent que les colonnes et blocs nécessaires : 10 à 100× moins de données scannées, donc plus rapide et moins cher.")],
 ("Stockage de la plateforme", ["Table DynamoDB stock avec bonne et mauvaise clé : test de charge et lecture des métriques de throttling ; TTL et Stream vers une Lambda.", "Data lake S3 en trois zones avec politiques, chiffrement, versioning, cycle de vie ; conversion CSV → Parquet et comparaison des coûts Athena.", "Redshift Serverless : tables avec DISTKEY/SORTKEY, COPY depuis Parquet, comparaison de deux plans, WLM."],
  "Preuve : la mauvaise clé plafonne à ~1 000 WCU effectifs avec ThrottledRequests > 0 quand la bonne absorbe 10 000 ; Athena scanne 1,2 Go en CSV contre 90 Mo en Parquet pour la même requête ; Redshift : la requête avec DISTKEY sur la jointure passe de 40 s à 4 s (plus de redistribution DS_BCAST).")),

ch("Apache Druid et Elasticsearch : servir les données", 's',
 ["Druid : base analytique temps réel pour les séries temporelles et tableaux de bord (agrégations sub-seconde sur des milliards de lignes) ; ingestion batch (S3) et streaming (Kafka) en segments immuables stockés en deep storage (S3) et chargés par les Historicals ; les Brokers routent et fusionnent, Coordinator gère les segments, Overlord/MiddleManagers ingèrent, metadata store PostgreSQL, ZooKeeper (ou sans).", "Elasticsearch : cluster de nœuds (master, data, coordinating, ingest), index découpé en shards primaires et répliques, index inversé, mapping ; la santé (green/yellow/red) dépend de l'allocation des shards ; le heap JVM (≤ 31 Go, 50 % RAM) et le disque (watermarks) sont les limites.", "Les deux se diagnostiquent par leurs API (Druid SQL sys tables, ES _cat/_cluster) et se dimensionnent par le nombre et la taille des segments/shards."],
 ["Expliquer l'architecture Druid et pourquoi il est dans une Data Platform", "Exploiter un cluster Elasticsearch : santé, allocation, heap, shards, reindex, snapshots", "Diagnostiquer les incidents courants des deux"],
 [("Druid", "", """                    requêtes SQL/JSON (Grafana, API)
                              │
                          Broker ×2  (routage, fusion, cache)        Router (UI, proxy)
                    ┌─────────┴─────────┐
              Historical ×N        MiddleManager / Indexer ×N  ←── Overlord (tâches d'ingestion) ; Kafka (temps réel) ; batch depuis S3 (index_parallel)
              (segments chargés     (segments en cours, poussés
               depuis le deep       vers le deep storage)
               storage, cache local)
                    │                       │
              Deep storage S3 (segments immuables, source de vérité) ─── Coordinator (chargement, équilibrage, rétention, compaction) ─── Metadata store PostgreSQL ─── ZooKeeper
Pourquoi Druid : agrégations temps réel (ventes par magasin par minute), rollup à l'ingestion, partition temporelle, colonnaire + bitmap, scaling horizontal par rôle
Ingestion : spec JSON (dataSource, timestampSpec, dimensionsSpec, metricsSpec avec rollup, granularitySpec segmentGranularity DAY / queryGranularity MINUTE)
Exploitation : segments trop petits (compaction automatique), historicals pleins (tiering, rétention), broker OOM (limites de requête), lag Kafka (plus de tâches), metadata store saturé ; SELECT * FROM sys.segments WHERE is_available = 0 ; sys.tasks WHERE status = 'FAILED'"""),
  ("Elasticsearch", "", """curl -s localhost:9200/_cluster/health?pretty ; curl -s 'localhost:9200/_cat/nodes?v&h=name,heap.percent,ram.percent,cpu,disk.used_percent,node.role'
curl -s 'localhost:9200/_cat/indices?v&s=store.size:desc' ; curl -s 'localhost:9200/_cat/shards?v&h=index,shard,prirep,state,unassigned.reason' | grep -v STARTED
curl -s localhost:9200/_cluster/allocation/explain?pretty            # POURQUOI un shard n'est pas alloué
yellow : répliques non allouées (un seul nœud, disque, filtre) → ajouter un nœud ou number_of_replicas: 0 en dev
red    : primaire manquant (nœud perdu, disque plein) → récupérer le nœud, restaurer depuis snapshot, ou allocate_stale_primary en dernier recours
high heap / GC longs : trop de shards (> 20 par Go de heap), fielddata, requêtes d'agrégation lourdes → shrink/rollover, ILM, circuit breakers, heap ≤ 31 Go
high CPU : requêtes wildcard/regex, refresh_interval 1 s sur ingestion massive → refresh 30 s pendant le bulk, requêtes revues
disk watermark : low 85 % (plus de nouveaux shards), high 90 % (déplacement), flood 95 % (index en lecture seule) → supprimer/ILM, agrandir, index.blocks.read_only_allow_delete: null
shard explosion : un index par jour × 5 shards × 3 répliques × 365 → ILM (rollover par taille 30–50 Go, forcemerge, delete)
reindex : POST _reindex { source, dest } avec alias pour basculer sans coupure ; snapshot : repository S3, SLM quotidien, restauration testée""")],
 [("Cluster Elasticsearch yellow depuis une semaine : grave ?", "Pas d'indisponibilité, mais aucune redondance : la perte d'un nœud passe au rouge (données inaccessibles). Trouver la cause (<code>allocation/explain</code>), souvent disque ou nombre de nœuds insuffisant."),
  ("Question d'entretien : Druid ou Elasticsearch pour un tableau de bord de ventes en temps réel ?", "Druid : agrégations temporelles, rollup, coût de stockage bas, latence sub-seconde sur des milliards de lignes. Elasticsearch excelle en recherche texte et exploration de documents, moins en agrégations massives.")],
 ("Druid et Elasticsearch en Docker", ["Cluster Druid (compose officiel) : ingestion batch de ventes depuis un S3 local (MinIO), requêtes SQL, compaction ; kill d'un Historical et observation de la réallocation.", "Cluster ES 3 nœuds : index avec ILM et alias, bulk de 1 M de documents, provoquer yellow (arrêt d'un nœud), red (perte de données d'un nœud sans réplique), watermark (petit disque) ; diagnostiquer et corriger chacun.", "Snapshot ES vers MinIO et restauration ; export Grafana des deux."],
  "Druid : après le kill, <code>sys.segments</code> montre les segments rechargés sur l'autre Historical depuis le deep storage en < 1 min. ES : yellow → green en remettant le nœud ; red réparé par restauration du snapshot ; watermark flood → index en lecture seule, corrigé par suppression d'index et <code>read_only_allow_delete: null</code>.")),

ch("Talend niveau débutant : Studio, jobs, composants", 'j',
 ["Talend Studio (Eclipse) : projet, repository (métadonnées de connexions, schémas, contextes), job = graphe de composants reliés par des flux (Main, Iterate, OnSubjobOk/Error, RunIf) ; un job compile en Java.", "Les composants clés : tFileInputDelimited / tFileOutputDelimited (fichiers), tDBInput / tDBOutput / tDBRow (bases), tMap (jointures, transformations, rejets), tRESTClient (API), tJava/tJavaRow (code), tRunJob (sous-job), tLogCatcher / tDie / tWarn (erreurs), tS3Put/Get, tContextLoad.", "Un job propre : contextes par environnement, schémas dans le repository, gestion des rejets, journalisation, sans mot de passe en dur, sans logique en tJava quand un composant existe."],
 ["Construire quatre jobs : CSV → PostgreSQL, PostgreSQL → S3, API → PostgreSQL, S3 → transformation → base", "Utiliser tMap (jointure, expressions, rejets) et les liens d'orchestration", "Externaliser la configuration en contextes et métadonnées"],
 [("Le job CSV → PostgreSQL", "", """tFileInputDelimited (ventes.csv, schéma repository VENTES, séparateur ;, header 1, encodage UTF-8, die on error : off, rejets → tFileOutputDelimited rejets_format.csv)
   │ Main
tMap  (lookup : tDBInput magasins → jointure sur code_magasin, « Inner join » ; expressions : montant = row1.prix * row1.qte ; date = TalendDate.parseDate("yyyy-MM-dd", row1.date) ; sortie « rejets » : lignes sans magasin → tFileOutputDelimited rejets_referentiel.csv)
   │ out1
tDBOutput (PostgreSQL, connexion repository, table ventes, action Insert or update sur (id), batch 1000, commit 10000, use existing connection tDBConnection)
tDBConnection (début) ─ OnSubjobOk → job ─ OnSubjobOk → tDBCommit ; OnSubjobError → tDBRollback → tDie
tLogCatcher → tFileOutputDelimited logs/${context.env}_ventes.log  (Java exceptions, tDie, tWarn)
context : env, db_host, db_port, db_name, db_user, db_password (type Password), s3_bucket, input_dir — chargé par tContextLoad depuis un fichier ou passé par le TAC/Job Server ; jamais de valeur de prod dans le Studio
Autres jobs : PostgreSQL → S3 : tDBInput → tFileOutputDelimited (fichier temporaire) → tS3Put (rôle IAM, pas de clé) ; API → PostgreSQL : tRESTClient (GET, pagination par tLoop/tIterate, header Authorization depuis context) → tExtractJSONFields → tMap → tDBOutput ; S3 → base : tS3Get → tFileInputDelimited → tMap (nettoyage, typage) → tDBOutput, avec tFileDelete du temporaire en OnSubjobOk"""),
  ("Liens et erreurs", "Main transporte des lignes ; Iterate rejoue le sous-job par élément (fichiers d'un dossier) ; OnSubjobOk/OnSubjobError orchestrent après la fin du sous-job entier ; OnComponentOk après un composant ; RunIf sur condition. Erreurs : <code>tLogCatcher</code> capte, <code>tDie</code> arrête avec un code de retour (visible du TAC/Airflow), <code>tWarn</code> signale ; les rejets métier sortent par les flux « reject » de tMap et des composants d'entrée, pas par une exception.", None)],
 [("Pourquoi mettre le tDBConnection et le commit hors du sous-job de traitement ?", "Pour avoir une transaction unique (rollback complet en cas d'erreur) et réutiliser la connexion entre composants (pas une connexion par tDBOutput)."),
  ("Question d'entretien : à quoi sert le repository de métadonnées ?", "À définir une fois connexions et schémas et les réutiliser dans tous les jobs : un changement de schéma se propage, un mot de passe n'est jamais saisi dans un composant.")],
 ("Quatre jobs de la mission", ["Studio dans une VM ou conteneur Windows/Linux (Talend Open Studio pour s'exercer) ; PostgreSQL et MinIO (S3) en Docker.", "Les quatre jobs avec contextes DEV/PROD, schémas repository, rejets, journalisation, tDie avec code de retour.", "Export du job (ZIP autonome) et exécution en ligne de commande depuis un conteneur Java : <code>./ventes_run.sh --context=PROD --context_param db_password=…</code>."],
  "Preuve : le job exporté s'exécute dans <code>eclipse-temurin:17</code> avec le contexte PROD sans modification ; un fichier avec deux lignes cassées produit deux lignes de rejet et un code de retour 0 ; un mot de passe faux produit un tDie code 4 et la ligne dans le log ; aucune valeur de production dans les fichiers du projet (grep).")),

ch("Talend niveau avancé, revue de code et audit Tech Lead", 's',
 ["Orchestration : job parent (tRunJob avec transmission de contexte et « die on child error »), enfants unitaires et réutilisables, tParallelize/multi-thread pour les sous-jobs indépendants ; retries par tLoop + RunIf ; journalisation structurée (tLogRow JSON, tStatCatcher vers une table de suivi).", "Performance : lecture par flux (pas de tHashOutput inutile), tMap en lookup « Load once » ou « Reload at each row » selon la taille, batch/commit, tDBBulkExec pour les gros volumes, tri en base plutôt qu'en tSortRow, JVM -Xmx adaptée (paramètres avancés du job), pas de tJava qui accumule en mémoire.", "Un Tech Lead audite architecture, code, performances, sécurité, journalisation, erreurs, contextes, secrets, Git, CI/CD, tests, documentation, monitoring, avec pour chaque constat symptôme → cause → solution."],
 ["Structurer une chaîne de jobs parent/enfants robuste avec retries et logs", "Reconnaître un mauvais job, un job moyen, un job propre", "Dérouler la checklist d'audit et écrire un rapport"],
 [("Trois jobs", "", """MAUVAIS : un seul job de 80 composants ; mot de passe PostgreSQL en dur dans tDBOutput ; tJava qui charge toute la table dans une HashMap statique ; pas de tLogCatcher ; commit à chaque ligne ; contexte DEV utilisé en prod avec des valeurs modifiées à la main ; pas de rejet (die on error partout) ; nom « Copy_of_job2_final ».
MOYEN : contextes par environnement mais mot de passe dans le fichier de contexte commité ; tLogCatcher vers un fichier local jamais lu ; jointure tMap en « Reload at each row » sur une table de 5 M de lignes (lent) ; pas de retry ; sous-jobs mais transmission de contexte oubliée (valeurs par défaut en prod !).
PROPRE : job parent d'orchestration (tPrejob/tPostjob, tRunJob ×3 avec « Transmit whole context », OnSubjobError → tDie code) ; enfants unitaires nommés par convention (DOMAINE_Action_Source_Cible) ; secrets chargés depuis Secrets Manager (tSystem + jq ou composant custom) au démarrage, jamais dans Git ; tLogCatcher + tStatCatcher → table run_log (job, début, fin, lignes, rejets, code) lue par Grafana ; batch 5 000 / commit 50 000 ; lookups « Load once » avec filtres SQL ; rejets métier fichiers datés en S3 ; retry ×3 avec backoff sur l'API ; documentation dans le job (notes) et README ; tests : jeu de données de référence + job de comparaison"""),
  ("Checklist d'audit (extrait)", "", """| Domaine       | Symptôme                                     | Cause                                   | Solution                                                      |
| architecture  | jobs géants, copier-coller                   | pas de découpage ni de convention       | parent/enfants, jobs génériques paramétrés, conventions       |
| code          | tJava partout, logique dupliquée            | méconnaissance des composants            | revue, routines partagées, composants standards                |
| performances  | job de 4 h, JVM OOM                          | lookups rechargés, tri en mémoire, commit ligne | Load once, tri SQL, batch, bulk, -Xmx, parallélisme     |
| sécurité      | mots de passe dans Git/contexte              | pas de gestionnaire de secrets           | Secrets Manager/Vault au démarrage, rôle IAM, contextes sans secret |
| erreurs       | job vert avec 30 % de rejets silencieux      | rejets non comptés, pas de seuil         | table run_log, seuil de rejets → tDie, alerte                  |
| logging       | logs locaux non centralisés                  | pas de sortie standard                   | logs JSON → CloudWatch/Loki, corrélation run_id                |
| contextes     | valeurs prod dans le Studio                  | contextes non externalisés               | tContextLoad, TAC/Airflow injecte, revue des fichiers          |
| Git           | pas de branche, commits « fix »              | pas de workflow                          | feature branches, MR, revue, Conventional Commits              |
| CI/CD         | build manuel depuis le Studio                | pas de CommandLine/Maven                 | pipeline GitLab (chapitre suivant)                             |
| tests         | aucun                                        | « ETL ne se teste pas »                  | jeux de référence, job de comparaison, tests d'intégration en CI |
| monitoring    | on découvre l'échec le lendemain             | pas d'alerte sur le code de retour        | TAC/Airflow → alerte, dashboard run_log, SLA par flux         |""")],
 [("Un job passe de 20 min à 3 h après la croissance d'une table : premier suspect ?", "Un lookup tMap « Reload at each row » ou sans filtre (chargement complet en mémoire), ou un commit ligne à ligne. Vérifier le plan (Load once + filtre SQL, index côté base, batch) et le -Xmx."),
  ("Question d'entretien : que vérifies-tu en revue d'un job Talend ?", "Nom et découpage, contextes et absence de secrets, gestion des erreurs et rejets avec seuil, journalisation vers run_log, performances des lookups et commits, idempotence (rejouable), documentation, et que le job est buildable par la CI sans le Studio.")],
 ("Audit d'un projet Talend", ["Reprendre les quatre jobs du chapitre précédent, en créer une version « mauvaise » et une « propre », mesurer (durée, mémoire, rejets).", "Remplir la checklist d'audit sur un projet d'exemple (fourni ou le tien) avec 12 constats symptôme → cause → solution priorisés.", "Rapport d'audit de 4 pages avec plan à 30/90 jours et revue de code écrite d'un job."],
  "Mesure typique : mauvais job 42 min / 3 Go de heap ; propre 6 min / 1 Go, rejets comptés dans run_log ; le rapport priorise secrets (immédiat), erreurs silencieuses (30 j), industrialisation (90 j).")),

ch("Talend TIS on-premise : TAC, Job Server, CI/CD", 's',
 ["Chaîne : Studio (développeur, Git) → dépôt Git → build Maven (CommandLine/CI builder) → artefact (ZIP) dans Nexus → TAC (tâche : artefact + contexte + serveur + planning) → Job Server (exécution, logs) → production ; la base TAC (PostgreSQL/MySQL) stocke utilisateurs, projets, tâches, exécutions.", "TAC administre : utilisateurs et rôles, projets et branches, serveurs (Job Servers, agents), tâches et déclencheurs (cron, fichier, événement), exécutions et historique, monitoring (Activity Monitoring Console), licences ; Job Server : agent Java sur EC2, ports (8000 commande, 8001 fichiers, 8888 monitoring), JVM, répertoires (jobs déployés, logs), sécurité (SSL, utilisateurs).", "CI/CD : Git → Maven (Talend CI Builder, plugin <code>org.talend.ci:builder-maven-plugin</code>) → tests → Sonar → artefact Nexus → déploiement par API TAC (metaServlet) → Job Server."],
 ["Expliquer et dessiner la chaîne complète et le rôle de chaque brique", "Administrer TAC et exploiter un Job Server (configuration, JVM, logs, troubleshooting)", "Écrire le pipeline GitLab CI d'industrialisation"],
 [("Architecture et chemin d'un job", "", """Développeur (Studio + Git)                                     Exploitation
   │ commit / MR                                                  │
   ▼                                                              ▼
Git (GitLab) ──► GitLab CI : mvn -f <projet>/poms/pom.xml -Pci … ──► Nexus (artefacts ZIP, snapshots/releases)
                                                                    │
                                                            TAC (Tomcat, base TAC) : Job Conductor : tâche = artefact Nexus + version + contexte + Job Server + trigger
                                                                    │ déploie / lance (API metaServlet : associatePreGeneratedJob, runTask)
                                                            Job Server(s) (EC2, agent org.talend.remote.jobserver) : exécute la JVM du job, remonte statut et logs (AMC)
                                                                    │
                                                            Production : PostgreSQL, S3, Redshift… ; logs → CloudWatch/ELK ; run_log → Grafana
Job Server : /opt/talend/jobserver/conf/TalendJobServer.properties (ports, users, JVM, jobs dir, log dir) ; org.talend.remote.jobserver.server.TalendJobServer.COMMAND_SERVER_PORT=8000 ; FILE_SERVER_PORT=8001 ; MONITORING_PORT=8888 ; MAX_CONCURRENT_JOBS ; JVM_OPTIONS -Xmx par job dans le TAC (paramètres de tâche)
troubleshooting : TAC « server unreachable » → SG/ports 8000-8001-8888, service, version agent ≠ TAC ; job « bloqué en Running » → JVM zombie (ps, kill), disque plein ; « deployment failed » → Nexus, espace, droits ; logs : jobserver/logs/, jobs/<tache>/log/ ; statistiques AMC ; sécurité : SSL TAC↔JobServer, utilisateurs Job Server, pas de root, SG restreint au TAC"""),
  ("GitLab CI", "", """stages: [build, test, quality, publish, deploy]
variables: { TALEND_VERSION: "8.0.1", MAVEN_OPTS: "-Dmaven.repo.local=.m2" }
cache: { key: talend, paths: [.m2/] }
build:
  stage: build
  image: registry.interne/talend-ci-builder:8.0.1          # image maison : JDK 17 + Maven + CI Builder + licence (secret) ; construite depuis le Studio, jamais Docker Hub
  script: [mvn -f poms/pom.xml clean package -Pci -Dlicense.path=$TALEND_LICENSE -Dupdatesite.path=$UPDATE_SITE -Dproduct.path=$STUDIO_PATH -DskipTests]
  artifacts: { paths: ["poms/jobs/**/target/*.zip"] }
test: { stage: test, image: eclipse-temurin:17, services: [postgres:16], script: [./tests/run.sh] }   # exécute les ZIP contre une base de test et compare aux résultats attendus
quality: { stage: quality, image: sonarsource/sonar-scanner-cli, script: [sonar-scanner -Dsonar.projectKey=talend -Dsonar.sources=.] }   # + règles maison : grep des secrets, contextes, tDie manquants
publish: { stage: publish, script: [mvn -f poms/pom.xml deploy -Pci -DskipTests -DaltDeploymentRepository=nexus::default::$NEXUS_URL/repository/talend-releases], rules: [{ if: $CI_COMMIT_TAG }] }
deploy_prod:
  stage: deploy
  when: manual
  script:
    - 'curl -s "$TAC_URL/metaServlet?$(echo "{\"actionName\":\"associatePreGeneratedJob\",\"authUser\":\"$TAC_USER\",\"authPass\":\"$TAC_PASS\",\"taskName\":\"VENTES_Load\",\"filePath\":\"$NEXUS_URL/…/VENTES_Load-$CI_COMMIT_TAG.zip\",\"contextName\":\"PROD\",\"executionServerName\":\"jobserver-prod-1\"}" | base64 -w0)"'
    - 'curl -s "$TAC_URL/metaServlet?$(echo "{\"actionName\":\"runTask\",\"authUser\":…,\"taskId\":42,\"mode\":\"synchronous\"}" | base64 -w0)"'   # exécution de vérification""")],
 [("Le TAC affiche un Job Server « unreachable » alors que la machine répond au ping : que vérifier ?", "Les ports 8000/8001/8888 depuis le TAC (security group), le service jobserver (<code>systemctl</code>), la correspondance de version agent/TAC, les logs de l'agent, et l'horloge (SSL)."),
  ("Question d'entretien : pourquoi ne plus déployer depuis le Studio ?", "Traçabilité (quel commit est en prod), reproductibilité (build identique), tests et qualité avant publication, et suppression des droits de production sur les postes : la chaîne Git → CI → Nexus → TAC est auditée.")],
 ("Chaîne TIS en laboratoire", ["Schéma complet de la chaîne et fiche d'administration TAC (utilisateurs, projets, serveurs, tâches, déclencheurs, AMC).", "Job Server sur une EC2 (ou conteneur) : configuration, ports, JVM, logs ; trois pannes simulées (port bloqué, disque plein, JVM zombie) et leur résolution.", "Pipeline GitLab complet (build CI Builder, test, Sonar, Nexus, déploiement TAC par API, exécution de vérification) sur un projet d'exemple ; si pas de licence TIS : la partie build avec Talend Open Studio + export de ZIP scripté, le reste identique."],
  "Preuve : un tag Git produit un ZIP versionné dans Nexus ; la tâche TAC pointe sur cette version ; l'exécution de vérification renvoie le code 0 et une ligne dans run_log avec le numéro de version ; les trois pannes sont résolues avec les commandes de la fiche en < 10 min.")),

ch("Airflow : orchestrer les pipelines et les jobs Talend", 'c',
 ["Airflow : DAG (Python) de tâches (opérateurs) planifiées par le Scheduler, exécutées par un Executor (Local, Celery, Kubernetes) via des Workers, suivies par le Webserver ; métadonnées en PostgreSQL ; XCom pour de petites données entre tâches, Variables et Connections (secrets via backend Secrets Manager), Pools pour limiter la concurrence.", "Un bon DAG : idempotent (rejouable par <code>data_interval</code>), sans traitement lourd dans le scheduler (l'opérateur lance ailleurs), retries avec backoff, SLA et alertes, dépendances explicites, pas de code au niveau module coûteux.", "Talend + Airflow : Airflow lance le job Talend (BashOperator sur le ZIP exporté, SSHOperator vers le Job Server, ou appel API TAC), attend le code de retour, enchaîne validation, chargement Redshift, notification."],
 ["Écrire un DAG ETL complet avec retries, validation et notification", "Configurer connections, variables, pools, secrets, et choisir l'executor", "Orchestrer des jobs Talend depuis Airflow"],
 [("DAG ETL avec Talend", "", """from airflow import DAG; from airflow.operators.bash import BashOperator; from airflow.providers.ssh.operators.ssh import SSHOperator; from airflow.providers.postgres.operators.postgres import PostgresOperator; from airflow.providers.amazon.aws.transfers.s3_to_redshift import S3ToRedshiftOperator; from airflow.operators.python import PythonOperator; from airflow.utils.trigger_rule import TriggerRule; from datetime import datetime, timedelta
default_args = { "owner": "data-platform", "retries": 3, "retry_delay": timedelta(minutes=5), "retry_exponential_backoff": True, "email_on_failure": False, "sla": timedelta(hours=2) }
with DAG("ventes_quotidien", start_date=datetime(2026, 9, 1), schedule="0 3 * * *", catchup=False, max_active_runs=1, default_args=default_args, tags=["talend", "ventes"]) as dag:
    extract = SSHOperator(task_id="talend_extract", ssh_conn_id="jobserver_prod", pool="talend", cmd_timeout=3600,
        command="/opt/talend/jobs/VENTES_Extract/VENTES_Extract_run.sh --context=PROD --context_param run_date={{ ds }} --context_param s3_prefix=raw/ventes/{{ ds_nodash }}")   # code de retour ≠ 0 → échec → retry
    validate = PythonOperator(task_id="validate", python_callable=validate_counts, op_kwargs={"date": "{{ ds }}"})   # compare count S3 vs run_log ; lève AirflowException si écart > 1 %
    transform = PostgresOperator(task_id="transform", postgres_conn_id="dwh", sql="sql/ventes_transform.sql", params={"date": "{{ ds }}"})   # idempotent : DELETE WHERE date = %(date)s puis INSERT
    load_redshift = S3ToRedshiftOperator(task_id="load_redshift", schema="serving", table="ventes", s3_bucket="dl-curated-eu", s3_key="domaine=ventes/date={{ ds }}/", copy_options=["FORMAT AS PARQUET"], method="REPLACE", redshift_conn_id="redshift")
    notify_ok = PythonOperator(task_id="notify_ok", python_callable=slack, op_kwargs={"msg": "ventes {{ ds }} OK"})
    notify_ko = PythonOperator(task_id="notify_ko", python_callable=slack, op_kwargs={"msg": "ventes {{ ds }} ÉCHEC : {{ ti.xcom_pull(task_ids='validate') }}"}, trigger_rule=TriggerRule.ONE_FAILED)
    extract >> validate >> transform >> load_redshift >> notify_ok
    [extract, validate, transform, load_redshift] >> notify_ko
# alternative : appel API TAC (metaServlet runTask synchronous) via SimpleHttpOperator ; ou KubernetesPodOperator qui lance l'image du job Talend"""),
  ("Configuration et exploitation", "", """# airflow.cfg / env : AIRFLOW__CORE__EXECUTOR=CeleryExecutor (ou KubernetesExecutor sur EKS) ; AIRFLOW__SECRETS__BACKEND=airflow.providers.amazon.aws.secrets.secrets_manager.SecretsManagerBackend ; connections_prefix airflow/connections
Variables (Admin → Variables ou Secrets Manager) : environnement, seuils ; jamais de secret en Variable non chiffrée
Pools : talend = 4 (le Job Server n'exécute que 4 jobs en parallèle) ; redshift = 2
Scheduler : dag_dir_list_interval, parsing_processes ; DAG lourd à importer = scheduler lent → pas d'appel réseau au niveau module
Diagnostic : airflow dags list-import-errors ; airflow tasks test ventes_quotidien talend_extract 2026-09-22 ; logs par tâche (S3 remote logging) ; DAG « bloqué » : pool plein, max_active_runs, tâche en queued sans worker (Celery/K8s), dépendance amont en échec, scheduler arrêté (heartbeat) ; airflow db check ; métriques StatsD → Prometheus (dag_processing, scheduler_heartbeat, pool.open_slots, ti.finish)""")],
 [("Pourquoi <code>catchup=False</code> et <code>max_active_runs=1</code> ?", "Sans catchup, un DAG activé tard ne rejoue pas tout l'historique ; avec un seul run actif, deux nuits ne se chevauchent pas sur le Job Server et la base. Le rattrapage se fait par backfill volontaire."),
  ("Question d'entretien : XCom pour passer un fichier de 2 Go ?", "Non : XCom stocke des petites valeurs dans la base de métadonnées. On passe une référence (chemin S3) et la tâche suivante lit S3.")],
 ("Plateforme Airflow + Talend", ["Airflow en Docker Compose (Celery, PostgreSQL, Redis) avec backend de secrets ; DAG <code>ventes_quotidien</code> qui lance le job Talend exporté (BashOperator dans un conteneur Java ou SSH), valide, transforme, charge, notifie.", "Provoquer : job Talend en erreur (retry puis notification), validation en échec (branche ko), pool saturé (tâches queued), scheduler arrêté (DAG « bloqué »), et diagnostiquer chaque cas.", "Backfill de 7 jours ; SLA miss simulé ; métriques Airflow dans Grafana."],
  "Preuve : le DAG rejoué deux fois pour la même date ne duplique rien (DELETE/INSERT et REPLACE) ; le retry exponentiel apparaît dans les logs (5, 10, 20 min) ; <code>notify_ko</code> s'exécute avec le message de la validation ; le backfill de 7 jours respecte le pool de 4 ; le dashboard montre <code>ti_failures</code> et la durée par tâche.")),

ch("Docker, Kubernetes et monitoring pour la Data", 'c',
 ["Conteneuriser un job Talend (ZIP exporté dans une image JRE), un outil (Airflow, Druid, ES) ou une application ; healthchecks, volumes pour l'état, réseau, registre privé (ECR), images par digest.", "Kubernetes (EKS) : Deployment pour le sans-état (Airflow webserver/scheduler, API), StatefulSet pour l'état (PostgreSQL, Elasticsearch, Druid Historicals, Kafka) avec PVC par réplica et identité stable, ConfigMap/Secret (External Secrets), Ingress, namespaces par équipe avec quotas ; opérateurs (ECK pour ES, Druid operator, Strimzi).", "Monitoring : Prometheus (node exporter, postgres_exporter, redshift/druid/ES exporters, JMX pour Talend/Airflow, StatsD Airflow), CloudWatch pour les services managés, Grafana pour les dashboards, Alertmanager pour les alertes sur symptômes (SLA de flux, lag, erreurs, saturation)."],
 ["Conteneuriser un job Talend et le lancer par Kubernetes (Job/CronJob) ou Airflow", "Déployer un StatefulSet de base ou d'outil data avec ses volumes", "Construire les dashboards et alertes essentiels de la plateforme"],
 [("Job Talend en conteneur et sur Kubernetes", "", """FROM eclipse-temurin:17-jre-alpine
RUN adduser -D talend
COPY --chown=talend VENTES_Extract/ /opt/job/           # ZIP exporté et dézippé par le pipeline (chapitre TIS)
USER talend
WORKDIR /opt/job
ENTRYPOINT ["sh", "VENTES_Extract/VENTES_Extract_run.sh"]
CMD ["--context=PROD"]
---
apiVersion: batch/v1
kind: CronJob
metadata: { name: ventes-extract, namespace: data-ventes }
spec:
  schedule: "0 3 * * *"; concurrencyPolicy: Forbid; successfulJobsHistoryLimit: 3
  jobTemplate: { spec: { backoffLimit: 2, activeDeadlineSeconds: 3600, template: { spec: { restartPolicy: Never, serviceAccountName: ventes (IRSA → rôle IAM S3),
    containers: [{ name: job, image: 123.dkr.ecr.eu-west-3.amazonaws.com/talend/ventes-extract@sha256:…, args: ["--context=PROD", "--context_param", "run_date=$(DATE)"], env: [{ name: DB_PASSWORD, valueFrom: { secretKeyRef: { name: dwh, key: password } } }], resources: { requests: { cpu: "500m", memory: "2Gi" }, limits: { memory: "2Gi" } } }] } } } }
# ou KubernetesPodOperator depuis Airflow : même image, logs remontés dans Airflow"""),
  ("StatefulSet PostgreSQL / Elasticsearch", "", """apiVersion: apps/v1
kind: StatefulSet
metadata: { name: es-data, namespace: search }
spec:
  serviceName: es-data; replicas: 3; podManagementPolicy: Parallel
  selector: { matchLabels: { app: es, role: data } }
  template: { metadata: { labels: { app: es, role: data } }, spec: { initContainers: [{ name: sysctl, image: busybox, command: ["sysctl", "-w", "vm.max_map_count=262144"], securityContext: { privileged: true } }],
    containers: [{ name: es, image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0, env: [{ name: ES_JAVA_OPTS, value: "-Xms8g -Xmx8g" }, { name: node.roles, value: "data" }, { name: discovery.seed_hosts, value: "es-master" }], resources: { requests: { memory: "16Gi", cpu: "4" }, limits: { memory: "16Gi" } }, volumeMounts: [{ name: data, mountPath: /usr/share/elasticsearch/data }], readinessProbe: { httpGet: { path: /_cluster/health?local=true, port: 9200 } } }],
    affinity: { podAntiAffinity: { requiredDuringSchedulingIgnoredDuringExecution: [{ labelSelector: { matchLabels: { app: es } }, topologyKey: kubernetes.io/hostname }] } } } }
  volumeClaimTemplates: [{ metadata: { name: data }, spec: { accessModes: [ReadWriteOnce], storageClassName: gp3, resources: { requests: { storage: 500Gi } } } }]
# en pratique : opérateur ECK (Elasticsearch CRD) ; PostgreSQL : CloudNativePG ; Druid : druid-operator ; PodDisruptionBudget minAvailable: 2 ; PriorityClass ; sauvegardes vers S3"""),
  ("Monitoring", "", """| Composant     | Métriques clés                                                                | Alerte                                   |
| EC2/nœuds     | CPU, load, mem_used, disk_used, iowait, net                                     | disque > 85 %, load > 2×vCPU 10 min      |
| PostgreSQL    | connexions, tps, cache hit, locks, deadlocks, dead tuples, replication lag, xid age | lag > 60 s, connexions > 80 %, xid > 1,5 G |
| RDS/Aurora    | CPU, DatabaseConnections, FreeStorageSpace, ReadLatency, ReplicaLag, ACU         | idem + bascule (event)                   |
| DynamoDB      | Consumed vs Provisioned, ThrottledRequests, latency                            | throttled > 0 5 min                      |
| Redshift      | CPU, queue wait, disk %, WLM queued, commit queue                               | disk > 80 %, queue wait > 60 s           |
| Druid         | segments unavailable, query time p95, ingestion lag, JVM heap                    | unavailable > 0, lag > 5 min             |
| Elasticsearch | cluster status, unassigned shards, heap %, GC time, disk %, indexing rate       | red, heap > 85 %, disk > 85 %            |
| Talend        | run_log (durée, lignes, rejets, code), JVM heap du Job Server, jobs concurrents  | job KO, durée > 2× médiane, rejets > seuil |
| Airflow       | scheduler heartbeat, dag run duration, ti failures, pool slots, queued tasks     | heartbeat absent, SLA miss, failures     |
| JVM           | heap used/after GC, GC pause, threads, fds                                       | heap après GC croissant (fuite), GC > 10 % |
Grafana : un dashboard « plateforme » (saturation), un par brique, un « flux » (run_log + DAG : SLA par flux métier) ; Alertmanager : routage par équipe, silences, runbook_url obligatoire""")],
 [("Pourquoi un StatefulSet et pas un Deployment pour Elasticsearch ?", "Identité stable (nom, DNS) pour le cluster, un volume par réplica qui survit au redémarrage, ordre contrôlé ; un Deployment donnerait des Pods interchangeables sans disque attaché de façon stable."),
  ("Question d'entretien : quelle est la première alerte à créer sur une Data Platform ?", "Le SLA des flux métier (le fichier des ventes est-il arrivé dans Redshift avant 7 h ?) : c'est ce que les utilisateurs voient. Les alertes de saturation viennent ensuite pour anticiper.")],
 ("Plateforme conteneurisée et supervisée", ["Image du job Talend, CronJob sur kind avec IRSA simulée, et la même image lancée par KubernetesPodOperator.", "StatefulSet Elasticsearch 3 nœuds (ou ECK) et PostgreSQL (CloudNativePG) sur kind avec PVC ; perte d'un Pod et vérification de la reprise avec ses données.", "Prometheus + Grafana + Alertmanager : exporters PostgreSQL/ES/node, StatsD Airflow, run_log Talend ; dashboards plateforme et flux ; 8 alertes avec runbook."],
  "Preuve : le CronJob écrit dans S3 (MinIO) avec le rôle du ServiceAccount ; après <code>kubectl delete pod es-data-1</code> le Pod revient avec le même PVC et le cluster repasse green ; l'alerte « flux ventes en retard » se déclenche quand le DAG est mis en pause 30 min ; chaque alerte a son <code>runbook_url</code>.")),

ch("MCO, support N3 et incidents de production", 's',
 ["Le Maintien en Condition Opérationnelle est une routine : quotidienne (supervision, échecs de la nuit, sauvegardes, espace, certificats), hebdomadaire (patchs, capacité, revue des alertes, tickets), mensuelle (restauration testée, revue de sécurité, coûts, rotation des secrets, mises à jour majeures planifiées).", "Le support N3 suit une méthode : symptôme → périmètre (qui, depuis quand, quoi d'autre) → hypothèses ordonnées → investigations avec commandes et métriques → cause → résolution → prévention (runbook, alerte, automatisation) → post-mortem.", "Les incidents reviennent toujours aux mêmes familles : saturation (CPU, disque, connexions, heap), blocage (verrous, files, pools), configuration (droits, DNS, certificats, contextes), données (volume inattendu, format), dépendance (API, S3, réseau)."],
 ["Tenir les checklists MCO et mesurer ce qui est fait", "Dérouler la méthode N3 sur dix scénarios types", "Constituer le catalogue de 30 incidents avec diagnostic, commandes, solution, prévention"],
 [("Checklist MCO", "", """QUOTIDIEN : dashboard plateforme (rouge ?), échecs de la nuit (TAC, Airflow, run_log), sauvegardes de la nuit OK (RDS, snapshots, ES SLM), espace disque (EC2, RDS FreeStorage, ES watermarks), certificats < 30 j, alertes non acquittées, tickets N2 remontés
HEBDO : patchs disponibles (AMI, RDS maintenance window, ES/Druid versions), capacité (tendance disque/CPU/connexions sur 30 j), revue des alertes bruyantes (supprimer ou corriger), tickets récurrents → automatisation, revue des accès demandés (self-service)
MENSUEL : restauration testée (RDS PITR dans une instance de test, ES snapshot, S3 versioning), revue de sécurité (Prowler, IAM last accessed, secrets non tournés), coûts (Cost Explorer par tag, anomalies), rotation des secrets, mises à jour majeures planifiées (RDS major, Talend patch, Airflow), post-mortems relus, runbooks mis à jour, exercice de bascule (trimestriel)"""),
  ("Scénarios N3 (extrait des dix)", "", """BASE LENTE : symptôme : DAG en retard, API lente | investigation : Performance Insights / pg_stat_activity (attentes), pg_stat_statements (nouvelle requête ?), locks, CPU, iowait, autovacuum en cours ? | hypothèses : requête sans index déployée hier, statistiques périmées, verrou d'un job Talend, vacuum wraparound | commandes : EXPLAIN ANALYZE, pg_blocking_pids, pg_stat_user_tables | résolution : index concurrent / ANALYZE / kill de la session (pg_terminate_backend) | prévention : revue des requêtes en MR, auto_explain, alerte sur les transactions longues
DISQUE PLEIN (EC2 Job Server) : df -h, du -xsh /var/log /tmp /opt/talend/jobserver/jobs | cause : logs de jobs non purgés, fichiers temporaires Talend d'un job planté | résolution : purge, logrotate, TAC purge tasks | prévention : alerte 80 %, logrotate, tmp sur volume séparé, purge automatique
POSTGRESQL BLOQUE : pg_stat_activity wait_event Lock ; pg_blocking_pids → transaction « idle in transaction » d'un job Talend qui a planté sans rollback | résolution : pg_terminate_backend ; prévention : idle_in_transaction_session_timeout, tDBRollback dans les jobs, lock_timeout dans les migrations
DYNAMODB THROTTLE : ThrottledRequests, Contributor Insights clé chaude | cause : nouvelle fonctionnalité avec clé = pays | résolution : on-demand temporaire + sharding de clé ; prévention : revue de modèle par accès avant mise en prod
ELASTICSEARCH ROUGE : _cluster/health, _cat/shards unassigned, allocation/explain | cause : nœud perdu + index sans réplique, ou disque flood | résolution : nœud de retour / snapshot / réplique ; prévention : réplique ≥ 1, ILM, watermarks alertés
TALEND JOB EN ERREUR : code de retour, log du job (tLogCatcher), run_log, TAC execution | cause : fichier source absent/format, mot de passe tourné, API tierce 500, OOM | résolution : rejouer après correction ; prévention : contrôle d'arrivée (sensor), secrets dynamiques, retry, -Xmx
AIRFLOW DAG BLOQUÉ : scheduler heartbeat, tâches queued, pool, max_active_runs, worker Celery | cause : pool plein par une tâche zombie, scheduler crashé, worker sans slot | résolution : clear de la tâche zombie, restart | prévention : timeouts de tâche, alerte heartbeat, pools dimensionnés
CPU ÉLEVÉ (EC2) : top → JVM Talend ; jstack / jcmd Thread.print → boucle ou GC ; jstat -gcutil → GC continu = heap trop petit | résolution : -Xmx, correction du job | prévention : dimensionnement par job dans le TAC, alerte GC
FUITE MÉMOIRE JVM : heap après GC croissant, OOM après N heures (Job Server, Druid, ES) | jcmd GC.heap_dump → MAT (leak suspects : HashMap statique d'un tJava, cache sans borne, fielddata ES) | résolution : correction, restart planifié en attendant | prévention : métrique heap après GC alertée, revue des tJava
EC2 INACCESSIBLE : StatusCheck, console screenshot, SSM (pas de SSH), logs système via EBS attaché ailleurs | cause : disque plein (/ à 100 %), OOM système, mise à jour cassée | résolution : recover / remplacement par l'ASG, volume data réattaché | prévention : / séparé du data, alerte disque, immutabilité"""),
  ("Catalogue d'incidents", "Trente incidents au format incident → impact → diagnostic → commandes → solution → prévention, répartis : AWS (IAM révoqué, NAT saturé, quota EC2, KMS désactivée, S3 lifecycle qui supprime), bases (wraparound, réplica cassé, bascule non absorbée, bloat, connexions), DynamoDB/Redshift (throttle, disque, WLM), Druid/ES (segments indisponibles, heap, watermark, mapping explosion), Talend/TAC/Job Server (licence expirée, TAC base pleine, Job Server unreachable, job zombie, contexte faux), Airflow (metadata DB pleine, scheduler, XCom géant), réseau/sécurité (certificat expiré, SG modifié, DNS), coût (instance oubliée, transfert inter-région). Chaque entrée est un runbook d'une page dans <code>docs/runbooks/</code>.", None)],
 [("Un incident revient chaque lundi : que fait le N3 ?", "Cherche le motif (charge du lundi, job hebdo, patch du week-end), reproduit, corrige la cause (dimensionnement, ordre des jobs, verrou) et ajoute une alerte prédictive ; un incident récurrent non traité est une dette d'exploitation, pas une fatalité."),
  ("Question d'entretien : quelle est ta première action sur « la plateforme est lente » ?", "Qualifier : quoi, qui, depuis quand, un changement récent ? Puis le dashboard plateforme (quelle ressource est saturée) et les changements (déploiements, DAG, jobs) de la fenêtre. Ensuite seulement les commandes ciblées.")],
 ("Kit MCO et N3", ["Checklists MCO en scripts (Python + boto3) : sauvegardes de la nuit, espace, certificats, échecs, coûts → rapport quotidien Slack.", "Dix scénarios N3 rejoués sur le laboratoire (Docker/kind) avec la fiche symptôme → … → prévention remplie pour chacun.", "Catalogue de 30 runbooks dans <code>docs/runbooks/</code> avec un index par symptôme ; post-mortem type."],
  "Le rapport quotidien contient les 7 contrôles avec un statut ; chaque scénario est résolu en < 15 min avec la fiche ; l'index des runbooks est testé par un pair (« disque plein » → 30 s pour trouver la page).")),

ch("Sécurité, Terraform, Ansible, self-service et haute disponibilité", 's',
 ["Sécuriser la plateforme : moindre privilège IAM par rôle et par équipe, secrets dans Secrets Manager/Vault (jamais dans Talend/Airflow), KMS partout, TLS entre briques (Job Server, PostgreSQL sslmode=verify-full, ES), patch et hardening des EC2, audit (CloudTrail, pgaudit, ES audit), accès humains par SSO + SSM, revue trimestrielle.", "Terraform pour tout (VPC, EC2, RDS, S3, IAM, monitoring) : modules, state distant verrouillé, un state par environnement, pipeline plan/apply ; Ansible pour l'intérieur des EC2 (Job Server, agents, hardening, patch) avec inventaire dynamique.", "Self-service : portail (Backstage, ou formulaire) → API/MR → Terraform module → validation (policy as code : tags, chiffrement, taille, coût) → apply → monitoring et documentation automatiques ; GitOps pour Kubernetes. HA : multi-AZ partout, réplication, sauvegardes hors site, RTO/RPO par service, PRA exercé."],
 ["Appliquer la grille de sécurité à chaque brique", "Écrire les modules Terraform et playbooks Ansible de la plateforme", "Concevoir le self-service et l'architecture résiliente avec RTO/RPO"],
 [("Terraform : modules et self-service", "", """platform/
  modules/ vpc/ ec2-jobserver/ rds-postgres/ aurora/ s3-datalake/ dynamodb-table/ iam-team-role/ monitoring/ es-domain/ (ou EKS + ECK)
  envs/ dev/ prod/  → backend s3 (versioning, lock DynamoDB), un state par composant ; providers épinglés ; terraform test sur chaque module
  policies/ (OPA/conftest sur le plan) : tags Owner/Team/CostCenter obligatoires, chiffrement KMS, pas de 0.0.0.0/0 sauf 443 ALB, RDS non public, backup ≥ 7 j, instance dans la liste autorisée, budget estimé (infracost) < seuil de l'équipe
# self-service : le Data Engineer remplit un formulaire (Backstage template « base PostgreSQL ») → MR générée dans envs/dev avec module "rds-postgres" { name, size = "small", team } → pipeline : plan + conftest + infracost + approbation du Tech Lead pour prod → apply → sortie : endpoint, secret dans Secrets Manager, dashboard Grafana, alertes, page catalogue
module "ventes_db" { source = "../../modules/rds-postgres"; name = "ventes"; size = "small"; team = "ventes"; kms_key_arn = module.kms.data_arn; subnets = module.vpc.database_subnets; allowed_sg = [module.jobserver.sg_id] }"""),
  ("Ansible : Job Server et hardening", "", """# inventory : plugin aws_ec2, groupes par tag Role (jobserver, druid, es) ; connexion par SSM (ansible_connection: community.aws.aws_ssm) : pas de port 22
- hosts: jobserver
  become: true
  roles:
    - { role: hardening, vars: { cis_level: 1 } }                # sysctl, auditd, permissions, chrony, pas de root SSH
    - { role: cloudwatch_agent, vars: { metrics: [mem, disk], logs: ["/opt/talend/jobserver/logs/*.log"] } }
    - { role: talend_jobserver, vars: { version: "8.0.1", tac_host: "{{ tac_host }}", jvm_xmx: "8g", users: "{{ lookup('amazon.aws.aws_secret', 'talend/jobserver/users') }}" } }   # templates conf, service systemd, healthcheck 8888
  tasks:
    - name: patch (fenêtre)
      ansible.builtin.dnf: { name: "*", state: latest, security: true }
      notify: reboot si nécessaire
# molecule pour tester les rôles ; ansible-lint en CI ; exécution par pipeline avec OIDC, jamais depuis un poste"""),
  ("Haute disponibilité et PRA", "", """| Brique        | HA                                              | Sauvegarde / reprise                                   | RTO / RPO cible |
| PostgreSQL RDS| Multi-AZ, pool résilient                        | snapshots + PITR, copie inter-région                   | 15 min / 5 min  |
| Aurora        | writer + readers 3 AZ                           | backtrack, PITR, Global Database si multi-région       | 5 min / 1 min   |
| DynamoDB      | natif multi-AZ                                  | PITR, export S3, Global Tables                         | 0 / 0           |
| S3            | natif (11 9 de durabilité)                      | versioning, réplication vers un compte isolé, Object Lock | 0 / 0        |
| Redshift      | multi-AZ (RA3), relocation                      | snapshots automatiques + inter-région                  | 1 h / 1 h       |
| Druid         | 2 Brokers, 2 Coordinators, Historicals ×N       | deep storage S3 = vérité ; metadata store RDS Multi-AZ | 30 min / 0      |
| Elasticsearch | 3 masters, répliques ≥ 1, zones                 | snapshots S3 (SLM), restauration testée                | 1 h / 1 h       |
| Job Server    | ASG(1) auto-réparé + second serveur en réserve   | jobs dans Nexus, config Ansible : reconstruction 15 min | 30 min / 0     |
| TAC           | Tomcat sur ASG + base RDS Multi-AZ              | dump base TAC + snapshots                               | 1 h / 15 min   |
| Airflow       | scheduler ×2 (HA), workers ×N, metadata RDS     | metadata RDS, DAGs dans Git                             | 15 min / 5 min |
PRA : Terraform recrée l'infrastructure dans la région secondaire (pilot light), données répliquées (S3, RDS copies, DynamoDB Global), bascule DNS ; exercice trimestriel chronométré ; runbook""")],
 [("Un Data Engineer demande un accès administrateur à RDS pour « aller plus vite » : réponse ?", "Non : un rôle applicatif limité au schéma, un accès humain temporaire (JIT) via SSO et bastion SSM journalisé si nécessaire, et le besoin réel (souvent une migration) passe par la CI. La plateforme fournit le chemin rapide sûr."),
  ("Question d'entretien : différence entre RTO et RPO ?", "RTO = durée maximale d'interruption acceptée ; RPO = quantité de données (en temps) qu'on accepte de perdre. Ils se fixent par service avec le métier, se chiffrent en coût, et se prouvent par des exercices.")],
 ("Plateforme automatisée et résiliente", ["Modules Terraform (VPC, Job Server, RDS, S3, DynamoDB, monitoring) avec tests et policies conftest ; pipeline plan/apply ; formulaire self-service → MR → apply.", "Playbooks Ansible (hardening, agent, Job Server, patch) sur inventaire dynamique par SSM ; Molecule.", "Tableau RTO/RPO, exercice de bascule RDS et restauration S3/ES, coût du PRA chiffré."],
  "Preuve : une demande self-service produit une base en 12 min avec secret, dashboard et alertes sans intervention ; une MR sans tag est refusée par conftest ; l'exercice de bascule mesure RTO 9 min pour RDS et 40 min pour ES depuis snapshot ; le coût du pilot light est chiffré (≈ +18 %).")),

ch("GCP en complément, projet final Tech Lead, questions d'entretien et fiche de survie", 'e',
 ["Correspondances AWS → GCP : EC2 → Compute Engine, S3 → Cloud Storage, RDS/Aurora → Cloud SQL/AlloyDB, DynamoDB → Firestore/Bigtable, Redshift → BigQuery (serverless, facturé au scan), IAM → IAM (par projet, hiérarchie), CloudWatch → Cloud Monitoring/Logging, Secrets Manager → Secret Manager, EKS → GKE, Airflow → Cloud Composer ; ce qui change : projets comme unité, VPC global, BigQuery qui remplace souvent Redshift + Athena.", "Le projet final : infrastructure AWS (Terraform), Talend TIS (chaîne Git → CI → Nexus → TAC → Job Server), Airflow, PostgreSQL/Aurora, Elasticsearch, Druid, monitoring, CI/CD, self-service, MCO ; présentable en 15 minutes avec les flux, les choix, les risques et les coûts.", "Les 100 questions d'entretien couvrent chaque brique en deux niveaux (réponse courte, réponse technique) ; la fiche de survie condense commandes, concepts, erreurs, métriques et procédures."],
 ["Comprendre une plateforme multi-cloud AWS/GCP", "Construire et présenter le projet final Tech Lead", "Répondre aux questions d'entretien et réciter la fiche de survie"],
 [("Projet final", "", """Laboratoire local (Docker/kind) : CSV → Talend (ZIP en conteneur ou Open Studio) → PostgreSQL → Airflow (DAG) → Elasticsearch → Grafana ; puis sur AWS : EC2 Job Server (ASG, AMI, Ansible), RDS PostgreSQL Multi-AZ, S3 data lake, IAM/KMS/Secrets Manager, CloudWatch ; Terraform pour tout ; pipeline GitLab (Talend build → Nexus → TAC/Job Server ; DAGs → S3/Git sync ; Terraform plan/apply)
Architecture à présenter (15 min) : 1) contexte et utilisateurs 2) schéma avec les flux numérotés 3) sécurité (IAM, KMS, secrets, TLS, audit) 4) exploitation (monitoring, alertes, MCO, N3, runbooks) 5) industrialisation (CI/CD, Terraform, self-service) 6) résilience (HA, PRA, RTO/RPO) 7) coûts (par brique, leviers) 8) risques et roadmap (dette Talend, migration Redshift → ?, Kubernetes pour Druid/ES)"""),
  ("Questions d'entretien (extrait des 100, par domaine)", "", """AWS : VPC trois niveaux pourquoi ? · SG vs NACL · rôle vs utilisateur IAM · endpoint S3 · KMS enveloppe · CloudTrail vs CloudWatch · comment auditer un accès S3 · NAT coût
EC2/Linux : load average · iowait · OOM killer · steal · IMDSv2 · ASG(1) · instance refresh · SSM vs SSH · diagnostiquer une machine lente en 5 commandes
PostgreSQL : MVCC · WAL · vacuum/autovacuum · index B-tree/GIN/BRIN · EXPLAIN ANALYZE lire · deadlock · idle in transaction · isolation · réplication streaming vs logique · wraparound
RDS/Aurora : Multi-AZ vs réplica · bascule et pool · Parameter Group · Performance Insights · Aurora stockage · Serverless v2 · PITR
DynamoDB : partition key · hot partition · GSI vs LSI · RCU/WCU · on-demand vs provisionné · TTL · Streams
S3/Redshift : storage classes · versioning/Object Lock · politique vs ACL · Parquet · DISTKEY/SORTKEY · Spectrum · WLM · Redshift vs Athena vs PostgreSQL
Druid : rôles des nœuds · segments · deep storage · rollup · ingestion Kafka vs batch · pourquoi Druid
Elasticsearch : shards/répliques · yellow/red · heap 31 Go · watermarks · ILM · reindex sans coupure · snapshots
Talend : tMap lookups · contextes · rejets vs erreurs · tRunJob transmission · commit/batch · run_log · mauvais job typique · export et exécution CLI
TAC/Job Server : chaîne de déploiement · tâches et triggers · ports · unreachable · JVM par tâche · AMC · metaServlet
Airflow : scheduler/executor/worker · idempotence et data_interval · catchup · XCom · pools · secrets backend · DAG bloqué · SLA
Docker/K8s : image d'un job Talend · StatefulSet vs Deployment · PVC · IRSA · CronJob · PDB · opérateurs
Monitoring : USE/RED · alertes symptômes · SLA de flux · heap après GC · lag de réplication · runbook_url
Sécurité : moindre privilège · secrets dans Talend · TLS PostgreSQL · pgaudit · patch · revue d'accès
Terraform/Ansible : state et lock · modules · plan en MR · drift · policy as code · inventaire dynamique · Molecule
MCO/N3 : checklists · première action sur « c'est lent » · incident récurrent · post-mortem · RTO/RPO
Format de réponse : phrase courte + exemple vécu (le laboratoire) + ce qu'on vérifierait en premier"""),
  ("Fiche de survie (condensé)", "", """COMMANDES : uptime top htop vmstat iostat free df du ss sar ps journalctl systemctl dmesg jcmd jstat jstack · psql: \\l \\dt \\d+ pg_stat_activity pg_blocking_pids pg_stat_statements EXPLAIN ANALYZE VACUUM ANALYZE pg_terminate_backend · aws: sts get-caller-identity, s3 ls/cp, rds describe-events/failover, dynamodb query, logs start-query, cloudtrail lookup-events, ce get-cost-and-usage · curl ES: _cluster/health _cat/nodes _cat/indices _cat/shards allocation/explain _snapshot · druid sys.segments sys.tasks · airflow dags list-import-errors, tasks test, tasks clear, dags backfill · talend: <job>_run.sh --context --context_param ; TAC metaServlet · terraform plan -detailed-exitcode, state list · ansible-playbook -i aws_ec2.yml --limit · kubectl get/describe/logs/exec, rollout, top
CONCEPTS : trois niveaux VPC · rôle IAM · enveloppe KMS · MVCC/WAL/vacuum · Multi-AZ vs réplica · partition key · Parquet · DISTKEY/SORTKEY · segments Druid · shards/heap ES · contextes Talend · run_log · chaîne Git→CI→Nexus→TAC→Job Server · DAG idempotent · pool · StatefulSet · USE/RED · SLA de flux · RTO/RPO · pilot light · policy as code · self-service
ERREURS FRÉQUENTES : clé d'accès dans un job · mot de passe en contexte commité · commit ligne à ligne · lookup rechargé · pas de rejets · catchup=True surprise · XCom géant · index par jour ES sans ILM · PK DynamoDB faible cardinalité · CSV dans le lake · NAT unique · pas de lock_timeout · VACUUM FULL en prod · trust-all TLS · alerte sans runbook · restauration jamais testée · logs sans rétention · TAC et Job Server de versions différentes · -Xmx par défaut · Deployment pour une base
MÉTRIQUES : load, iowait, mem available, disk %, connexions PG, lag réplication, dead tuples, xid age, RDS FreeStorage, ThrottledRequests, Redshift queue wait, segments unavailable, ES status/heap/watermark, run_log durée/rejets/code, Airflow heartbeat/failures/SLA, heap après GC, coût par équipe
PROCÉDURES : qualifier → dashboard → changements → commandes ciblées → cause → correction → prévention → post-mortem ; bascule RDS ; restauration PITR ; restauration ES ; job zombie ; DAG bloqué ; disque plein ; secret tourné
SCHÉMAS : architecture de référence · VPC trois niveaux · chaîne Talend TIS · DAG ETL · Druid · ES cluster · monitoring · HA/PRA""")],
 [("Le client hésite entre migrer Redshift vers BigQuery ou rester : critères ?", "Données déjà sur AWS (transfert et latence), compétences, coût au scan contre cluster, outils BI, gouvernance multi-cloud. Rester et optimiser (RA3, Serverless, Spectrum) est souvent moins risqué ; BigQuery vaut le coup si l'entreprise est déjà GCP-first pour la data."),
  ("Question d'entretien finale : présente la plateforme en 3 minutes.", "Utilisateurs et besoin → le schéma en un flux (ingestion, stockage, service, orchestration) → ce qui la rend exploitable (IaC, CI/CD, monitoring, MCO, N3) → un chiffre (coût, SLA tenu) → un risque et ce qu'on fait.")],
 ("Projet final et simulation d'entretien", ["Laboratoire complet local puis AWS (EC2 + RDS + S3) avec tous les fichiers dans un dépôt ; dashboard Grafana de bout en bout ; coût mesuré et ressources détruites.", "Dossier d'architecture Tech Lead (8 pages, schémas, coûts, risques, roadmap) et présentation de 15 minutes enregistrée.", "100 questions répondues à voix haute (30 s), fiche de survie apprise, trois scénarios N3 rejoués sans notes."],
  "Objectif : le CSV du matin est dans Elasticsearch et visible dans Grafana avant 7 h via Talend → PostgreSQL → Airflow, avec une alerte SLA qui prouve la chaîne ; la présentation tient en 14 min ; 90/100 questions répondues sans hésitation.")),
]

d = sys.argv[1]
page('cours-data-platform-aws-talend.html', 'Data Platform, AWS, Talend, Airflow et InfraOps — de zéro à expert', "Quinze chapitres orientés mission et entretien : architecture et rôles, AWS pour la data, EC2 et Linux expert, PostgreSQL, RDS et Aurora, DynamoDB/S3/Redshift, Druid et Elasticsearch, Talend (débutant, avancé, audit, TIS/TAC/Job Server, CI/CD), Airflow, Docker/Kubernetes/monitoring, MCO et support N3, sécurité/Terraform/Ansible/self-service/HA, GCP, projet final Tech Lead, questions d'entretien et fiche de survie. Tout en Docker et Terraform, chaque chapitre a ses exercices corrigés et un travail pratique avec correction type.", "≈ 80 h de travail · prérequis : Docker Desktop, un compte AWS sandbox, Talend Open Studio pour s'exercer (TIS si licence) · s'appuie sur le parcours DevOps (niveaux 3 à 6) et le cours Cloud.", DATA, [('cours-cloud.html', 'Cloud'), ('devops-niveau-4-cloud.html', 'DevOps niveau 4'), ('devops-niveau-6-observabilite.html', 'DevOps niveau 6')])
