import re, pathlib, json

G = {
# ---- shell / Linux
"pwd":"affiche le répertoire courant","ls":"liste les fichiers (-l détails, -a cachés, -h tailles lisibles)","cd":"change de répertoire","find":"cherche des fichiers par nom, taille, date","du":"taille occupée par des répertoires","df":"espace libre par système de fichiers (-h lisible, -i inodes)",
"chmod":"change les droits (lecture, écriture, exécution)","chown":"change le propriétaire et le groupe","useradd":"crée un utilisateur","usermod":"modifie un utilisateur (groupes, shell)","sudo":"exécute en tant qu'un autre utilisateur, root par défaut","su":"ouvre un shell sous une autre identité",
"ps":"liste les processus","top":"processus en temps réel (CPU, mémoire)","htop":"top amélioré, interactif","kill":"envoie un signal à un processus (-15 arrêt propre, -9 forcé)","nohup":"lance une commande qui survit à la fermeture du terminal","jobs":"liste les tâches en arrière-plan du shell","fg":"ramène une tâche au premier plan","bg":"relance une tâche en arrière-plan",
"grep":"cherche un motif dans du texte ou des fichiers (-r récursif, -n numéros de ligne, -E regex, -c compte)","cut":"extrait des colonnes (-d séparateur, -f champ)","awk":"traite du texte colonne par colonne","sed":"remplace ou transforme du texte (-i sur place)","sort":"trie des lignes (-rn numérique décroissant)","uniq":"supprime ou compte les doublons de lignes consécutives (-c)","wc":"compte lignes, mots, octets (-l lignes)","head":"premières lignes","tail":"dernières lignes (-f suit le fichier en direct)","xargs":"transforme l'entrée standard en arguments de commande","tee":"écrit dans un fichier et affiche en même temps","cat":"affiche un fichier","echo":"affiche un texte","printf":"affiche un texte formaté","date":"affiche ou formate la date","seq":"génère une suite de nombres","sleep":"attend N secondes","mktemp":"crée un fichier ou répertoire temporaire unique","trap":"exécute une commande à la sortie du script ou sur un signal","set":"options du shell (-e arrêt sur erreur, -u variable non définie interdite, -o pipefail erreur dans un pipe)","export":"définit une variable d'environnement pour les commandes suivantes","source":"exécute un fichier dans le shell courant","alias":"raccourci de commande","command":"vérifie si une commande existe (-v)","which":"chemin d'un exécutable","chmod +x":"rend un fichier exécutable","ln":"crée un lien (-s symbolique)","cp":"copie","mv":"déplace ou renomme","rm":"supprime (-r récursif, -f sans confirmation)","mkdir":"crée un répertoire","rmdir":"supprime un répertoire vide","tar":"archive ou extrait (-c créer, -x extraire, -z gzip, -f fichier)","zip":"crée une archive zip","unzip":"extrait une archive zip","shopt":"options avancées du shell (nullglob : motif sans résultat = vide)","read":"lit une ligne depuis l'entrée","while":"boucle tant que","for":"boucle sur une liste","until":"boucle jusqu'à ce que","if":"condition","case":"aiguillage selon une valeur","getopts":"analyse les options d'un script (-e valeur, -v)","local":"variable locale à une fonction","readonly":"variable en lecture seule","exit":"termine le script avec un code de retour","return":"sort d'une fonction avec un code",
"apt":"gestionnaire de paquets Debian/Ubuntu","apt update":"rafraîchit la liste des paquets disponibles","apt install":"installe des paquets (-y sans confirmation)","apt-get":"gestionnaire de paquets Debian/Ubuntu (version script)","apt-get update":"rafraîchit la liste des paquets","apt-get install":"installe des paquets","apt list":"liste les paquets (--installed)","dnf":"gestionnaire de paquets RHEL/Fedora","apk":"gestionnaire de paquets Alpine","apk add":"installe un paquet sur Alpine","pip":"gestionnaire de paquets Python","pip install":"installe un paquet Python","npm":"gestionnaire de paquets Node","npm ci":"installe exactement le package-lock (pour la CI)","npm install":"installe les dépendances","npm run":"exécute un script du package.json","npm audit":"vérifie les vulnérabilités des dépendances",
"systemctl":"pilote les services systemd","systemctl status":"état d'un service","systemctl start":"démarre un service","systemctl stop":"arrête un service","systemctl restart":"redémarre un service","systemctl enable":"active au démarrage","systemctl disable":"désactive au démarrage","systemctl list-units":"liste les unités","journalctl":"lit les journaux systemd (-u service, -f suivre, --since période)","service":"pilote un service (ancienne interface)","dmesg":"messages du noyau (OOM, disque, matériel)","uptime":"durée de fonctionnement et charge moyenne","free":"mémoire utilisée et libre (-h lisible)","iostat":"statistiques d'entrées-sorties disque","vmstat":"mémoire, CPU, swap en continu","lsof":"fichiers ouverts (-p par processus, -i réseau)","crontab":"planifie des commandes récurrentes","crond":"démon de planification (-f au premier plan)",
# ---- réseau
"ip":"configuration réseau moderne","ip addr":"adresses IP des interfaces","ip route":"table de routage","ip link":"interfaces réseau","ping":"teste la joignabilité IP (-c nombre de paquets)","traceroute":"chemin des paquets vers une destination","ss":"connexions et ports en écoute (-t TCP, -u UDP, -l écoute, -p processus, -n numérique)","netstat":"connexions et ports (ancien équivalent de ss)","nc":"netcat : teste un port (-z scan, -v verbeux) ou envoie des données","curl":"requête HTTP ou autre (-s silencieux, -v détaillé, -I en-têtes seuls, -f échoue sur erreur HTTP, -o fichier, -w format)","wget":"télécharge un fichier","dig":"interroge le DNS (+short résultat court, @serveur)","nslookup":"interroge le DNS (ancien équivalent de dig)","getent":"interroge la résolution de noms du système (hosts)","host":"interroge le DNS","ufw":"pare-feu simplifié (allow, deny, enable)","iptables":"règles de pare-feu et NAT du noyau","nftables":"règles de pare-feu modernes","tcpdump":"capture le trafic réseau","openssl":"boîte à outils TLS et cryptographie","openssl s_client":"ouvre une connexion TLS et affiche le certificat","openssl x509":"lit ou affiche un certificat","openssl req":"crée une demande de certificat ou un certificat auto-signé (-x509)","ssh":"connexion sécurisée à distance","ssh-keyscan":"récupère la clé publique d'un serveur SSH","scp":"copie de fichiers via SSH","rsync":"synchronise des fichiers (local ou distant)",
# ---- git
"git":"gestion de versions","git init":"crée un dépôt","git clone":"copie un dépôt distant","git status":"état du répertoire de travail et de l'index","git diff":"différences (--staged : ce qui est indexé)","git add":"ajoute à l'index (-p morceau par morceau, -A tout)","git commit":"enregistre l'index en commit (-m message, --amend corrige le dernier)","git log":"historique (--oneline compact, --graph arbre, --all toutes branches)","git show":"détail d'un commit","git restore":"annule des modifications du répertoire de travail (--staged désindexe)","git stash":"met de côté les modifications en cours (pop les restaure)","git switch":"change de branche (-c crée)","git checkout":"change de branche ou restaure (ancienne commande)","git branch":"liste ou crée des branches (-r distantes)","git merge":"fusionne une branche dans la courante","git rebase":"rejoue les commits par-dessus une autre branche (-i interactif, --continue, --abort)","git cherry-pick":"applique un commit précis","git reset":"déplace la branche (--soft garde l'index, --hard efface tout)","git revert":"crée un commit qui annule un commit","git reflog":"journal de tout ce qu'a pointé HEAD : le filet de sécurité","git bisect":"trouve le commit fautif par dichotomie","git tag":"marque une version (-a annotée)","git push":"envoie vers le dépôt distant (-u lie la branche, --tags, --force)","git pull":"récupère et fusionne","git fetch":"récupère sans fusionner","git remote":"gère les dépôts distants","git config":"configuration (--global)","git mv":"renomme en gardant l'historique","git ls-tree":"liste les fichiers d'un commit","git rev-parse":"résout une référence en hash (--short)","git filter-repo":"réécrit l'historique (supprimer un fichier partout)","git worktree":"plusieurs répertoires de travail pour un dépôt","gitleaks":"détecte les secrets dans un dépôt","semgrep":"analyse statique du code par règles",
# ---- docker
"docker":"client Docker","docker run":"crée et démarre un conteneur (-d arrière-plan, -it interactif, --rm supprimé à l'arrêt, -p port, -v volume, -e variable, --name nom, --network réseau)","docker ps":"liste les conteneurs (-a y compris arrêtés)","docker logs":"journaux d'un conteneur (-f suivre, --tail N)","docker exec":"exécute une commande dans un conteneur en cours (-it interactif)","docker stop":"arrête proprement (SIGTERM puis SIGKILL après 10 s)","docker start":"redémarre un conteneur arrêté","docker rm":"supprime un conteneur (-f force)","docker kill":"tue un conteneur (SIGKILL)","docker inspect":"détails JSON d'un objet (état, réseau, config)","docker stats":"consommation en direct","docker top":"processus d'un conteneur","docker system df":"espace utilisé par Docker","docker system prune":"nettoie ce qui n'est plus utilisé (-a tout, --volumes aussi)","docker build":"construit une image depuis un Dockerfile (-t tag, --target étape, --no-cache)","docker buildx build":"build avancé BuildKit (multi-plateforme, cache)","docker pull":"télécharge une image","docker push":"envoie une image vers un registre","docker tag":"donne un nom supplémentaire à une image","docker images":"liste les images","docker image inspect":"détails d'une image (couches)","docker history":"couches d'une image et leurs commandes","docker login":"s'authentifie auprès d'un registre","docker volume":"gère les volumes","docker volume create":"crée un volume","docker volume ls":"liste les volumes","docker volume inspect":"détails d'un volume","docker network":"gère les réseaux","docker network create":"crée un réseau","docker network inspect":"détails d'un réseau","docker events":"flux d'événements du démon (--since)","docker version":"versions client et serveur","docker info":"informations sur le démon","docker load":"charge une image depuis une archive","docker save":"exporte une image en archive","docker cp":"copie entre hôte et conteneur",
"docker compose":"pilote une pile décrite dans compose.yaml","docker compose up":"crée et démarre les services (-d arrière-plan, --build reconstruit)","docker compose down":"arrête et supprime conteneurs et réseaux (-v aussi les volumes)","docker compose ps":"état des services","docker compose logs":"journaux (-f suivre)","docker compose exec":"commande dans un service en cours","docker compose run":"lance une commande ponctuelle dans un service (--rm)","docker compose stop":"arrête sans supprimer","docker compose start":"redémarre","docker compose restart":"redémarre les services","docker compose kill":"tue un service","docker compose config":"affiche le fichier résolu (variables, surcharges)","docker compose pull":"met à jour les images","docker compose build":"construit les images",
"dive":"explore les couches d'une image","kaniko":"construit des images sans démon Docker","trivy":"scanner de vulnérabilités (images, dépendances, IaC)","trivy image":"scanne une image","trivy config":"scanne des fichiers de configuration (Terraform, Kubernetes, Dockerfile)","trivy fs":"scanne un répertoire (dépendances)","grype":"scanner de vulnérabilités d'images et de SBOM","syft":"génère un SBOM","cosign":"signe et vérifie des artefacts (Sigstore)","cosign sign":"signe une image","cosign verify":"vérifie une signature","cosign attest":"attache une attestation (SBOM, provenance)","cosign verify-attestation":"vérifie une attestation","cosign generate-key-pair":"génère une paire de clés","cosign sign-blob":"signe un fichier","cosign attach":"attache un SBOM à une image","shellcheck":"analyse statique de scripts Bash","hadolint":"lint de Dockerfile",
# ---- kubernetes
"kubectl":"client Kubernetes","kubectl get":"liste des objets (-A tous namespaces, -o wide/yaml/json, -w suivre, -l filtre par label)","kubectl describe":"détails et événements d'un objet : à lire en premier","kubectl logs":"journaux d'un Pod (-f suivre, --previous conteneur précédent, -c conteneur)","kubectl exec":"commande dans un conteneur (-it interactif)","kubectl apply":"crée ou met à jour depuis des fichiers (-f fichier ou dossier, -k kustomize)","kubectl delete":"supprime des objets","kubectl diff":"différences entre les fichiers et le cluster","kubectl create":"crée un objet","kubectl edit":"édite un objet en direct","kubectl patch":"modifie un champ précis","kubectl scale":"change le nombre de réplicas","kubectl rollout":"gère les déploiements progressifs","kubectl rollout status":"suit un déploiement","kubectl rollout history":"historique des révisions","kubectl rollout undo":"revient à la révision précédente","kubectl rollout restart":"redémarre les Pods d'un Deployment","kubectl set image":"change l'image d'un Deployment","kubectl port-forward":"redirige un port local vers un Pod ou Service","kubectl proxy":"expose l'API en local","kubectl top":"consommation CPU et mémoire (nécessite metrics-server)","kubectl explain":"documentation d'un champ d'objet","kubectl auth can-i":"vérifie une permission (--as identité, --list toutes)","kubectl config":"gère les contextes et kubeconfig","kubectl cluster-info":"adresses du control plane","kubectl cordon":"empêche de nouveaux Pods sur un nœud","kubectl drain":"évacue les Pods d'un nœud","kubectl uncordon":"réautorise un nœud","kubectl debug":"conteneur éphémère de débogage (--image, --target) ou shell sur un nœud","kubectl cp":"copie entre le poste et un Pod","kubectl kustomize":"rend un overlay Kustomize","kubectl api-resources":"liste les types d'objets","kubectl api-versions":"versions d'API disponibles","kubectl krew":"gestionnaire de plugins kubectl","kubectl neat":"affiche un objet sans les champs de statut","kubectl tree":"arbre de propriété des objets","kubectl view-secret":"décode un Secret","kubectl who-can":"qui a une permission","kubectl get events":"événements récents du cluster",
"kind":"Kubernetes dans Docker","kind create cluster":"crée un cluster kind (--config fichier)","kind load docker-image":"charge une image locale dans le cluster","kind delete cluster":"supprime le cluster","helm":"gestionnaire de paquets Kubernetes","helm repo add":"ajoute un dépôt de charts","helm repo update":"met à jour les dépôts","helm search repo":"cherche un chart","helm show values":"valeurs par défaut d'un chart","helm install":"installe une release (-n namespace, -f values, --version)","helm upgrade":"met à jour une release (--install crée si absente, --atomic rollback si échec)","helm list":"releases installées","helm history":"révisions d'une release","helm rollback":"revient à une révision","helm template":"rend les manifests sans installer","helm diff":"différences avant upgrade (plugin)","helm uninstall":"supprime une release","helm lint":"vérifie un chart","helm test":"exécute les tests d'un chart","helm push":"publie un chart dans un registre OCI","helm unittest":"tests unitaires de templates (plugin)","argocd":"client ArgoCD","kustomize":"surcharges de manifests","istioctl":"client Istio","etcdctl":"client etcd (snapshot save/restore)","kubeadm":"installe et met à jour un cluster (upgrade, certs)","crictl":"client du runtime de conteneurs sur un nœud","k9s":"interface texte pour Kubernetes","stern":"logs de plusieurs Pods en couleur","kube-bench":"vérifie le CIS Benchmark","kubescape":"audit de posture Kubernetes","kyverno":"client Kyverno (test, apply)","conftest":"teste des fichiers avec des politiques OPA","opa":"moteur de politiques (test, eval)","velero":"sauvegarde et restauration Kubernetes","talosctl":"client Talos Linux",
# ---- IaC
"terraform":"infrastructure as code","terraform init":"télécharge providers et modules, configure le backend","terraform fmt":"formate le code (-check en CI, -recursive)","terraform validate":"vérifie la syntaxe et la cohérence","terraform plan":"calcule les changements sans les appliquer (-out sauvegarde le plan)","terraform apply":"applique les changements (un plan sauvegardé de préférence)","terraform destroy":"supprime toutes les ressources","terraform state":"manipule le state (list, show, mv, rm, pull)","terraform state list":"ressources du state","terraform state show":"détail d'une ressource","terraform state mv":"renomme dans le state sans recréer","terraform state rm":"oublie une ressource sans la détruire","terraform state pull":"télécharge le state","terraform import":"adopte une ressource existante","terraform output":"affiche les sorties (-json, -raw)","terraform force-unlock":"lève un verrou orphelin","terraform console":"évalue des expressions","terraform graph":"graphe des dépendances","terraform test":"exécute les tests .tftest.hcl","terraform providers":"providers utilisés (lock pour le lockfile)","terraform show":"affiche un plan ou le state","terraform taint":"force la recréation (ancien, préférer -replace)","tofu":"OpenTofu, équivalent de terraform","terragrunt":"surcouche Terraform (DRY des backends)","terraform-docs":"génère la documentation d'un module","checkov":"scanner de configuration IaC","tflint":"lint Terraform","infracost":"estime le coût d'un plan Terraform","packer":"construit des images de machines","packer init":"installe les plugins","packer validate":"vérifie le template","packer build":"construit l'image","vagrant":"VM de développement (up, ssh, destroy)",
"ansible":"exécute un module ad hoc sur des hôtes (-m module, -a arguments, -i inventaire)","ansible-playbook":"exécute un playbook (-i inventaire, --check simulation, --diff, --limit hôtes, --tags, -e variables, -vvv verbeux)","ansible-vault":"chiffre des fichiers ou valeurs (create, edit, encrypt_string)","ansible-galaxy":"installe rôles et collections (collection install, init)","ansible-lint":"vérifie les bonnes pratiques","ansible-inventory":"affiche l'inventaire résolu (--host, --list, --graph)","ansible-rulebook":"Event-Driven Ansible","molecule":"teste des rôles dans des conteneurs","ansible-pull":"le nœud applique un playbook depuis Git",
# ---- cloud
"aws":"CLI AWS","aws sso login":"connexion par IAM Identity Center","aws s3":"opérations S3 (ls, cp, mb, sync)","aws s3 mb":"crée un bucket","aws ecs":"pilote ECS (update-service)","aws ecs update-service":"met à jour un service ECS (nouvelle image, réplicas)","aws iam":"gère les identités","aws ec2":"gère EC2 et le réseau","aws logs":"CloudWatch Logs","awslocal":"CLI AWS pointée sur LocalStack","az":"CLI Azure","gcloud":"CLI Google Cloud","gcloud run deploy":"déploie sur Cloud Run","steampipe":"interroge le cloud en SQL","prowler":"audit de sécurité multi-cloud","nitro-cli":"gère les enclaves Nitro",
# ---- sécurité / secrets
"vault":"client HashiCorp Vault","vault secrets enable":"active un moteur de secrets","vault kv put":"écrit un secret","vault kv get":"lit un secret","vault policy write":"crée une politique","vault auth enable":"active une méthode d'authentification","vault write":"écrit une configuration ou génère une valeur","vault read":"lit une valeur (identifiants dynamiques)","vault lease revoke":"révoque un bail","kubeseal":"chiffre un Secret pour Sealed Secrets","sops":"chiffre des fichiers avec age, PGP ou KMS","age":"chiffrement de fichiers moderne","step":"client step-ca (PKI)","zap-baseline.py":"scan passif OWASP ZAP","zap-api-scan.py":"scan d'API OWASP ZAP depuis un OpenAPI","nuclei":"scan de vulnérabilités par templates","schemathesis":"fuzzing d'API depuis OpenAPI","bearer":"SAST orienté données sensibles","garak":"red teaming de modèles de langage","promptfoo":"tests et évaluations de prompts","rekor-cli":"interroge le journal de transparence Sigstore","oras":"pousse des artefacts dans un registre OCI","kubearmor":"enforcement à l'exécution","falco":"détection à l'exécution",
# ---- observabilité / perf
"k6":"tests de charge (run, --out)","curl -sf":"requête silencieuse qui échoue sur erreur HTTP","promtool":"vérifie règles et config Prometheus","amtool":"client Alertmanager","logcli":"client Loki","tempo-cli":"client Tempo","pg_dump":"sauvegarde logique PostgreSQL (-Fc format compressé)","pg_restore":"restaure une sauvegarde pg_dump","pg_basebackup":"sauvegarde physique PostgreSQL","psql":"client PostgreSQL (-U utilisateur, -d base)","pg_isready":"vérifie que PostgreSQL accepte les connexions","pgbouncer":"pooler de connexions","pgroll":"migrations sans interruption","duckdb":"base analytique en fichier","jq":"filtre et transforme du JSON","yq":"filtre et transforme du YAML","mvn":"Maven (compile, test, package)","./mvnw":"Maven wrapper (version épinglée)","java":"lance une application Java (-jar)","python":"interprète Python","python3":"interprète Python 3","pytest":"tests Python","node":"exécute du JavaScript","semantic-release":"calcule version et changelog depuis les commits","commitlint":"vérifie le format des messages de commit","renovate":"ouvre des MR de mise à jour de dépendances","dagger":"pipelines en code","act":"exécute GitHub Actions en local","gh":"CLI GitHub","glab":"CLI GitLab","make":"exécute une cible du Makefile","time":"mesure la durée d'une commande","watch":"répète une commande à intervalle","winpty":"adaptateur de terminal pour Git Bash sous Windows","start":"ouvre un fichier ou programme sous Windows","cygpath":"convertit un chemin Git Bash en chemin Windows",
}

CSS = """
/* ============ Explication des commandes ============ */
pre .explain{position:absolute;top:.5rem;right:4.9rem;background:rgba(255,255,255,.08);color:var(--code-ink);border:1px solid rgba(255,255,255,.18);border-radius:6px;font:inherit;font-size:.78rem;padding:.2rem .55rem;cursor:pointer;opacity:.55}
pre:hover .explain,pre .explain:focus-visible,pre .explain.on{opacity:1}
pre .explain.on{background:#1B7A4E;border-color:#1B7A4E;color:#fff}
pre .xpl{display:block;color:#8FD3A7;font-size:.82em;line-height:1.45;padding:.05rem 0 .35rem 1.4em;white-space:pre-wrap;word-break:break-word;font-family:"Atkinson Hyperlegible",system-ui,sans-serif}
pre .xpl::before{content:"↳ ";opacity:.7}
@media (max-width:760px){pre .explain{right:4.6rem;top:.45rem;opacity:.85;padding:.3rem .6rem;font-size:.8rem}}
@media print{pre .explain{display:none} pre .xpl{color:#1B7A4E}}
</style>"""

JS = r"""
<script>
(function(){
  var G=__GLOSSARY__; var KEY='devops-explain';
  var keys=Object.keys(G).sort(function(a,b){return b.length-a.length;});
  function esc(t){ return t.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;'); }
  function cmdOf(line){
    var l=line.trim();
    if(!l||/^#/.test(l)||/^(\/\/|--|\*|\[|<|{|}|\.|-\s|[a-zA-Z_][\w.-]*\s*[:=]\s*(?![\s\S]*\$\())/.test(l)) return null;   // commentaires, YAML, HCL, JSON, JS
    l=l.replace(/^\$\s+/,'').replace(/^(sudo|winpty|time|nohup)\s+/,'').replace(/^(?:[A-Z_][A-Z0-9_]*=\S*\s+)+/,'');
    var toks=l.split(/\s+/).filter(Boolean); if(!toks.length) return null;
    for(var n=Math.min(3,toks.length);n>=1;n--){ var k=toks.slice(0,n).join(' '); if(G[k]) return {key:k, desc:G[k]}; }
    // ./script.sh, ./mvnw
    if(/^\.\/[\w.-]+/.test(toks[0])){ var b=toks[0].replace(/^\.\//,''); if(G[b]) return {key:b, desc:G[b]}; return {key:toks[0], desc:'exécute le script '+toks[0]+' du projet'}; }
    return null;
  }
  function explain(pre, on){
    var code=pre.querySelector('code'); if(!code) return;
    if(!code.dataset.orig) code.dataset.orig=code.textContent;
    if(!on){ code.innerHTML=esc(code.dataset.orig); return; }
    var out=[], lines=code.dataset.orig.split('\n');
    for(var i=0;i<lines.length;i++){
      var line=lines[i]; out.push(esc(line));
      var seen={}; var parts=line.split(/\s(?:\|\||&&|\|)\s/);
      var expl=[];
      parts.forEach(function(p){ var c=cmdOf(p); if(c&&!seen[c.key]){ seen[c.key]=1; expl.push('<b>'+esc(c.key)+'</b> : '+esc(c.desc)); } });
      if(expl.length) out.push('<span class="xpl">'+expl.join(' · ')+'</span>');
      else out.push('');
    }
    code.innerHTML=out.join('\n').replace(/\n\n/g,'\n');
  }
  var pref=false; try{ pref=localStorage.getItem(KEY)==='1'; }catch(e){}
  document.querySelectorAll('pre:not(.diagram)').forEach(function(pre){
    var code=pre.querySelector('code'); if(!code) return;
    // au moins une commande reconnue ?
    var has=code.textContent.split('\n').some(function(l){ return !!cmdOf(l); }); if(!has) return;
    var b=document.createElement('button'); b.type='button'; b.className='explain'; b.textContent='Expliquer';
    b.addEventListener('click',function(){ var on=!b.classList.contains('on'); b.classList.toggle('on',on); b.textContent=on?'Masquer':'Expliquer'; explain(pre,on); try{ localStorage.setItem(KEY,on?'1':'0'); }catch(e){} });
    pre.appendChild(b);
    if(pref){ b.classList.add('on'); b.textContent='Masquer'; explain(pre,true); }
  });
})();
</script>
"""

out = pathlib.Path('/mnt/user-data/outputs')
for f in sorted(out.glob('devops-0*.html')):
    s = f.read_text()
    if 'devops-explain' in s: print(f.name, 'déjà fait'); continue
    s = s.replace('</style>', CSS, 1)
    # la copie doit utiliser le texte d'origine, pas les explications
    old = "var t=pre.innerText.replace(/^Copier\\n?/,'').replace(/Copi\\u00e9 !$/,'');"
    assert old in s, f.name
    s = s.replace(old, "var c0=pre.querySelector('code'); var t=(c0&&c0.dataset.orig)?c0.dataset.orig:pre.innerText.replace(/^Copier\\n?/,'').replace(/Copi\\u00e9 !$/,'').replace(/^(Expliquer|Masquer)\\n?/,'');", 1)
    s = s.replace('</body>', JS.replace('__GLOSSARY__', json.dumps(G, ensure_ascii=False)) + '</body>', 1)
    f.write_text(s); print(f.name, 'ok')
print(len(G), 'entrées de glossaire')

ip = out/'devops-parcours-complet.html'; t = ip.read_text()
if 'Expliquer' not in t:
    t = t.replace('<li><strong>Lecture rapide</strong>', '<li><strong>Expliquer les commandes</strong> : chaque bloc de code a un bouton « Expliquer » qui affiche, sous chaque ligne, ce que fait la commande et ses options (plus de 200 commandes Linux, Git, Docker, Kubernetes, Terraform, Ansible, AWS, Vault, sécurité). Le réglage se mémorise ; « Copier » copie toujours le code sans les explications.</li>\n<li><strong>Lecture rapide</strong>', 1)
    ip.write_text(t); print('index ok')
