"""Planches manga du cours Angular (11 chapitres). Usage : python3 manga13.py <page>"""
import sys, pathlib
sys.path.insert(0, str(pathlib.Path(__file__).parent))
from manga_gabarit import strip3, apply
F = lambda *a: strip3(*a)
STRIPS = [
 ("c1", F("mga1", "l'abonnement éternel", "Angular 1",
   dict(term=["ngOnInit() {", "  this.api.flux$.subscribe(", "    x => this.x = x); }"], bulle=["Je m'abonne,", "c'est tout."]),
   dict(term=["10 ouvertures de la page :", "  10 abonnements actifs", "  mémoire × 10, requêtes × 10"], sfx="×10"),
   "se désabonner sans y penser", ["pipe async dans le template", "takeUntilDestroyed()", "ou toSignal(flux$)", "un abonnement = un cycle de vie"],
   "Un subscribe manuel survit au composant : on laisse le pipe async, takeUntilDestroyed ou toSignal gérer la fin de l'abonnement.")),
 ("c2", F("mga2", "@for sans track pertinent", "Angular 2",
   dict(term=["@for (i of incidents;", "  track $index) {", "  <app-ligne [i]='i' /> }"], bulle=["track $index,", "ça compile."]),
   dict(term=["rafraîchissement de la liste :", "  800 lignes recréées", "  focus et saisies perdus"], rack=False, nuit=False, who='mika', expr='shock', sfx="800"),
   "suivre par identité", ["track i.id", "le DOM est réutilisé", "l'état des lignes survit"],
   "Avec track sur l'index, une liste rechargée recrée tout son DOM : on suit chaque élément par son identifiant et Angular réutilise les lignes.")),
 ("c3", F("mga3", "OnPush ne voit rien", "Angular 3",
   dict(term=["this.incident.statut =", "  'FERME';", "// enfant en OnPush"], bulle=["J'ai changé", "le statut."]),
   dict(term=["l'enfant affiche toujours", "  « OUVERT »", "même référence d'objet"], rack=False, nuit=False, who='kai', expr='shock', sfx="?"),
   "nouvelle référence, ou signal", ["{ ...incident, statut: 'FERME' }", "input() + signal", "OnPush partout, mutation nulle part"],
   "OnPush ne regarde que les références : modifier un objet en place ne rafraîchit pas l'enfant ; on crée une nouvelle référence ou on passe par des signals.")),
 ("c4", F("mga4", "l'effect qui écrit partout", "Angular 4",
   dict(term=["effect(() => {", "  this.total.set(", "    this.items().length); });"], bulle=["Un effect pour", "calculer le", "total."]),
   dict(term=["valeurs intermédiaires", "  affichées, rendus en trop", "et bientôt une boucle"], rack=False, nuit=False, who='mika', expr='angry', pose='hips', sfx="boucle"),
   "dériver, ne pas copier", ["computed() pour une dérivation", "linkedSignal pour un état", "  réinitialisable", "effect : effets de bord seulement"],
   "Un effect qui écrit dans un signal recrée une synchronisation manuelle : une valeur dérivée se déclare avec computed, et l'effect reste réservé aux effets de bord (journal, stockage, DOM).")),
 ("c5", F("mga5", "trois instances du même service", "Angular 5",
   dict(term=["@Component({", "  providers: [PanierService]", "})  // dans 3 composants"], bulle=["Je le fournis", "là où j'en", "ai besoin."]),
   dict(term=["le panier se vide", "  en changeant de page", "trois paniers différents"], rack=False, nuit=False, who='kai', expr='shock', sfx="×3"),
   "choisir la portée", ["@Injectable({ providedIn: 'root' })", "providers locaux : exprès", "une instance = un état"],
   "Chaque providers d'un composant crée une nouvelle instance du service : un état partagé se fournit à la racine, et une portée locale se choisit volontairement.")),
 ("c6", F("mga6", "le guard n'est pas une serrure", "Angular 6",
   dict(term=["canActivate: [adminGuard]", "// la page admin est", "// protégée"], bulle=["Sans le rôle,", "on ne passe pas."]),
   dict(term=["curl -X DELETE", "  /api/incidents/42", "204 No Content"], sfx="204"),
   "le serveur décide", ["guard : confort d'affichage", "l'API vérifie chaque droit", "jeton validé côté serveur", "tests d'autorisation de l'API"],
   "Un guard empêche seulement d'afficher une page : n'importe qui peut appeler l'API directement, donc c'est le serveur qui vérifie chaque autorisation.")),
 ("c7", F("mga7", "le formulaire en any", "Angular 7",
   dict(term=["form = new FormGroup({", "  priorite: new FormControl()", "})  // any"], bulle=["Le typage,", "on verra plus", "tard."]),
   dict(term=["envoyé : priorite: 'P1 '", "  avec un espace", "API : 400, ou pire, accepté"], rack=False, nuit=False, who='mika', expr='angry', pose='hips', sfx="400"),
   "des formulaires typés", ["FormControl<Priorite>(…)", "nonNullable, validateurs", "messages d'erreur accessibles", "validation serveur aussi"],
   "Un formulaire non typé laisse passer n'importe quelle valeur : les formulaires réactifs typés, les validateurs et une validation côté serveur ferment la porte.")),
 ("c8", F("mga8", "NgRx pour trois booléens", "Angular 8",
   dict(term=["actions, reducers, effects,", "  selectors, facade…", "  pour ouvrir un panneau"], bulle=["Comme ça, c'est", "scalable."]),
   dict(term=["une fonctionnalité simple :", "  11 fichiers modifiés", "l'équipe n'ose plus y toucher"], rack=False, nuit=False, who='kai', expr='shock', sfx="11"),
   "l'outil à la taille du besoin", ["service + signals d'abord", "SignalStore si l'état grossit", "Store complet : gros état partagé", "  avec besoin d'historique"],
   "Un store complet pour quelques valeurs ajoute des fichiers sans valeur : on commence par un service à signals, SignalStore ensuite, et le Store classique seulement pour un état large et partagé.")),
 ("c9", F("mga9", "le test qui cherche .btn-primary", "Angular 9",
   dict(term=["fixture.nativeElement", "  .querySelector('.btn-primary')", "  .click();"], bulle=["Ça trouve", "le bouton."]),
   dict(term=["le design change la classe", "  en .btn-accent", "37 tests rouges, rien de cassé"], rack=False, nuit=False, who='mika', expr='angry', pose='hips', sfx="37"),
   "tester comme l'utilisateur", ["harnesses du CDK et Material", "Testing Library : getByRole", "Playwright pour le bout en bout", "pas de sélecteur CSS de style"],
   "Un test accroché aux classes CSS casse à chaque retouche de style : les harnesses et les requêtes par rôle testent ce que l'utilisateur perçoit.")),
 ("c10", F("mga10", "faire confiance au HTML", "Angular 10",
   dict(term=["this.sanitizer", "  .bypassSecurityTrustHtml(", "    commentaire)"], bulle=["Sinon Angular", "enlève le", "gras."]),
   dict(term=["commentaire piégé :", "  <img src=x onerror=…>", "script exécuté chez tous"], sfx="XSS"),
   "garder la protection", ["laisser Angular assainir", "sinon DOMPurify, puis bypass", "CSP et Trusted Types", "revue de chaque bypass"],
   "Angular assainit le HTML par défaut ; bypassSecurityTrustHtml désactive cette protection : on nettoie avant, on ajoute une CSP et Trusted Types, et chaque bypass passe en revue.")),
 ("c11", F("mga11", "des micro-frontends pour une équipe", "Angular 11",
   dict(term=["4 micro-frontends", "  Module Federation", "  une seule équipe de 5"], bulle=["C'est ce que", "font les grands."]),
   dict(term=["Angular 19 ici, 18 là", "  deux versions chargées", "  et un bug de dépendance"], rack=False, nuit=False, who='kai', expr='shock', sfx="×2"),
   "le monorepo d'abord", ["Nx : bibliothèques et frontières", "une version d'Angular", "micro-frontends seulement si", "  plusieurs équipes autonomes"],
   "Les micro-frontends résolvent l'autonomie de plusieurs équipes, pas un problème de code : pour une équipe, un monorepo Nx avec des frontières de bibliothèques suffit.")),
]
if __name__ == '__main__': apply(sys.argv[1], STRIPS)
