"""Planches manga du cours Savoir-être de zéro à expert (10 chapitres). Usage : python3 manga20.py <page>"""
import sys, pathlib
sys.path.insert(0, str(pathlib.Path(__file__).parent))
from manga_gabarit import strip3, apply
F = lambda *a: strip3(*a)
N = dict(rack=False, nuit=False)
STRIPS = [
 ("c1", F("mgse1", "tout lire en une soirée", "Savoir-être 1",
   dict(term=["dimanche soir :", "  les huit paliers lus", "  en deux heures"], bulle=["Voilà,", "je sais tout."]),
   dict(term=["un mois plus tard :", "  mêmes réactions, mêmes", "  réunions, rien n'a changé"], **N, who='kai', expr='shock', sfx="0"),
   "pratiquer, pas lire", ["deux compétences à la fois", "une pratique par semaine", "un observateur qui dit ce qu'il voit", "la grille refaite en fin de trimestre"],
   "Le savoir-être change par répétition observée, pas par lecture : deux compétences à la fois, une pratique par semaine, et quelqu'un qui dit ce qu'il a vu.")),
 ("c2", F("mgse2", "la réponse à chaud", "Savoir-être 2",
   dict(term=["réunion : « ta solution", "  ne tiendra jamais »", "  devant toute l'équipe"], expr='angry', pose='hips', bulle=["Tu n'as rien", "compris !"]),
   dict(term=["le ton monte", "la réunion s'arrête", "deux jours de froid"], **N, who='mika', expr='shock', sfx="froid"),
   "nommer, respirer, questionner", ["« je suis agacé » (dans sa tête)", "une minute avant de répondre", "« qu'est-ce qui te gêne ? »", "répondre sur ce point précis"],
   "Une réaction à chaud crée un second problème : on nomme l'émotion pour soi, on prend une minute, et on commence par une question.")),
 ("c3", F("mgse3", "l'e-mail sans réponse", "Savoir-être 3",
   dict(term=["Objet : point", "  12 lignes d'historique", "  la demande en ligne 11"], bulle=["Tout y est,", "il n'a qu'à", "lire."]),
   dict(term=["une semaine plus tard :", "  aucune réponse", "  la démo est bloquée"], **N, who='kai', expr='shock', sfx="7 j"),
   "la demande d'abord", ["objet précis", "première ligne : ce que j'attends", "trois lignes de contexte", "date de réponse souhaitée"],
   "Un message long cache la demande : l'objet est précis, la première ligne dit ce qu'on attend, et le contexte tient en trois lignes.")),
 ("c4", F("mgse4", "prévenu la veille", "Savoir-être 4",
   dict(term=["mardi : je sais que", "  vendredi ne tiendra pas", "  « je vais rattraper »"], bulle=["Je peux", "encore y", "arriver."]),
   dict(term=["jeudi 19 h : « ce sera", "  lundi finalement »", "le client est déjà prévenu"], **N, who='mika', expr='angry', pose='hips', sfx="jeudi"),
   "prévenir dès qu'on sait", ["le jour même, pas la veille", "faits, nouvelle date", "une option : livrer une partie", "le décideur choisit"],
   "La confiance ne se perd pas sur le retard mais sur la surprise : on prévient dès qu'on sait, avec une nouvelle date et une option.")),
 ("c5", F("mgse5", "trois mois de rancune", "Savoir-être 5",
   dict(term=["le correctif présenté", "  par un collègue", "  comme le sien"], expr='angry', pose='hips', bulle=["Je ne dis rien,", "ça passera."]),
   dict(term=["trois mois après, en réunion :", "  « de toute façon tu voles", "  le travail des autres »"], **N, who='kai', expr='shock', sfx="boum"),
   "en direct, sous 48 heures", ["en privé, sur un fait", "l'impact pour toi", "une demande claire", "« ok pour la prochaine fois ? »"],
   "Un désaccord non dit grossit jusqu'à exploser : on va voir la personne sous 48 heures, en privé, avec un fait, son impact et une demande.")),
 ("c6", F("mgse6", "dix arguments, zéro adhésion", "Savoir-être 6",
   dict(term=["présentation du standard", "  24 diapositives", "  10 arguments"], bulle=["Avec tout ça,", "ils vont", "adhérer."]),
   dict(term=["l'équipe se braque", "  « encore une contrainte »", "  rien ne change"], **N, who='kai', expr='shock', sfx="non"),
   "rendre l'essai facile", ["partir de leur problème", "un fait, une démonstration", "un essai d'un mois, un critère", "décider ensemble ensuite"],
   "Empiler les arguments braque : on part du problème de l'autre, on montre un fait, et on propose un essai court et réversible avec un critère convenu.")),
 ("c7", F("mgse7", "refait pendant la nuit", "Savoir-être 7",
   dict(term=["délégué à Sam :", "  le module de notifications", "  résultat : « pas comme moi »"], bulle=["Je le refais", "ce soir."]),
   dict(term=["le lendemain, Sam découvre", "  son travail réécrit", "  il ne proposera plus rien"], **N, who='mika', expr='shock', sfx="stop"),
   "déléguer un résultat", ["critères de réussite écrits", "points de contrôle convenus", "on ne corrige que ce qui", "  viole un critère"],
   "Reprendre un travail délégué tue l'initiative : on délègue un résultat avec ses critères, et on accepte une solution différente de la sienne si elle les respecte.")),
 ("c8", F("mgse8", "le manager surpris", "Savoir-être 8",
   dict(term=["le projet glisse de 3 semaines", "  « je gère, pas besoin", "  de l'inquiéter »"], bulle=["Je le lui dirai", "quand ce sera", "réglé."]),
   dict(term=["son directeur l'appelle :", "  « pourquoi je l'apprends", "  par le client ? »"], **N, who='mika', expr='angry', pose='hips', sfx="?!"),
   "pas de surprise", ["point hebdomadaire de cinq lignes", "le risque d'abord", "une option avec chaque problème", "dès qu'on sait"],
   "Un manager qui apprend une mauvaise nouvelle par un autre perd confiance : un point hebdomadaire court, le risque en premier, et une option avec chaque problème.")),
 ("c9", F("mgse9", "de 7 h à 22 h", "Savoir-être 9",
   dict(term=["trois semaines de rush", "  connecté de 7 h à 22 h", "  « c'est temporaire »"], bulle=["Je tiens,", "ça va."]),
   dict(term=["erreurs en série", "  irritable en réunion", "  arrêt maladie en mars"], **N, who='kai', expr='shock', sfx="stop"),
   "des règles qui tiennent", ["limites horaires écrites", "dire la surcharge avec des faits", "en parler tôt à quelqu'un", "récupérer après chaque rush"],
   "La durée se gère avec des règles tenues : limites horaires, surcharge dite avec des faits, et une personne à qui en parler avant qu'il soit trop tard.")),
 ("c10", F("mgse10", "4 sur 4 partout", "Savoir-être 10",
   dict(term=["auto-évaluation :", "  8 compétences", "  8 fois « expert »"], bulle=["Je me connais", "bien."]),
   dict(term=["deux collègues notent :", "  collaborer : 2, diriger : 2", "  écart de deux points"], **N, who='kai', expr='shock', sfx="écart"),
   "l'écart est le travail", ["faire noter par deux personnes", "demander deux exemples", "choisir l'écart le plus grand", "un observateur pour ce point"],
   "Une auto-évaluation flatteuse ne sert à rien : l'écart entre sa note et celle des autres désigne la compétence à travailler en premier.")),
]
if __name__ == '__main__': apply(sys.argv[1], STRIPS)
