"""Planches manga du cours Data Platform, AWS, Talend, Airflow (15 chapitres). Usage : python3 manga19.py <page>"""
import sys, pathlib
sys.path.insert(0, str(pathlib.Path(__file__).parent))
from manga_gabarit import strip3, apply
F = lambda *a: strip3(*a)
N = dict(rack=False, nuit=False)
STRIPS = [
 ("c1", F("mgd1", "le lac devenu marécage", "Data 1",
   dict(term=["s3://data-lake/", "  export_final_v3.csv", "  export_final_v3_bis.csv"], bulle=["On range", "plus tard."]),
   dict(term=["2 ans après : 40 000 fichiers", "  aucun propriétaire", "  quel chiffre est le bon ?"], **N, who='mika', expr='shock', sfx="?"),
   "des zones et des propriétaires", ["brut, nettoyé, exposé", "un propriétaire par jeu", "catalogue et lignage", "contrats de données"],
   "Un lac sans structure devient un marécage : zones brute, nettoyée et exposée, un propriétaire par jeu de données, un catalogue et des contrats entre producteurs et consommateurs.")),
 ("c2", F("mgd2", "CloudTrail désactivé", "Data 2",
   dict(term=["CloudTrail : désactivé", "  « trop de logs »", "KMS : clé par défaut partout"], bulle=["On économise", "un peu."]),
   dict(term=["bucket vidé cette nuit", "qui ? depuis où ?", "aucune trace"], sfx="?"),
   "tracer et chiffrer", ["CloudTrail multi-région", "journal immuable, autre compte", "KMS : clés par domaine", "Secrets Manager, rotation"],
   "Sans journal d'audit, un incident ne s'explique pas : CloudTrail sur toutes les régions vers un compte séparé, des clés KMS par domaine, et des secrets à rotation automatique.")),
 ("c3", F("mgd3", "le disque plein à 3 h", "Data 3",
   dict(term=["EC2 du job Talend", "  /var/log sans rotation", "  df -h : 97 %"], bulle=["Il reste", "de la place."]),
   dict(term=["03 h 00 : No space left", "  le job s'arrête à moitié", "  données partielles chargées"], sfx="100 %"),
   "prévenir, pas constater", ["logrotate configuré", "alerte à 80 % du disque", "volume séparé pour les données", "reprise idempotente du job"],
   "Un disque plein arrête les jobs au pire moment : rotation des journaux, alerte à 80 %, volume dédié aux données, et des jobs qui reprennent sans doublon.")),
 ("c4", F("mgd4", "le SELECT * qui scanne tout", "Data 4",
   dict(term=["SELECT * FROM ventes", "  WHERE date_vente >", "  now() - interval '1 day'"], bulle=["Une petite", "requête du", "matin."]),
   dict(term=["EXPLAIN : Seq Scan", "  sur 800 millions de lignes", "  12 minutes, base saturée"], sfx="Seq Scan"),
   "lire le plan", ["EXPLAIN (ANALYZE, BUFFERS)", "index sur la colonne filtrée", "partitionnement par date", "colonnes utiles seulement"],
   "Une requête simple peut parcourir toute la table : EXPLAIN montre le plan, un index ou un partitionnement par date évite le parcours complet, et on ne lit que les colonnes utiles.")),
 ("c5", F("mgd5", "max_connections atteint", "Data 5",
   dict(term=["30 jobs Talend en parallèle", "  20 connexions chacun", "  Aurora : max 500"], bulle=["Aurora", "encaisse tout."]),
   dict(term=["FATAL: too many connections", "  l'application métier aussi", "  est refusée"], sfx="FATAL"),
   "partager les connexions", ["RDS Proxy ou PgBouncer", "pools dimensionnés par job", "files et fenêtres de batch", "surveiller les connexions actives"],
   "PostgreSQL ouvre un processus par connexion : un proxy de connexions et des pools dimensionnés évitent que les traitements batch bloquent l'application.")),
 ("c6", F("mgd6", "le scan DynamoDB", "Data 6",
   dict(term=["table DynamoDB : 200 Go", "rapport : Scan complet", "  chaque heure"], bulle=["Scan, c'est", "comme SELECT."]),
   dict(term=["capacité consommée ×40", "  throttling de l'application", "  facture multipliée"], **N, who='kai', expr='shock', sfx="×40"),
   "modéliser pour la requête", ["clés conçues pour les accès", "Query plutôt que Scan", "index secondaire si besoin", "export S3 pour l'analytique"],
   "DynamoDB se modélise à partir des requêtes : on interroge par clé, on ajoute des index pour les autres accès, et l'analytique passe par un export vers S3 ou Redshift.")),
 ("c7", F("mgd7", "un index par jour, pour toujours", "Data 7",
   dict(term=["logs-2026.01.01", "logs-2026.01.02 …", "  aucune politique de cycle"], bulle=["Elasticsearch", "gère."]),
   dict(term=["3 600 shards sur 3 nœuds", "cluster en rouge", "  mémoire saturée"], sfx="rouge"),
   "maîtriser le cycle de vie", ["ILM : hot, warm, delete", "shards de 20 à 50 Go", "rollover par taille", "Druid pour l'agrégat"],
   "Des index quotidiens sans politique multiplient les shards jusqu'à la saturation : une politique de cycle de vie, un rollover par taille et des shards bien dimensionnés gardent le cluster sain.")),
 ("c8", F("mgd8", "le mot de passe dans le job", "Data 8",
   dict(term=["tPostgresqlInput :", "  password = \"Prod2026!\"", "  en dur dans le job"], bulle=["Ça marche du", "premier coup."]),
   dict(term=["job exporté, partagé", "  mot de passe de production", "  dans le dépôt de l'équipe"], sfx="fuite"),
   "des contextes, jamais en dur", ["variables de contexte", "valeurs par environnement", "secret lu à l'exécution", "revue : zéro chaîne en dur"],
   "Un identifiant saisi dans un composant voyage avec chaque export du job : les connexions passent par des variables de contexte, alimentées à l'exécution depuis un coffre.")),
 ("c9", F("mgd9", "le job de 400 composants", "Data 9",
   dict(term=["job_chargement_global", "  412 composants", "  un seul développeur le connaît"], bulle=["Tout est au", "même endroit."]),
   dict(term=["le développeur part", "  le job échoue en prod", "  personne n'ose l'ouvrir"], **N, who='mika', expr='shock', sfx="412"),
   "découper et relire", ["jobs enfants par étape", "joblets pour le réutilisable", "conventions de nommage", "revue de code Tech Lead"],
   "Un job géant ne se relit ni ne se maintient : on le découpe en jobs enfants, on factorise en joblets, et une revue de code vérifie nommage, gestion d'erreurs et contextes.")),
 ("c10", F("mgd10", "déployé à la main sur le Job Server", "Data 10",
   dict(term=["export du job en zip", "  copié sur le Job Server", "  par le Bureau à distance"], bulle=["Rapide et", "efficace."]),
   dict(term=["prod ≠ recette ≠ Git", "  quelle version tourne ?", "  personne ne sait"], sfx="?"),
   "livrer par la chaîne", ["build CI depuis Git", "artefact versionné (Nexus)", "publication via TAC / API", "même artefact partout"],
   "Un job copié à la main rend les versions invérifiables : la CI construit depuis Git, publie un artefact versionné, et le TAC déploie ce même artefact dans chaque environnement.")),
 ("c11", F("mgd11", "le DAG qui ne s'arrête plus", "Data 11",
   dict(term=["retries = 50", "retry_delay = 1 min", "tâche non idempotente"], bulle=["Il finira", "par passer."]),
   dict(term=["50 exécutions partielles", "  données chargées 23 fois", "  rapports faux"], sfx="×23"),
   "des tâches rejouables", ["tâches idempotentes", "2 ou 3 retries, backoff", "SLA et alertes par tâche", "catchup maîtrisé"],
   "Relancer une tâche non idempotente multiplie les données : chaque tâche doit pouvoir être rejouée sans effet de bord, avec peu de tentatives espacées et une alerte en cas d'échec.")),
 ("c12", F("mgd12", "le job sans limite mémoire", "Data 12",
   dict(term=["Pod du job Talend :", "  resources: {}", "  « la JVM s'adapte »"], bulle=["Pas de limite,", "pas de", "problème."]),
   dict(term=["le job prend 14 Go", "  nœud saturé", "  l'API voisine expulsée"], sfx="OOM"),
   "dimensionner et isoler", ["requests et limits posées", "-XX:MaxRAMPercentage=75", "nœuds dédiés aux batchs", "tableau de bord par job"],
   "Un job sans limite consomme tout le nœud et fait expulser ses voisins : requests et limites, une JVM réglée sur la mémoire du conteneur, et des nœuds dédiés aux traitements lourds.")),
 ("c13", F("mgd13", "l'incident sans runbook", "Data 13",
   dict(term=["03 h : chargement en échec", "astreinte : nouveau venu", "documentation : aucune"], bulle=["Je relance", "et je vois."]),
   dict(term=["trois relances à l'aveugle", "  doublons en base", "  rapport de 8 h faux"], sfx="×3"),
   "un runbook par alerte", ["symptôme, cause probable", "vérifications dans l'ordre", "action sûre, escalade", "post-mortem et mise à jour"],
   "Sans runbook, l'astreinte improvise et aggrave : chaque alerte renvoie à une procédure qui dit quoi vérifier, quelle action est sûre, et à qui escalader.")),
 ("c14", F("mgd14", "le self-service sans garde-fous", "Data 14",
   dict(term=["portail self-service :", "  « crée ta base »", "  aucune règle"], bulle=["Les équipes", "sont autonomes."]),
   dict(term=["6 mois : 140 bases", "  12 publiques, 0 sauvegarde", "  aucun propriétaire"], sfx="140"),
   "l'autonomie encadrée", ["modules Terraform validés", "politiques as code (OPA)", "étiquettes obligatoires", "sauvegarde et chiffrement inclus"],
   "Le self-service sans règles produit des ressources non sécurisées et orphelines : on offre des modules validés qui incluent sauvegarde, chiffrement et étiquettes, contrôlés par des politiques.")),
 ("c15", F("mgd15", "réciter les services", "Data 15",
   dict(term=["entretien Tech Lead Data :", "  « S3, Glue, Redshift,", "  Athena, EMR, Kinesis… »"], bulle=["Je connais", "tout AWS."]),
   dict(term=["« racontez un incident de", "  production que vous avez", "  résolu » … silence"], **N, who='kai', expr='shock', sfx="…"),
   "raconter une situation", ["contexte et enjeu", "diagnostic, étape par étape", "décision et arbitrage", "résultat chiffré, leçon"],
   "Un recruteur de Tech Lead Data cherche un raisonnement, pas un catalogue : un incident réel, le diagnostic, la décision, le résultat chiffré et ce qui a changé ensuite.")),
]
if __name__ == '__main__': apply(sys.argv[1], STRIPS)
