"""Planches manga du cours Assistants IA (9 chapitres). Usage : python3 manga27.py <page>"""
import sys, pathlib
sys.path.insert(0, str(pathlib.Path(__file__).parent))
from manga_gabarit import strip3, apply
F = lambda *a: strip3(*a)
N = dict(rack=False, nuit=False)
STRIPS = [
 ("c1", F("mgas1", "accepté sans lire", "Assistants 1",
   dict(term=["suggestion acceptée : Tab", "  méthode de 40 lignes", "  pas relue"], bulle=["Il sait mieux", "que moi."]),
   dict(term=["production :", "  API inexistante appelée", "  NoSuchMethodError"], sfx="erreur"),
   "tu restes responsable", ["comprendre chaque ligne", "compiler et tester", "vérifier les API", "relecture de MR"],
   "Une suggestion acceptée sans la comprendre devient ton code, avec ses erreurs : on comprend, on compile, on teste et on relit, comme pour tout le reste.")),
 ("c2", F("mgas2", "écris-moi l'application", "Assistants 2",
   dict(term=["« écris-moi une API", "  de gestion d'incidents »", "  (aucun contexte)"], bulle=["Il va tout", "faire."]),
   dict(term=["code générique", "  autre framework, autre modèle", "  tout à refaire"], **N, who='kai', expr='shock', sfx="à refaire"),
   "contexte et plan d'abord", ["pile et code existant", "contraintes et critères", "plan avant le code", "étapes testées"],
   "Une demande vague donne un code générique : on donne le contexte, les contraintes et le critère d'acceptation, et on demande un plan avant le code.")),
 ("c3", F("mgas3", "la clé proposée", "Assistants 3",
   dict(term=["application.yml :", "  suggestion : api-key:", "  sk-live-…"], bulle=["Pratique, il", "a complété."]),
   dict(term=["fusionné, poussé", "  clé réelle exposée", "  dans l'historique Git"], sfx="clé"),
   "aucun secret dans le code", ["variables ou coffre", "détection de secrets en CI", "fichiers sensibles exclus", "révoquer si exposé"],
   "Un assistant peut compléter un secret plausible ou réel : les secrets viennent de l'environnement ou d'un coffre, et la CI détecte ceux qui passent.")),
 ("c4", F("mgas4", "l'agent sans garde-fous", "Assistants 4",
   dict(term=["agent de code :", "  toutes permissions", "  sur la branche main"], bulle=["Il ira plus", "vite seul."]),
   dict(term=["« nettoyer les fichiers »", "  rm -rf data/", "  poussé sur main"], sfx="rm"),
   "des limites fixées", ["branche dédiée, conteneur", "commandes sensibles confirmées", "hooks de blocage", "MR relue"],
   "Un agent sans limites peut exécuter une commande destructrice : il travaille sur une branche, en conteneur, avec des permissions restreintes et des automatismes de blocage.")),
 ("c5", F("mgas5", "quarante fichiers collés", "Assistants 5",
   dict(term=["chat : 40 fichiers", "  copiés-collés un par un", "  « refactore tout »"], bulle=["Ça rentrera", "bien."]),
   dict(term=["contexte tronqué", "  réponses incohérentes", "  3 heures perdues"], **N, who='mika', expr='angry', pose='hips', sfx="3 h"),
   "le bon outil", ["agent qui lit le dépôt", "tâche découpée", "une étape à la fois", "tests entre chaque étape"],
   "La conversation n'est pas faite pour refactorer un dépôt entier : un agent qui lit le dépôt, avec des étapes courtes et testées, fait mieux et plus vite.")),
 ("c6", F("mgas6", "le legacy réécrit d'un coup", "Assistants 6",
   dict(term=["« réécris le module", "  Struts en Spring »", "  2 000 lignes générées"], bulle=["Ça compile !"]),
   dict(term=["recette : 3 écrans", "  au comportement changé", "  aucun test pour le voir"], sfx="×3"),
   "comprendre, figer, changer", ["faire expliquer d'abord", "tests de caractérisation", "un écran à la fois", "mêmes tests avant et après"],
   "« Ça compile » ne veut pas dire « ça marche pareil » : on fige le comportement par des tests de caractérisation, puis on migre écran par écran.")),
 ("c7", F("mgas7", "le code client dans un chatbot public", "Assistants 7",
   dict(term=["code du client X", "  + extrait de base réel", "  collés dans un outil grand public"], bulle=["C'est plus", "rapide."]),
   dict(term=["audit du client :", "  clause de confidentialité", "  et données personnelles"], **N, who='mika', expr='shock', sfx="audit"),
   "l'outil autorisé, rien d'autre", ["outil sous contrat d'entreprise", "données fictives ou anonymisées", "accord du client si besoin", "politique d'équipe écrite"],
   "Le code et les données d'un client ne partent que vers un outil autorisé par le contrat : outil d'entreprise, données anonymisées, et accord en cas de doute.")),
 ("c8", F("mgas8", "des licences pour tous, une méthode pour personne", "Assistants 8",
   dict(term=["500 licences achetées", "  aucune formation", "  aucune mesure"], who='sensei', expr='neutral', pose='stand', bulle=["Ils vont", "voler."]),
   dict(term=["trois mois après :", "  résultats inégaux", "  deux incidents non relus"], **N, who='kai', expr='shock', sfx="?"),
   "piloter et mesurer", ["pilote avec deux équipes", "conventions dans les dépôts", "formation courte", "mesures avant et après"],
   "Les licences seules ne produisent rien : un pilote, des conventions, une formation et des mesures font la différence, et la relecture reste obligatoire.")),
 ("c9", F("mgas9", "« c'est l'IA qui l'a écrit »", "Assistants 9",
   dict(term=["entretien technique :", "  « expliquez ce code", "  de votre portfolio »"], bulle=["C'est l'IA", "qui l'a écrit."]),
   dict(term=["le recruteur note :", "  « ne maîtrise pas", "  son propre code »"], **N, who='mika', expr='shock', sfx="…"),
   "posséder son code", ["expliquer chaque choix", "dire ce qui a été corrigé", "montrer des mesures", "petits pas, preuves"],
   "Un code livré avec un assistant reste ton code : tu dois pouvoir l'expliquer, dire ce que tu as corrigé, et montrer ce que ça a apporté.")),
]
if __name__ == '__main__': apply(sys.argv[1], STRIPS)
