"""Planches manga du cours Microservices (13 chapitres). Usage : python3 manga22.py <page>"""
import sys, pathlib
sys.path.insert(0, str(pathlib.Path(__file__).parent))
from manga_gabarit import strip3, apply
F = lambda *a: strip3(*a)
N = dict(rack=False, nuit=False)
STRIPS = [
 ("c1", F("mgm1", "douze services pour quatre", "Microservices 1",
   dict(term=["équipe : 4 développeurs", "services : 12", "pipelines : 12, astreintes : 12"], bulle=["C'est moderne,", "c'est scalable."]),
   dict(term=["une fonctionnalité :", "  5 services modifiés", "  3 semaines de coordination"], **N, who='kai', expr='shock', sfx="×5"),
   "commencer modulaire", ["un monolithe modulaire", "frontières vérifiées en CI", "extraire sur critères mesurés", "pas avant l'observabilité"],
   "Des microservices sans équipes pour les porter multiplient le travail : on commence par un monolithe modulaire, et on extrait un service quand un critère mesurable le justifie.")),
 ("c2", F("mgm2", "découpé par couches", "Microservices 2",
   dict(term=["services : ihm, metier,", "  donnees", "« comme les couches du code »"], bulle=["C'est bien", "rangé."]),
   dict(term=["ajouter un champ « zone » :", "  3 services, 3 MR,", "  3 déploiements synchronisés"], **N, who='mika', expr='angry', pose='hips', sfx="×3"),
   "découper par métier", ["un service par bounded context", "incidents, mobilisation, alertes", "chacun : API, logique, données", "le vocabulaire trace la frontière"],
   "Un découpage par couches techniques fait toucher tous les services à chaque fonctionnalité : on découpe par capacité métier, chaque service portant son interface, sa logique et ses données.")),
 ("c3", F("mgm3", "cinq appels en chaîne", "Microservices 3",
   dict(term=["page tableau de bord :", "  A → B → C → D → E", "  chacun à 99,9 %"], bulle=["Chaque service", "est fiable."]),
   dict(term=["disponibilité : 99,5 %", "latence : 200 ms × 5", "D ralentit : tout ralentit"], sfx="×5"),
   "limiter le synchrone", ["appels en parallèle, délais", "vue locale par événements", "cache pour le lent qui change peu", "jamais de chaîne profonde"],
   "Des appels synchrones en chaîne multiplient les indisponibilités et additionnent les latences : on parallélise, on met en cache, ou on maintient une vue locale alimentée par événements.")),
 ("c4", F("mgm4", "la notification envoyée deux fois", "Microservices 4",
   dict(term=["@KafkaListener", "void surEvenement(e) {", "  envoyerSms(e); }"], bulle=["Kafka livre", "le message,", "c'est simple."]),
   dict(term=["rééquilibrage du groupe", "  le lot est relu", "  200 SMS envoyés deux fois"], sfx="×2"),
   "consommer sans doublon", ["identifiant d'événement mémorisé", "dans la même transaction", "topic d'échec surveillé", "clé = identifiant d'incident"],
   "Kafka livre au moins une fois : un consommateur qui ne mémorise pas ce qu'il a traité rejoue ses effets ; l'identifiant d'événement enregistré dans la même transaction rend le traitement idempotent.")),
 ("c5", F("mgm5", "la base partagée", "Microservices 5",
   dict(term=["incidents et mobilisation", "  lisent la même table", "  equipe_affectee"], bulle=["Plus simple", "qu'une API."]),
   dict(term=["mobilisation renomme", "  une colonne", "incidents tombe en prod"], sfx="SQL"),
   "chacun ses données", ["une base ou un schéma par service", "partage par API ou événements", "outbox pour publier", "saga pour les étapes multiples"],
   "Une table partagée est un contrat invisible : un renommage casse un autre service ; chaque service possède ses données et les partage par API ou par événements publiés avec l'outbox.")),
 ("c6", F("mgm6", "le JOIN impossible", "Microservices 6",
   dict(term=["rapport mensuel :", "  appeler 4 services", "  pour 50 000 incidents"], bulle=["On boucle", "sur les API."]),
   dict(term=["200 000 appels", "  délais dépassés partout", "  le rapport ne sort jamais"], sfx="timeout"),
   "une vue pour lire", ["projection des événements", "table taillée pour le rapport", "cohérente à terme, datée", "reconstructible en rejouant"],
   "Une requête qui traverse plusieurs services ne se fait pas en bouclant sur leurs API : une vue de lecture alimentée par leurs événements répond en une requête locale.")),
 ("c7", F("mgm7", "la tempête de tentatives", "Microservices 7",
   dict(term=["chaque niveau réessaie", "  3 fois, sans attente", "  3 niveaux d'appels"], bulle=["Les nouvelles", "tentatives, ça", "sécurise."]),
   dict(term=["Alertes ralentit 30 s", "  charge × 27", "  10 minutes de panne"], sfx="×27"),
   "se protéger sans aggraver", ["délai à chaque appel", "tentatives à un seul niveau", "recul exponentiel et aléa", "disjoncteur et cloison"],
   "Des nouvelles tentatives à chaque niveau multiplient la charge sur un service déjà en difficulté : délais partout, tentatives à un seul niveau avec recul et aléa, disjoncteur pour laisser respirer.")),
 ("c8", F("mgm8", "la passerelle qui fait du métier", "Microservices 8",
   dict(term=["passerelle :", "  calcul des priorités,", "  règles d'escalade"], bulle=["Comme ça, c'est", "fait une fois."]),
   dict(term=["chaque règle métier", "  passe par l'équipe passerelle", "  file d'attente : 6 semaines"], **N, who='mika', expr='angry', pose='hips', sfx="6 sem."),
   "une passerelle fine", ["routage, jeton, débit, traces", "le métier dans les services", "un BFF par client", "aucune règle dupliquée"],
   "Une passerelle qui porte du métier devient un monolithe central : elle route, vérifie les jetons et limite le débit, et les règles restent dans les services.")),
 ("c9", F("mgm9", "le jeton qui ouvre tout", "Microservices 9",
   dict(term=["services internes :", "  « on fait confiance", "  à la passerelle »"], bulle=["Le réseau", "interne est sûr."]),
   dict(term=["un Pod compromis", "  rejoue le jeton utilisateur", "  vers tous les services"], sfx="accès"),
   "vérifier partout", ["audience vérifiée par service", "échange de jeton par appel", "mTLS strict", "NetworkPolicy par service"],
   "Un réseau interne n'est pas une frontière de confiance : chaque service valide le jeton et son audience, les appels passent par l'échange de jeton, et le mTLS avec les politiques réseau limite les chemins.")),
 ("c10", F("mgm10", "où est passée la requête ?", "Microservices 10",
   dict(term=["incident client à 14 h", "  9 services concernés", "  aucune trace distribuée"], bulle=["Je grep", "les logs."]),
   dict(term=["3 heures plus tard :", "  9 journaux ouverts", "  cause toujours inconnue"], **N, who='kai', expr='shock', sfx="3 h"),
   "une trace de bout en bout", ["OpenTelemetry sur chaque service", "traceparent en HTTP et Kafka", "traceId dans chaque journal", "SLO par parcours"],
   "Sans trace distribuée, diagnostiquer une requête qui traverse neuf services prend des heures : OpenTelemetry propage le contexte partout et relie traces, métriques et journaux.")),
 ("c11", F("mgm11", "l'environnement d'intégration partagé", "Microservices 11",
   dict(term=["env-integration :", "  12 services, 5 équipes", "  cassé 2 jours sur 3"], bulle=["On teste tout", "ensemble, c'est", "plus sûr."]),
   dict(term=["mise en production bloquée", "  « qui a cassé l'intégration ? »", "  personne ne sait"], **N, who='mika', expr='shock', sfx="bloqué"),
   "tester sans dépendre des autres", ["tests de composant, Testcontainers", "contrats Pact en CI", "can-i-deploy avant de livrer", "peu de bout en bout"],
   "Un environnement d'intégration partagé est toujours cassé : chaque service se teste comme un composant, les accords entre services se prouvent par contrats, et can-i-deploy bloque ce qui casserait.")),
 ("c12", F("mgm12", "le déploiement synchronisé", "Microservices 12",
   dict(term=["release du jeudi :", "  6 services ensemble", "  dans un ordre précis"], bulle=["Sinon ça", "casse."]),
   dict(term=["un service échoue", "  les 5 autres reviennent", "  en arrière aussi"], sfx="×6"),
   "déployer seul, à tout moment", ["compatibilité N-1", "expand / contract", "contrats vérifiés en CI", "canary avec analyse"],
   "Des services qu'il faut déployer ensemble ne sont pas autonomes : chaque changement reste compatible avec la version précédente, et les contrats le vérifient avant chaque livraison.")),
 ("c13", F("mgm13", "tout réécrire en microservices", "Microservices 13",
   dict(term=["plan : réécrire le monolithe", "  en 20 services", "  livraison dans un an"], who='sensei', expr='neutral', pose='stand', bulle=["On repart", "de zéro."]),
   dict(term=["18 mois plus tard :", "  40 % réécrit", "  le monolithe évolue encore"], **N, who='kai', expr='shock', sfx="18 mois"),
   "étrangler, route par route", ["passerelle devant le monolithe", "un contexte peu couplé d'abord", "CDC pour les données", "retour arrière à chaque étape"],
   "Une réécriture complète court après un métier qui change : la passerelle bascule une route après l'autre vers les nouveaux services, et chaque étape reste réversible.")),
]
if __name__ == '__main__': apply(sys.argv[1], STRIPS)
