"""Planches manga du cours Savoir-être : situations et attitudes (12 chapitres). Usage : python3 manga21.py <page>"""
import sys, pathlib
sys.path.insert(0, str(pathlib.Path(__file__).parent))
from manga_gabarit import strip3, apply
F = lambda *a: strip3(*a)
N = dict(rack=False, nuit=False)
STRIPS = [
 ("c1", F("mgsa1", "« c'est nul »", "Situations 1",
   dict(term=["revue du pipeline de Léa", "  « franchement, c'est nul »", "  devant l'équipe"], bulle=["Je dis juste", "la vérité."]),
   dict(term=["Léa ne présente plus rien", "  l'équipe se tait", "  plus personne ne relit"], **N, who='mika', expr='shock', sfx="silence"),
   "un fait et son impact", ["situation : hier, en revue", "comportement : le build de 12 min", "impact : on attend, on contourne", "demande : cache des dépendances"],
   "« C'est nul » est une opinion qui blesse sans aider : on décrit la situation, le comportement observé, son impact, et on formule une demande.")),
 ("c2", F("mgsa2", "vingt commentaires, vingt justifications", "Situations 2",
   dict(term=["revue de ma MR :", "  20 commentaires secs", "  « je vais répondre à tout »"], expr='angry', pose='hips', bulle=["Il n'a rien", "compris à mon", "code."]),
   dict(term=["40 messages échangés", "  deux jours de ping-pong", "  la MR bloquée"], **N, who='mika', expr='shock', sfx="40"),
   "trier, corriger, parler", ["bloquant : corrigé tout de suite", "mineur : corrigé ou noté", "opinion : règle d'équipe", "désaccord : 10 min de vive voix"],
   "Une revue sèche parle du code : on trie les commentaires, on corrige le bloquant, et on règle le reste de vive voix plutôt qu'en quarante messages.")),
 ("c3", F("mgsa3", "« ça fait longtemps »", "Situations 3",
   dict(term=["entretien annuel :", "  « ça fait trois ans,", "  j'aimerais une augmentation »"], bulle=["Je le mérite,", "non ?"]),
   dict(term=["« pas de budget cette année »", "  aucun élément à défendre", "  pour ton manager"], **N, who='kai', expr='shock', sfx="non"),
   "une demande préparée", ["réalisations chiffrées de l'année", "le marché pour ton profil", "un montant et une date", "en parler avant l'entretien"],
   "Une demande sur le ressenti ne donne rien à défendre : on arrive avec des faits chiffrés, le marché, un montant, une date, et on en parle en amont.")),
 ("c4", F("mgsa4", "deux semaines de débat", "Situations 4",
   dict(term=["Kafka ou RabbitMQ ?", "  deux seniors s'opposent", "  depuis 14 jours"], bulle=["Laissons-les", "converger."]),
   dict(term=["l'équipe attend", "  le sprint est perdu", "  les deux sont épuisés"], **N, who='mika', expr='angry', pose='hips', sfx="14 j"),
   "trancher avec des critères", ["critères écrits : charge, coût", "un prototype chacun, 3 jours", "décision datée, une ADR", "réévaluation dans 3 mois"],
   "Ne pas trancher est la pire décision : critères écrits, un prototype par option, une date de décision et une ADR qui dit quand on la réévaluera.")),
 ("c5", F("mgsa5", "« on va essayer »", "Situations 5",
   dict(term=["le PO : « pour vendredi,", "  les trois fonctionnalités ? »", "estimation : 8 jours"], bulle=["On va", "essayer."]),
   dict(term=["vendredi : une livrée", "  deux en retard", "  l'équipe a fait des nuits"], **N, who='kai', expr='shock', sfx="1 / 3"),
   "des options chiffrées", ["« tout : 8 jours »", "« vendredi : A et B, sans C »", "« ou tout, sans tests, déconseillé »", "le décideur choisit"],
   "« On va essayer » transforme une impossibilité en promesse : on donne l'estimation, deux options réalistes, et on laisse le décideur choisir.")),
 ("c6", F("mgsa6", "six mois sans en parler", "Situations 6",
   dict(term=["Sam livre peu, se trompe", "  depuis janvier", "  « ça va s'arranger »"], who='mika', expr='smile', pose='stand', bulle=["Je ne veux pas", "le froisser."]),
   dict(term=["juin : les RH demandent", "  pourquoi rien n'est écrit", "  Sam tombe des nues"], **N, who='mika', expr='shock', sfx="juin"),
   "tôt, factuel, suivi", ["1:1 dédié, faits récents", "écouter la cause", "attentes écrites, six semaines", "point chaque semaine"],
   "Éviter une conversation difficile est une faute de management : on en parle tôt, sur des faits, on écoute la cause, et on fixe des attentes écrites avec un suivi.")),
 ("c7", F("mgsa7", "annoncé par e-mail", "Situations 7",
   dict(term=["vendredi 18 h 45 :", "  « réorganisation, votre équipe", "  est scindée lundi »"], who='mika', expr='smile', pose='stand', bulle=["Comme ça,", "ils ont le", "week-end."]),
   dict(term=["lundi : colère, rumeurs", "  deux démissions en préparation", "  confiance perdue"], **N, who='mika', expr='shock', sfx="lundi"),
   "en personne, et vite", ["annonce en équipe, puis en 1:1", "ce qui est décidé", "ce qui ne l'est pas encore", "date du prochain point"],
   "Une mauvaise nouvelle se dit en personne, tôt, avec ce qui est décidé et ce qui ne l'est pas, puis un rendez-vous pour les questions.")),
 ("c8", F("mgsa8", "« on en reparle au prochain comité »", "Situations 8",
   dict(term=["comité de direction :", "  choix du fournisseur cloud", "  reporté pour la 3e fois"], who='sensei', expr='neutral', pose='stand', bulle=["Il nous manque", "des éléments."]),
   dict(term=["six mois d'attente", "  deux équipes bloquées", "  le budget expire"], **N, who='kai', expr='shock', sfx="×3"),
   "décider à 60 %", ["critères et date fixés d'avance", "deux options chiffrées", "décision, puis explication", "réévaluation à six mois"],
   "Attendre toute l'information bloque tout le monde : critères et date posés à l'avance, deux options chiffrées, une décision expliquée et une réévaluation prévue.")),
 ("c9", F("mgsa9", "« donnez-moi un nom »", "Situations 9",
   dict(term=["après l'incident :", "  le directeur veut", "  « le responsable »"], who='sensei', expr='neutral', pose='stand', bulle=["Qui a fait", "ça ?"]),
   dict(term=["un nom est donné", "  l'équipe cache désormais", "  ses erreurs"], **N, who='mika', expr='shock', sfx="silence"),
   "protéger et corriger", ["« trois garde-fous manquaient »", "« voilà les actions, datées »", "« le responsable, c'est moi :", "  c'est mon équipe »"],
   "Désigner un coupable garantit le silence au prochain incident : le manager présente les garde-fous manquants, les actions, et prend la responsabilité pour son équipe.")),
 ("c10", F("mgsa10", "la réunion qui dérape", "Situations 10",
   dict(term=["réunion d'architecture :", "  « toi, tu n'as jamais", "  rien livré de stable »"], who='mika', expr='angry', pose='hips', bulle=["Et toi,", "alors ?"]),
   dict(term=["le ton monte", "  plus personne ne parle", "  du sujet"], **N, who='kai', expr='shock', sfx="stop"),
   "recadrer calmement", ["« on s'arrête »", "« le sujet : la migration »", "« on en parle à trois après »", "point suivant"],
   "Quand une réunion glisse vers les personnes, on l'arrête calmement, on ramène au sujet, et on traite le conflit en privé ensuite.")),
 ("c11", F("mgsa11", "« pendant que tu y es »", "Situations 11",
   dict(term=["le client : « pendant que", "  tu y es, ajoute l'export", "  et le SSO »"], bulle=["Je ne veux pas", "le froisser."]),
   dict(term=["+12 jours non facturés", "  la mission déborde", "  le livrable principal glisse"], **N, who='kai', expr='shock', sfx="+12 j"),
   "rattacher au cadrage", ["« bonne idée, hors cadrage »", "avenant de X jours", "ou à la place de Y", "le client choisit"],
   "Accepter gratuitement chaque ajout fait dériver la mission : on reconnaît l'intérêt, on rappelle le cadrage, et on propose un avenant ou un arbitrage.")),
 ("c12", F("mgsa12", "« trop perfectionniste »", "Situations 12",
   dict(term=["entretien : « votre", "  principal défaut ? »", "  « je suis trop perfectionniste »"], bulle=["Réponse", "classique !"]),
   dict(term=["le recruteur note :", "  « réponse préparée,", "  aucune lucidité »"], **N, who='mika', expr='shock', sfx="…"),
   "un vrai défaut, un vrai progrès", ["« je répondais à chaud »", "« depuis un an, je prends une heure »", "« la semaine dernière, en revue… »", "ce que ça a changé"],
   "Un faux défaut signale une réponse apprise : on cite un vrai défaut, la pratique mise en place et un exemple récent de progrès.")),
]
if __name__ == '__main__': apply(sys.argv[1], STRIPS)
