"""Planches manga du cours Alibaba Cloud (10 chapitres). Usage : python3 manga29.py <page>"""
import sys, pathlib
sys.path.insert(0, str(pathlib.Path(__file__).parent))
from manga_gabarit import strip3, apply
F = lambda *a: strip3(*a)
N = dict(rack=False, nuit=False)
STRIPS = [
 ("c1", F("mgal1", "la mauvaise région", "Alibaba 1",
   dict(term=["clients en Chine continentale", "  compte international", "  région Singapour"], bulle=["C'est à côté,", "ça ira."]),
   dict(term=["latence variable, pertes", "  site web bloqué", "  (hébergement sans ICP)"], **N, who='mika', expr='shock', sfx="lent"),
   "choisir selon l'usage", ["où sont les utilisateurs", "site international ou Chine", "ICP avant la mise en ligne", "avis juridique sur les données"],
   "Le choix de la région et du site dépend des utilisateurs et des obligations : pour la Chine continentale, compte adapté, région chinoise et déclaration ICP.")),
 ("c2", F("mgal2", "l'AccessKey du compte principal", "Alibaba 2",
   dict(term=["deploy.sh :", "  AccessKey du compte principal", "  dans le dépôt"], bulle=["Il a tous", "les droits,", "pratique."]),
   dict(term=["dépôt cloné par un tiers", "  clé valide, droits totaux", "  instances de minage"], sfx="clé"),
   "des rôles, pas des clés", ["aucune clé sur le principal", "utilisateurs et rôles RAM", "STS pour la CI", "détection de secrets"],
   "Une AccessKey du compte principal donne tous les droits à qui la trouve : rôles RAM, identifiants temporaires STS, et aucune clé sur le compte principal.")),
 ("c3", F("mgal3", "le groupe de sécurité ouvert", "Alibaba 3",
   dict(term=["groupe de sécurité :", "  22/22 depuis 0.0.0.0/0", "  3389 aussi"], bulle=["Pour dépanner", "vite."]),
   dict(term=["force brute toute la nuit", "  un compte faible trouvé", "  instance compromise"], sfx="22"),
   "rien d'ouvert au monde", ["pas d'adresse publique", "bastion géré, journalisé", "règles depuis le VPC", "audit des règles"],
   "Un port d'administration ouvert au monde finit par céder : pas d'adresse publique, accès par un bastion journalisé, et règles limitées au VPC.")),
 ("c4", F("mgal4", "la base sur une instance préemptible", "Alibaba 4",
   dict(term=["PostgreSQL de recette", "  instance préemptible", "  « 80 % d'économie »"], bulle=["Moins cher,", "même machine."]),
   dict(term=["instance reprise", "  en pleine démonstration", "  données perdues"], **N, who='kai', expr='shock', sfx="repris"),
   "le préemptible pour l'interruptible", ["traitements, CI, sans état", "base : service géré", "sauvegardes testées", "coûts suivis par étiquette"],
   "Une instance préemptible peut être reprise à tout moment : elle sert aux traitements interruptibles, jamais à une base.")),
 ("c5", F("mgal5", "l'API du cluster ouverte", "Alibaba 5",
   dict(term=["ACK : API publique", "  kubeconfig admin", "  partagé à toute l'équipe"], bulle=["Tout le monde", "peut déployer."]),
   dict(term=["kubeconfig sur un poste volé", "  accès administrateur", "  au cluster de production"], sfx="admin"),
   "un cluster fermé", ["API privée ou restreinte", "rôles par espace de noms", "identités des Pods (RRSA)", "audit vers SLS"],
   "Un cluster dont l'API est ouverte et les droits partagés se prend en un fichier : API restreinte, rôles par espace de noms, identités des Pods et audit.")),
 ("c6", F("mgal6", "le compartiment OSS public", "Alibaba 6",
   dict(term=["compartiment des pièces jointes", "  lecture publique", "  « pour l'appli mobile »"], bulle=["C'est plus", "simple."]),
   dict(term=["URL devinables", "  documents d'incidents", "  indexés par un moteur"], sfx="public"),
   "privé et signé", ["blocage de l'accès public", "URL signées à courte durée", "chiffrement KMS", "journal des accès"],
   "Un compartiment public expose tout ce qu'il contient : il reste privé, et l'application distribue des URL signées à courte durée.")),
 ("c7", F("mgal7", "la requête qui lit tout", "Alibaba 7",
   dict(term=["SELECT zone, count(*)", "  FROM incidents", "  -- sans filtre de partition"], bulle=["Juste un", "comptage."]),
   dict(term=["5 ans d'historique lus", "  chaque jour", "  facture multipliée par 10"], sfx="× 10"),
   "lire le strict nécessaire", ["filtre sur la partition", "quotas et alertes de coût", "plan d'exécution vérifié", "tables agrégées"],
   "Dans un entrepôt facturé au volume lu, une requête sans filtre de partition relit tout l'historique : on filtre, on fixe des quotas et on surveille le coût.")),
 ("c8", F("mgal8", "l'incident sans journaux", "Alibaba 8",
   dict(term=["SLS : non configuré", "  ActionTrail : désactivé", "  « on verra plus tard »"], bulle=["On a les", "journaux des", "machines."]),
   dict(term=["incident de sécurité :", "  qui ? quand ? d'où ?", "  aucune trace"], **N, who='mika', expr='angry', pose='hips', sfx="?"),
   "tracer dès le départ", ["ActionTrail vers le compte sécurité", "journaux applicatifs dans SLS", "alertes sur requêtes", "rétention définie"],
   "Sans journaux, un incident ne s'explique pas : ActionTrail et SLS se configurent le premier jour, avec une rétention et des alertes.")),
 ("c9", F("mgal9", "les données qui traversent la frontière", "Alibaba 9",
   dict(term=["données personnelles", "  collectées en Chine", "  copiées vers Francfort"], bulle=["Les données", "sont à nous."]),
   dict(term=["contrôle de conformité :", "  transfert non encadré", "  (PIPL)"], **N, who='kai', expr='shock', sfx="PIPL"),
   "localiser et encadrer", ["cartographier les flux", "avis juridique local", "données gardées en Chine si requis", "registre des traitements"],
   "Un transfert de données personnelles hors de Chine suit des règles précises : on cartographie les flux, on demande un avis juridique, et l'architecture garde les données là où la loi l'exige.")),
 ("c10", F("mgal10", "copier l'architecture AWS telle quelle", "Alibaba 10",
   dict(term=["plan : même Terraform", "  « on change juste", "  le fournisseur »"], bulle=["Deux", "semaines."]),
   dict(term=["arguments inconnus", "  quotas trop bas", "  fonctions absentes"], **N, who='mika', expr='shock', sfx="écarts"),
   "correspondre, puis tester", ["tableau des correspondances", "écarts constatés, pas supposés", "quotas demandés tôt", "pilote avant promesse"],
   "Deux clouds se ressemblent sans être identiques : on établit les correspondances, on constate les écarts sur un pilote, et on chiffre avant de promettre.")),
]
if __name__ == '__main__': apply(sys.argv[1], STRIPS)
