"""Planches manga du cours AWS (11 chapitres). Usage : python3 manga28.py <page>"""
import sys, pathlib
sys.path.insert(0, str(pathlib.Path(__file__).parent))
from manga_gabarit import strip3, apply
F = lambda *a: strip3(*a)
N = dict(rack=False, nuit=False)
STRIPS = [
 ("c1", F("mgaw1", "le compte racine du quotidien", "AWS 1",
   dict(term=["connexion : compte racine", "  MFA : non", "  clé d'accès sur le poste"], bulle=["C'est plus", "simple, j'ai", "tous les droits."]),
   dict(term=["poste compromis", "  clé racine utilisée", "  60 instances créées"], sfx="racine"),
   "la racine sous clé", ["MFA matérielle", "aucune clé d'accès racine", "IAM Identity Center", "rôles temporaires"],
   "Le compte racine a tous les droits et ne se limite pas : on le protège par MFA, sans clé d'accès, et on travaille par identités fédérées et rôles temporaires.")),
 ("c2", F("mgaw2", "Action : *, Resource : *", "AWS 2",
   dict(term=["politique du rôle de CI :", "  \"Action\": \"*\"", "  \"Resource\": \"*\""], bulle=["Pour débloquer", "le déploiement."]),
   dict(term=["erreur dans le script", "  aws rds delete-db-cluster", "  base de production supprimée"], sfx="delete"),
   "le moindre privilège", ["actions et ressources précises", "Access Analyzer", "refus explicite du sensible", "protection contre la suppression"],
   "Un joker dans une politique transforme chaque erreur en catastrophe : actions et ressources précises, refus explicites sur le sensible, et protection contre la suppression.")),
 ("c3", F("mgaw3", "tout en sous-réseau public", "AWS 3",
   dict(term=["instances de l'API :", "  sous-réseau public", "  IP publique, port 22"], bulle=["Pour les mises", "à jour."]),
   dict(term=["scan d'Internet :", "  22 et 8080 ouverts", "  tentatives toute la nuit"], sfx="scan"),
   "privé par défaut", ["applications en sous-réseau privé", "seul l'ALB est public", "Session Manager, pas SSH", "points de terminaison VPC"],
   "Une instance joignable depuis Internet est attaquée en minutes : les applications vivent en privé, seul l'équilibreur est exposé, et l'administration passe par Session Manager.")),
 ("c4", F("mgaw4", "l'instance qu'on soigne", "AWS 4",
   dict(term=["i-0a1b… : production", "  en service depuis 2023", "  modifiée à la main"], bulle=["Elle marche,", "on n'y touche", "pas."]),
   dict(term=["disque corrompu", "  aucune image, aucun script", "  4 heures pour la refaire"], sfx="4 h"),
   "remplacer, pas réparer", ["image dorée (Packer)", "modèle de lancement", "groupe Auto Scaling", "configuration par code"],
   "Une instance soignée à la main ne se reconstruit plus : image dorée, modèle de lancement et Auto Scaling remplacent une instance défaillante en quelques minutes.")),
 ("c5", F("mgaw5", "le compartiment sans versioning", "AWS 5",
   dict(term=["crise-pieces-jointes", "  versioning : désactivé", "  sauvegarde : aucune"], bulle=["S3 ne perd", "jamais rien."]),
   dict(term=["script de migration :", "  12 000 objets écrasés", "  par des fichiers vides"], sfx="perdu"),
   "pouvoir revenir en arrière", ["versioning activé", "cycle de vie des versions", "AWS Backup, autre compte", "restauration testée"],
   "S3 ne perd pas les données, mais il exécute fidèlement les erreurs : versioning, cycle de vie et sauvegarde dans un autre compte permettent de revenir en arrière.")),
 ("c6", F("mgaw6", "la base dans une seule zone", "AWS 6",
   dict(term=["RDS PostgreSQL", "  Multi-AZ : non", "  « on économise »"], bulle=["Elle ne tombe", "jamais."]),
   dict(term=["maintenance de la zone", "  40 minutes d'arrêt", "  en pleine alerte météo"], sfx="40 min"),
   "une base qui bascule", ["Multi-AZ ou Aurora", "reconnexion automatique", "fenêtre de maintenance choisie", "bascule testée"],
   "Une base dans une seule zone s'arrête à chaque maintenance ou panne : Multi-AZ ou Aurora basculent en une à deux minutes, et l'application se reconnecte seule.")),
 ("c7", F("mgaw7", "l'appel direct qui déborde", "AWS 7",
   dict(term=["réception des alertes", "  appelle le service SMS", "  en direct"], bulle=["Plus simple", "qu'une file."]),
   dict(term=["pic : 10 000 alertes", "  service SMS saturé", "  réception en erreur"], sfx="503"),
   "découpler par une file", ["SNS puis SQS", "consommateur idempotent", "file d'échec surveillée", "alerte sur le retard"],
   "Un appel direct propage la panne du plus lent : une file absorbe le pic, le consommateur traite à son rythme, et rien ne se perd.")),
 ("c8", F("mgaw8", "un seul compte pour tout", "AWS 8",
   dict(term=["un compte AWS", "  prod, recette, bac à sable", "  mêmes droits pour tous"], bulle=["On s'y", "retrouve."]),
   dict(term=["« je nettoie la recette »", "  base de production supprimée", "  mauvais onglet"], **N, who='kai', expr='shock', sfx="prod"),
   "des comptes séparés", ["Organizations et unités", "un compte par environnement", "SCP de protection", "Control Tower"],
   "Tout dans un compte, c'est toutes les erreurs au même endroit : des comptes par environnement, des garde-fous d'organisation et des rôles propres à chaque compte.")),
 ("c9", F("mgaw9", "l'alarme que personne ne reçoit", "AWS 9",
   dict(term=["alarme file d'échec", "  → sujet SNS", "  abonnés : 0"], bulle=["L'alarme", "existe, c'est", "bon."]),
   dict(term=["deux jours plus tard :", "  3 000 notifications", "  jamais envoyées"], **N, who='mika', expr='shock', sfx="2 j"),
   "une alarme qui arrive", ["reliée à l'astreinte", "testée à la création", "runbook dans l'alarme", "contrôle des alarmes orphelines"],
   "Une alarme sans destinataire ne prévient personne : chaque alarme de page est reliée à l'astreinte, testée, et accompagnée de son runbook.")),
 ("c10", F("mgaw10", "le plan de reprise jamais joué", "AWS 10",
   dict(term=["plan de reprise : 30 pages", "  région de secours : prévue", "  exercice : jamais"], who='sensei', expr='neutral', pose='stand', bulle=["Tout est", "écrit."]),
   dict(term=["jour J : quotas absents", "  image introuvable, DNS figé", "  8 heures au lieu de 30 min"], sfx="8 h"),
   "une reprise prouvée", ["exercice planifié chaque semestre", "RPO et RTO mesurés", "quotas et images vérifiés", "runbook corrigé"],
   "Un plan de reprise non joué est une hypothèse : on l'exerce, on mesure RPO et RTO, et on corrige tout ce qui a manqué.")),
 ("c11", F("mgaw11", "réciter deux cents services", "AWS 11",
   dict(term=["entretien architecte :", "  « EC2, S3, Lambda, Glue,", "  Kinesis, Outposts… »"], bulle=["Je connais", "tout le", "catalogue."]),
   dict(term=["« et pour une application", "  de crise nationale ? »", "  … liste de services"], **N, who='kai', expr='shock', sfx="…"),
   "raisonner en exigences", ["exigences d'abord", "architecture et compromis", "sécurité et exploitation", "coût et reprise"],
   "Un architecte ne récite pas un catalogue : il part des exigences, propose une architecture, explique ses compromis, sa sécurité, son exploitation et son coût.")),
]
if __name__ == '__main__': apply(sys.argv[1], STRIPS)
