"""Planches manga du cours Cloud (10 chapitres). Usage : python3 manga18.py <page>"""
import sys, pathlib
sys.path.insert(0, str(pathlib.Path(__file__).parent))
from manga_gabarit import strip3, apply
F = lambda *a: strip3(*a)
N = dict(rack=False, nuit=False)
STRIPS = [
 ("c1", F("mgc1", "le cloud, c'est l'ordinateur des autres", "Cloud 1",
   dict(term=["bucket S3 créé", "  chiffrement : par défaut", "  accès public : « à voir »"], bulle=["Le cloud gère", "la sécurité."]),
   dict(term=["bucket public indexé", "  12 000 fichiers clients", "« c'était à vous de fermer »"], sfx="public"),
   "la responsabilité partagée", ["le fournisseur : le matériel", "toi : données, accès, config", "Block Public Access partout", "revue de configuration continue"],
   "Le fournisseur sécurise l'infrastructure ; la configuration, les accès et les données restent de ta responsabilité, et un bucket ouvert est toujours ta faute.")),
 ("c2", F("mgc2", "AdministratorAccess pour tout le monde", "Cloud 2",
   dict(term=["groupe « devs » :", "  AdministratorAccess", "  « pour ne pas bloquer »"], bulle=["On gagne du", "temps."]),
   dict(term=["un stagiaire supprime", "  la mauvaise pile", "prod détruite, pas de garde-fou"], sfx="détruit"),
   "le moindre privilège", ["SSO et rôles par métier", "permission boundaries", "SCP : interdits d'organisation", "prod dans un compte séparé"],
   "Des droits d'administrateur pour tous transforment chaque erreur en incident : SSO, rôles par métier, limites de permissions et comptes séparés contiennent l'impact.")),
 ("c3", F("mgc3", "la base dans le sous-réseau public", "Cloud 3",
   dict(term=["RDS : publicly_accessible", "  = true", "SG : 5432 depuis 0.0.0.0/0"], bulle=["Pour me", "connecter depuis", "chez moi."]),
   dict(term=["scan d'Internet : 5432 ouvert", "4 000 tentatives de connexion", "  par heure"], sfx="5432"),
   "rien d'exposé par défaut", ["base en sous-réseau privé", "accès via SSM ou bastion", "SG par référence, pas par IP", "VPC endpoints pour S3"],
   "Une base accessible depuis Internet est attaquée en quelques minutes : elle vit en sous-réseau privé, on y accède par Session Manager, et les groupes de sécurité se référencent entre eux.")),
 ("c4", F("mgc4", "le serverless qui s'endort", "Cloud 4",
   dict(term=["API critique en Lambda", "  Java, 1 Go de dépendances", "  appelée 3 fois par heure"], bulle=["On ne paie", "que l'usage."]),
   dict(term=["premier appel : 6 s", "  (démarrage à froid)", "timeout du client : 5 s"], sfx="6 s"),
   "choisir le bon calcul", ["Lambda : événementiel, court", "SnapStart ou runtime léger", "conteneur managé si latence", "mesurer p99, pas la moyenne"],
   "Le serverless facture l'usage mais paie son démarrage à froid : on le réserve aux traitements événementiels, on réduit le démarrage, et une API sensible à la latence va sur un conteneur managé.")),
 ("c5", F("mgc5", "la base sans sauvegarde testée", "Cloud 5",
   dict(term=["RDS : sauvegardes 1 jour", "  multi-AZ : non", "  restauration testée : jamais"], bulle=["C'est managé,", "c'est sauvegardé."]),
   dict(term=["DELETE sans WHERE à 17 h", "restauration point-in-time :", "  personne ne sait faire"], sfx="17 h"),
   "managé ne veut pas dire testé", ["rétention 7 à 35 jours", "multi-AZ en production", "restauration testée chaque mois", "copie inter-régions"],
   "Un service managé sauvegarde si on le configure, et la restauration s'apprend avant le sinistre : rétention suffisante, multi-AZ, et un exercice de restauration chaque mois.")),
 ("c6", F("mgc6", "personne ne regarde GuardDuty", "Cloud 6",
   dict(term=["GuardDuty activé", "Security Hub activé", "  alertes : boîte mail partagée"], bulle=["On est", "équipés."]),
   dict(term=["alerte : appels depuis Tor", "  sur une clé de la CI", "lue… 11 jours après"], sfx="11 j"),
   "détecter, c'est aussi traiter", ["alertes routées vers l'astreinte", "runbook par type d'alerte", "réponse automatique (révoquer)", "exercice d'incident trimestriel"],
   "Une détection sans destinataire ne détecte rien : les alertes critiques arrivent à l'astreinte avec un runbook, et les réponses simples, comme révoquer une clé, sont automatisées.")),
 ("c7", F("mgc7", "cliqué en console", "Cloud 7",
   dict(term=["« juste un sous-réseau »", "  créé en console", "  hors Terraform"], bulle=["Deux minutes,", "pas besoin de", "MR."]),
   dict(term=["terraform plan :", "  dérive détectée", "apply : la route disparaît"], sfx="dérive"),
   "tout passe par le code", ["console en lecture seule", "changement = MR + plan relu", "détection de dérive planifiée", "import des ressources orphelines"],
   "Une ressource créée à la main est ignorée ou détruite par le prochain apply : la console reste en lecture seule, et tout changement passe par une MR avec un plan relu.")),
 ("c8", F("mgc8", "les logs qui coûtent plus que l'appli", "Cloud 8",
   dict(term=["CloudWatch Logs :", "  niveau DEBUG en prod", "  rétention : jamais expirer"], bulle=["On ne sait", "jamais."]),
   dict(term=["facture du mois :", "  application 1 200 €", "  logs 3 400 €"], **N, who='mika', expr='shock', sfx="3 400 €"),
   "observer avec mesure", ["niveau INFO en production", "rétention 14 à 30 jours", "archive S3 si obligation", "métriques plutôt que logs"],
   "Des logs verbeux conservés sans limite coûtent plus que l'application : niveau adapté, rétention courte, archivage à froid pour les obligations, et des métriques pour ce qui se compte.")),
 ("c9", F("mgc9", "le NAT qui mange le budget", "Cloud 9",
   dict(term=["les Pods téléchargent", "  images et paquets", "  via la passerelle NAT"], bulle=["Le réseau,", "c'est gratuit."]),
   dict(term=["NAT : 4,1 To traités", "  0,048 $ par Go", "  premier poste de la facture"], **N, who='kai', expr='shock', sfx="NAT"),
   "le transfert se paie", ["VPC endpoints S3 et ECR", "cache de registre local", "coûts ventilés par étiquette", "revue FinOps mensuelle"],
   "Le trafic qui traverse une passerelle NAT est facturé au gigaoctet : des endpoints privés pour S3 et le registre, un cache local, et la facture se lit ligne par ligne chaque mois.")),
 ("c10", F("mgc10", "la souveraineté oubliée", "Cloud 10",
   dict(term=["données de santé", "  hébergées aux États-Unis", "  « c'est le moins cher »"], bulle=["Le cloud n'a", "pas de", "frontières."]),
   dict(term=["audit : hébergement non HDS", "  exigence SecNumCloud", "  migration à prévoir"], **N, who='mika', expr='angry', pose='hips', sfx="HDS"),
   "l'exigence avant l'offre", ["données sensibles : où, qui", "HDS, SecNumCloud si requis", "chiffrement avec tes clés", "plan de réversibilité écrit"],
   "Le choix d'un cloud commence par les exigences de la donnée : localisation, certifications comme HDS ou SecNumCloud, maîtrise des clés et réversibilité, avant le prix.")),
]
if __name__ == '__main__': apply(sys.argv[1], STRIPS)
