"""Planches manga du cours Vue (9 chapitres). Usage : python3 manga14.py <page>"""
import sys, pathlib
sys.path.insert(0, str(pathlib.Path(__file__).parent))
from manga_gabarit import strip3, apply
F = lambda *a: strip3(*a)
STRIPS = [
 ("c1", F("mgv1", "la réactivité perdue", "Vue 1",
   dict(term=["const etat = reactive({ n: 0 })", "const { n } = etat", "// n dans le template"], bulle=["Plus court", "à écrire."]),
   dict(term=["etat.n++ : 1, 2, 3…", "l'écran affiche toujours 0", "n est une simple copie"], rack=False, nuit=False, who='kai', expr='shock', sfx="0"),
   "garder la référence", ["ref() pour les valeurs simples", "toRefs() pour destructurer", "storeToRefs() pour Pinia"],
   "Déstructurer un objet réactif en copie les valeurs et coupe la réactivité : on utilise ref, toRefs ou storeToRefs pour garder le lien.")),
 ("c2", F("mgv2", "l'enfant qui modifie la prop", "Vue 2",
   dict(term=["props: ['incident']", "this.incident.statut =", "  'FERME'"], bulle=["C'est l'enfant", "qui sait."]),
   dict(term=["[Vue warn] mutation d'une prop", "le parent n'est pas au courant", "deux vérités"], rack=False, nuit=False, who='mika', expr='angry', pose='hips', sfx="warn"),
   "les données descendent", ["props en lecture seule", "emit pour remonter l'intention", "defineModel() pour v-model"],
   "Les props descendent, les événements remontent : l'enfant émet une intention et le parent modifie sa donnée, ou on passe par defineModel pour un v-model propre.")),
 ("c3", F("mgv3", "le composable partagé par accident", "Vue 3",
   dict(term=["const filtres = ref({})", "export function useFiltres()", "  { return { filtres } }"], bulle=["Mon composable", "est prêt."]),
   dict(term=["deux pages utilisent", "  useFiltres() :", "elles partagent les filtres"], rack=False, nuit=False, who='kai', expr='shock', sfx="partagé"),
   "l'état dans la fonction", ["déclarer ref() dans useFiltres", "partage voulu : un store Pinia", "nommer : useXxx, retour explicite"],
   "Un ref déclaré hors de la fonction du composable est partagé par tous ses utilisateurs : l'état se déclare dans la fonction, et le partage volontaire passe par un store.")),
 ("c4", F("mgv4", "le bundle de 3 Mo", "Vue 4",
   dict(term=["import Admin from", "  './pages/Admin.vue'", "// 40 pages importées ainsi"], bulle=["Tout est prêt", "tout de suite."]),
   dict(term=["premier chargement :", "  3 Mo de JavaScript", "  6 s sur mobile 4G"], rack=False, nuit=False, who='mika', expr='shock', sfx="6 s"),
   "charger à la demande", ["component: () => import(…)", "une route = un morceau", "préchargement au survol", "budget de taille dans la CI"],
   "Importer toutes les pages dans le routeur les met dans le premier téléchargement : chaque route se charge à la demande, et un budget de taille surveille le poids.")),
 ("c5", F("mgv5", "le jeton persisté", "Vue 5",
   dict(term=["pinia-plugin-persistedstate", "  store auth : { token }", "  → localStorage"], bulle=["On reste", "connecté, c'est", "pratique."]),
   dict(term=["une faille XSS ailleurs :", "  localStorage.token", "  envoyé à un inconnu"], sfx="volé"),
   "rien de sensible côté client", ["session en cookie HttpOnly", "BFF qui porte le jeton", "persister seulement l'UI", "  (thème, filtres)"],
   "Tout ce qui est persisté dans le navigateur est lisible par un script injecté : le jeton reste dans un cookie HttpOnly géré par un BFF, et on ne persiste que des préférences.")),
 ("c6", F("mgv6", "validé côté client seulement", "Vue 6",
   dict(term=["<input v-model='titre'", "  :rules='[requis, max200]'>", "// le formulaire est sûr"], bulle=["Impossible", "d'envoyer un", "titre vide."]),
   dict(term=["curl -d '{\"titre\":\"\"}'", "  /api/incidents", "201 Created"], sfx="201"),
   "valider des deux côtés", ["schéma partagé (Zod, Valibot)", "client : confort", "serveur : la vraie règle", "erreurs lisibles et liées au champ"],
   "La validation côté client aide l'utilisateur mais ne protège rien : la même règle, idéalement un schéma partagé, est appliquée par le serveur.")),
 ("c7", F("mgv7", "le snapshot accepté les yeux fermés", "Vue 7",
   dict(term=["expect(wrapper.html())", "  .toMatchSnapshot()", "// 1 800 lignes"], bulle=["Un test par", "composant,", "vite fait."]),
   dict(term=["snapshot modifié : 312 lignes", "  « u » pour mettre à jour", "le bug est validé"], rack=False, nuit=False, who='mika', expr='angry', pose='hips', sfx="u"),
   "tester ce qui compte", ["Testing Library : rôles, textes", "un comportement par test", "petits snapshots ciblés", "Playwright pour les parcours"],
   "Un snapshot géant se met à jour sans être relu : on teste des comportements précis par les rôles et les textes, et on garde les snapshots petits et ciblés.")),
 ("c8", F("mgv8", "window is not defined", "Vue 8",
   dict(term=["<script setup>", "const large =", "  window.innerWidth > 900"], bulle=["Marche", "parfaitement", "en local."]),
   dict(term=["nuxt build && start", "500 : window is not defined", "  (rendu côté serveur)"], sfx="500"),
   "penser serveur et client", ["onMounted() pour le navigateur", "<ClientOnly> si besoin", "import.meta.client", "tester le build SSR en CI"],
   "En rendu serveur, le code s'exécute d'abord sans navigateur : ce qui touche window ou le DOM va dans onMounted ou ClientOnly, et la CI teste le build SSR.")),
 ("c9", F("mgv9", "réécrire parce que c'est à la mode", "Vue 9",
   dict(term=["application Angular : 6 ans", "  stable, 40 écrans", "« passons à Vue, c'est léger »"], bulle=["Tout le monde", "en parle."]),
   dict(term=["huit mois de réécriture", "  zéro fonctionnalité livrée", "  les mêmes bugs, en Vue"], rack=False, nuit=False, who='kai', expr='shock', sfx="8 mois"),
   "choisir sur des critères", ["compétences de l'équipe", "écosystème et contraintes", "coût de la migration", "une ADR, un pilote borné"],
   "Les trois frameworks livrent de bonnes applications : on choisit sur les compétences, l'écosystème et le coût réel, on l'écrit dans une ADR, et on ne réécrit que sur un gain démontré.")),
]
if __name__ == '__main__': apply(sys.argv[1], STRIPS)
