"""Planches manga de la page Mission en parties (32 chapitres). Reprend les planches de manga32 et en ajoute 15.
Usage : python3 manga33.py <page>"""
import sys, pathlib, runpy
sys.path.insert(0, str(pathlib.Path(__file__).parent))
from manga_gabarit import strip3, apply
F = lambda *a: strip3(*a)
N = dict(rack=False, nuit=False)
ANC = dict(runpy.run_path(str(pathlib.Path(__file__).with_name('manga32.py')), run_name='lib')['STRIPS'])
NEUF = {
 "W1": F("mgw1", "le serveur ouvert à tous", "WildFly 1",
   dict(term=["standalone.sh -b 0.0.0.0", "  -bmanagement 0.0.0.0", "  admin / admin"], bulle=["Comme dans", "le tutoriel."]),
   dict(term=["console de gestion joignable", "  depuis tout le réseau", "  compte par défaut"], sfx="9990"),
   "écouter où il faut", ["-bmanagement sur le réseau d'admin", "utilisateurs nominatifs", "TLS sur la gestion", "ports documentés"],
   "Un serveur de laboratoire recopié en production expose sa console : la gestion n'écoute que sur le réseau d'administration, avec des comptes nominatifs."),
 "W3": F("mgw3", "le pool sans validation", "WildFly 3",
   dict(term=["datasource CriseDS", "  validate-on-match : false", "  exception-sorter : aucun"], bulle=["Oracle ne", "redémarre", "jamais."]),
   dict(term=["redémarrage d'Oracle la nuit", "  connexions mortes gardées", "  erreurs jusqu'au redémarrage"], **N, who='mika', expr='shock', sfx="closed"),
   "un pool qui se répare", ["validation des connexions", "tri des exceptions Oracle", "délai d'attente borné", "test en redémarrant Oracle"],
   "Sans validation, le pool garde des connexions mortes après une coupure : validation et tri des exceptions Oracle le réparent tout seul."),
 "W4": F("mgw4", "la bibliothèque en double", "WildFly 4",
   dict(term=["WEB-INF/lib/hibernate-core-5.6.jar", "  + Hibernate du serveur", "  sans exclusion"], bulle=["Ça marche", "sur mon poste."]),
   dict(term=["production : NoSuchMethodError", "  au démarrage", "  application indisponible"], sfx="NoSuch"),
   "maîtriser le classloading", ["jboss-deployment-structure.xml", "exclure le module du serveur", "ou retirer la copie", "même configuration partout"],
   "Deux versions d'une même bibliothèque se battent au chargement : on exclut explicitement l'une des deux et l'on garde les environnements identiques."),
 "W6": F("mgw6", "le mot de passe dans standalone.xml", "WildFly 6",
   dict(term=["<password>Oracle2026!</password>", "  dans standalone.xml", "  copié dans le wiki"], bulle=["C'est un", "fichier du", "serveur."]),
   dict(term=["sauvegarde partagée", "  fichier lisible par tous", "  mot de passe de production exposé"], **N, who='kai', expr='shock', sfx="fuite"),
   "les secrets dans Elytron", ["magasin d'identifiants", "credential-reference", "droits 640 sur la configuration", "rotation après fuite"],
   "Un mot de passe en clair dans la configuration voyage avec chaque copie : le magasin d'identifiants Elytron le garde chiffré."),
 "W7": F("mgw7", "la migration du vendredi", "WildFly 7",
   dict(term=["« on passe en WildFly 31", "  vendredi soir »", "  (application Struts 1)"], who='sensei', expr='neutral', pose='stand', bulle=["Juste une", "version de", "plus."]),
   dict(term=["ClassNotFoundException :", "  javax.servlet.http.HttpServlet", "  retour arrière à 3 h du matin"], sfx="javax"),
   "une migration est un projet", ["inventaire javax", "options chiffrées et POC", "tests complets en intégration", "retour arrière prêt"],
   "Passer à Jakarta EE 10 casse tout ce qui reste en javax, comme Struts 1 : inventaire, POC et tests avant toute bascule."),
 "O1": F("mgo1", "la date système", "Ordonnancement 1",
   dict(term=["JOUR=$(date +%Y%m%d)", "  chaîne démarrée à 23 h 30"], bulle=["C'est la", "date du jour."]),
   dict(term=["après minuit :", "  fichiers datés du lendemain", "  rapports incohérents"], **N, who='mika', expr='shock', sfx="J+1"),
   "la date d'exploitation", ["fournie par l'ordonnanceur", "passée en paramètre", "validée par le script", "relance = même date"],
   "Une chaîne de nuit qui passe minuit change de date si les scripts lisent l'horloge : la date d'exploitation est un paramètre, fourni par l'ordonnanceur."),
 "O2": F("mgo2", "la chaîne sans point de reprise", "Ordonnancement 2",
   dict(term=["chaîne monolithique", "  10 étapes, 6 heures", "  aucun point de reprise"], bulle=["Elle marche", "presque", "toujours."]),
   dict(term=["échec à l'étape 9", "  tout relancer : 6 heures", "  éditions à 14 h"], sfx="6 h"),
   "découper et reprendre", ["jobs courts et relançables", "état entre les étapes", "contrôles intermédiaires", "écritures idempotentes"],
   "Une chaîne sans point de reprise se relance en entier : des jobs courts et idempotents permettent de repartir de l'étape en échec."),
 "O4": F("mgo4", "forcer en succès", "Ordonnancement 4",
   dict(term=["job calcul : en erreur", "  « force OK »", "  pour débloquer les éditions"], bulle=["Les éditions", "doivent", "partir."]),
   dict(term=["éditions envoyées", "  avec les chiffres de la veille", "  rectificatif aux partenaires"], **N, who='kai', expr='shock', sfx="OK ?"),
   "forcer, c'est exceptionnel", ["analyser avant d'agir", "corriger et relancer", "forcer seulement si justifié", "ticket et accord tracés"],
   "Forcer un job en succès fait croire à la suite que les données sont prêtes : on analyse, on corrige, et le forçage reste exceptionnel et tracé."),
 "O5": F("mgo5", "le changement d'heure", "Ordonnancement 5",
   dict(term=["job planifié à 2 h 30", "  nuit du passage", "  à l'heure d'été"], bulle=["Il tourne", "chaque nuit."]),
   dict(term=["2 h 30 n'existe pas", "  job non lancé", "  personne ne l'a vu"], sfx="2:30"),
   "anticiper le calendrier", ["pas de planification 2 h – 3 h", "ou heures en UTC", "cas particuliers testés", "vérification matinale"],
   "Les nuits de changement d'heure, 2 h 30 n'existe pas ou existe deux fois : on évite la plage, ou on planifie en UTC, et on teste."),
 "O6": F("mgo6", "la chaîne modifiée en production", "Ordonnancement 6",
   dict(term=["console de production :", "  dépendance ajoutée à la main", "  intégration inchangée"], bulle=["C'était", "urgent."]),
   dict(term=["mise en production suivante :", "  définition écrasée", "  la dépendance disparaît"], **N, who='mika', expr='angry', pose='hips', sfx="écrasé"),
   "les chaînes comme code", ["définitions versionnées", "relecture en MR", "tests en intégration", "livraison par la chaîne"],
   "Une chaîne modifiée à la main en production diverge de l'intégration et se fait écraser : les définitions vivent dans le dépôt et se livrent."),
 "U1": F("mgu1", "kill -9 d'abord", "Unix 1",
   dict(term=["WildFly lent", "  kill -9 <pid>", "  (réflexe)"], bulle=["Ça redémarre", "plus vite."]),
   dict(term=["transactions interrompues", "  fichier de sortie tronqué", "  reprise manuelle des données"], sfx="-9"),
   "arrêter proprement", ["arrêt gracieux par la CLI", "kill -TERM sinon", "-KILL en dernier recours", "tracer l'action"],
   "kill -9 ne laisse rien terminer : on arrête proprement, et on ne force qu'en dernier recours, en le traçant."),
 "U3": F("mgu3", "le grep sur 40 Go", "Unix 3",
   dict(term=["grep -r ERROR /var/log", "  40 Go, en production", "  à 10 h du matin"], bulle=["Juste une", "recherche."]),
   dict(term=["disques saturés", "  application ralentie", "  pour tous les utilisateurs"], **N, who='kai', expr='shock', sfx="I/O"),
   "chercher sans nuire", ["cibler fichiers et période", "zgrep sur les compressés", "nice et ionice", "copie vers une machine d'analyse"],
   "Une recherche massive sur un serveur de production le ralentit pour tous : on cible, on filtre, on baisse la priorité, ou on analyse ailleurs."),
 "U4": F("mgu4", "le disque plein de journaux", "Unix 4",
   dict(term=["niveau DEBUG laissé actif", "  aucune rotation", "  /var à 98 %"], bulle=["On fera le", "ménage plus", "tard."]),
   dict(term=["disque plein à 3 h", "  WildFly ne peut plus écrire", "  chaîne de nuit en échec"], sfx="100 %"),
   "des journaux maîtrisés", ["logrotate ou rotation applicative", "rétention et compression", "alerte à 80 %", "niveau INFO en production"],
   "Des journaux sans rotation finissent par remplir le disque et arrêter le service : rotation, rétention, alerte d'espace et bon niveau de journal."),
 "U5": F("mgu5", "Stop-Process sans filtre", "Unix 5",
   dict(term=["Get-Process java |", "  Stop-Process", "  # arrêter WildFly"], bulle=["Tous les java,", "c'est pareil."]),
   dict(term=["WildFly arrêté…", "  et l'outil de supervision", "  et le batch de paie"], **N, who='mika', expr='shock', sfx="×3"),
   "cibler, puis agir", ["Stop-Service du bon service", "filtre par identifiant", "-WhatIf d'abord", "script testé avec Pester"],
   "Un pipeline agit sur tout ce qu'il reçoit : on cible précisément, on essaie avec -WhatIf, et l'on passe par le service."),
 "U6": F("mgu6", "le mot de passe dans le script", "Unix 6",
   dict(term=["export.sh :", "  PASS='Prod2026!'", "  versionné depuis 2019"], bulle=["Le dépôt est", "interne."]),
   dict(term=["dépôt copié par un prestataire", "  mot de passe de production", "  valide depuis 7 ans"], sfx="secret"),
   "aucun secret dans le code", ["coffre ou variable injectée", "gitleaks en CI", "rotation après exposition", "droits minimaux"],
   "Un secret dans un script se copie avec lui : il vient d'un coffre ou de l'environnement, et la CI refuse tout secret dans le dépôt."),
}
ORDRE = ["c1", "c2", "c5", "c13", "c14", "c15", "W1", "c3", "W3", "W4", "c4", "W6", "W7", "O1", "O2", "c6", "O4", "O5", "O6",
         "U1", "c7", "U3", "U4", "U5", "U6", "c8", "c9", "c10", "c11", "c12", "c16", "c17"]
STRIPS = [(f"c{i}", NEUF[k] if k in NEUF else ANC[k]) for i, k in enumerate(ORDRE, 1)]
if __name__ == '__main__': apply(sys.argv[1], STRIPS)
